//! Translate an enforced dbt model contract into a Rocky `.contract.toml`.
//!
//! A dbt contract (`config: { contract: { enforced: true } }`) declares every
//! output column with a `data_type` and optional `constraints`. Rocky checks a
//! `<model>.contract.toml` next to the model at compile time. This module
//! writes that file from the manifest's columns:
//!
//! - `data_type` maps to a Rocky contract type name.
//! - `not_null` and `primary_key` constraints map to `nullable = false`.
//! - Every declared column goes in `[rules] required`.
//!
//! Anything Rocky cannot check is counted, so the caller can warn: a type
//! with no Rocky name, and the constraints `unique`, `check`, `foreign_key`
//! and `custom`.

use std::fmt::Write as _;

use rocky_core::contracts::warehouse_type_to_rocky;
use rocky_ir::RockyType;

use super::dbt_manifest::DbtManifestNode;

/// A generated contract and what could not be carried over.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ImportedContract {
    /// File body for `<model>.contract.toml`.
    pub toml: String,
    /// Columns whose `data_type` has no Rocky type name. The column is still
    /// required; only its type is not checked.
    pub untyped_columns: usize,
    /// Constraints Rocky does not check.
    pub unmapped_constraints: usize,
}

/// Build the contract for `node`, or `None` when the node declares no
/// enforced contract or no columns.
pub fn contract_from_node(node: &DbtManifestNode) -> Option<ImportedContract> {
    if !node.config.contract.as_ref().is_some_and(|c| c.enforced) || node.columns.is_empty() {
        return None;
    }
    let mut columns: Vec<_> = node.columns.values().collect();
    columns.sort_by(|a, b| a.name.cmp(&b.name));

    let mut toml =
        String::from("# Generated by `rocky import-dbt` from an enforced dbt contract.\n");
    let mut untyped_columns = 0;
    let mut unmapped_constraints = 0;
    for column in &columns {
        toml.push_str("\n[[columns]]\n");
        let _ = writeln!(toml, "name = {}", toml_string(&column.name));
        if let Some(data_type) = column.data_type.as_deref() {
            match contract_type_name(data_type) {
                Some(name) => {
                    let _ = writeln!(toml, "type = {}", toml_string(&name));
                }
                None => untyped_columns += 1,
            }
        }
        let mut not_null = false;
        for constraint in &column.constraints {
            match constraint.to_ascii_lowercase().as_str() {
                "not_null" | "primary_key" => not_null = true,
                _ => unmapped_constraints += 1,
            }
        }
        if not_null {
            toml.push_str("nullable = false\n");
        }
    }
    let required: Vec<String> = columns.iter().map(|c| toml_string(&c.name)).collect();
    let _ = write!(toml, "\n[rules]\nrequired = [{}]\n", required.join(", "));
    Some(ImportedContract {
        toml,
        untyped_columns,
        unmapped_constraints,
    })
}

/// Map a warehouse type string from a dbt contract to a contract type name.
///
/// `None` for a type Rocky has no name for (`json`, `uuid`, ...), so the
/// contract leaves it unchecked. A decimal maps to bare `Decimal` (any
/// precision and scale): Rocky's inferred precision for computed decimals can
/// differ from the warehouse's, and a false mismatch would refuse a valid
/// model.
fn contract_type_name(data_type: &str) -> Option<String> {
    let name = match warehouse_type_to_rocky(data_type) {
        RockyType::Boolean => "Boolean",
        RockyType::Int32 => "Int32",
        RockyType::Int64 => "Int64",
        RockyType::Float32 => "Float32",
        RockyType::Float64 => "Float64",
        RockyType::Decimal { .. } => "Decimal",
        RockyType::String => "String",
        RockyType::Binary => "Binary",
        RockyType::Date => "Date",
        RockyType::Timestamp => "Timestamp",
        RockyType::TimestampNtz => "TimestampNtz",
        RockyType::Variant => "Variant",
        RockyType::Array(_) | RockyType::Map(_, _) | RockyType::Struct(_) | RockyType::Unknown => {
            return None;
        }
    };
    Some(name.to_string())
}

/// A TOML basic string.
fn toml_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            c if c.is_control() => {
                let _ = write!(out, "\\u{:04X}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::contracts::CompilerContract;

    fn parse(toml: &str) -> CompilerContract {
        toml::from_str(toml).expect("generated contract parses")
    }

    #[test]
    fn maps_types_and_constraints() {
        let manifest = serde_json::json!({
            "metadata": { "project_name": "p" },
            "nodes": { "model.p.m": {
                "unique_id": "model.p.m", "name": "m", "resource_type": "model",
                "compiled_code": "SELECT 1", "raw_code": "SELECT 1",
                "depends_on": { "nodes": [], "macros": [] },
                "config": { "materialized": "table", "contract": { "enforced": true } },
                "columns": {
                    "id": { "name": "id", "data_type": "bigint", "constraints": [{ "type": "not_null" }, { "type": "primary_key" }] },
                    "total": { "name": "total", "data_type": "decimal(18,2)" },
                    "note": { "name": "note", "data_type": "varchar", "constraints": [{ "type": "not_null" }] },
                    "blob": { "name": "blob", "data_type": "geography", "constraints": [{ "type": "unique" }] }
                },
                "tags": [], "schema": "s", "database": "d"
            }},
            "sources": {}
        });
        let dir = tempfile::TempDir::new().unwrap();
        let path = dir.path().join("manifest.json");
        std::fs::write(&path, manifest.to_string()).unwrap();
        let parsed_manifest = crate::import::dbt_manifest::parse_manifest(&path).unwrap();
        let node = &parsed_manifest.nodes["model.p.m"];
        let contract = contract_from_node(node).expect("enforced contract");
        let parsed = parse(&contract.toml);
        let by_name = |n: &str| parsed.columns.iter().find(|c| c.name == n).unwrap();
        assert_eq!(by_name("id").type_name.as_deref(), Some("Int64"));
        assert_eq!(by_name("id").nullable, Some(false));
        assert_eq!(by_name("total").type_name.as_deref(), Some("Decimal"));
        assert_eq!(by_name("total").nullable, None);
        assert_eq!(by_name("note").type_name.as_deref(), Some("String"));
        assert_eq!(by_name("note").nullable, Some(false));
        assert_eq!(by_name("blob").type_name, None);
        assert_eq!(parsed.rules.required, ["blob", "id", "note", "total"]);
        assert_eq!(contract.untyped_columns, 1);
        assert_eq!(contract.unmapped_constraints, 1);
    }
}
