//! Translate an enforced dbt model contract into a Rocky `.contract.toml`.
//!
//! A dbt contract (`config: { contract: { enforced: true } }`) declares every
//! output column with a `data_type` and optional `constraints`. Rocky checks a
//! `<model>.contract.toml` next to the model at compile time. This module
//! writes that file from the manifest's columns:
//!
//! - `data_type` maps to a Rocky contract type name, read for the dbt
//!   adapter where the name means different types on different warehouses.
//! - Every declared column goes in `[rules] required`.
//!
//! Anything Rocky cannot check is counted, so the caller can warn: a type
//! with no Rocky name (or none Rocky reads the same way on that warehouse),
//! the constraints `unique`, `check`, `foreign_key` and `custom`, and the
//! `not_null` and `primary_key` constraints.
//!
//! A `not_null` or `primary_key` constraint does not become
//! `nullable = false`. Rocky checks `nullable = false` at compile time
//! (`E012`), and it cannot prove a column NOT NULL when the column comes
//! straight from a source table, so the check would refuse a valid model. The
//! file names each such column in a comment instead.

use std::fmt::Write as _;

use rocky_core::contracts::warehouse_type_to_rocky;
use rocky_ir::RockyType;

use super::dbt_manifest::DbtManifestNode;

/// A generated contract and what could not be carried over.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ImportedContract {
    /// File body for `<model>.contract.toml`.
    pub toml: String,
    /// Columns whose `data_type` has no Rocky type name. The column is still
    /// required; only its type is not checked.
    pub untyped_columns: usize,
    /// Constraints Rocky does not check, other than `not_null` and
    /// `primary_key`.
    pub unmapped_constraints: usize,
    /// `not_null` and `primary_key` constraints, which the contract does not
    /// check (see the module docs).
    pub not_null_constraints: usize,
}

/// Build the contract for `node`, or `None` when the node declares no
/// enforced contract or no columns.
///
/// `adapter` is the dbt adapter type from the manifest (`snowflake`,
/// `postgres`, ...), when known. It decides what a `float` or a bare
/// `timestamp` means; with no adapter, those columns are left unchecked.
pub fn contract_from_node(
    node: &DbtManifestNode,
    adapter: Option<&str>,
) -> Option<ImportedContract> {
    if !node.config.contract.as_ref().is_some_and(|c| c.enforced) || node.columns.is_empty() {
        return None;
    }
    let mut columns: Vec<_> = node.columns.values().collect();
    columns.sort_by(|a, b| a.name.cmp(&b.name));

    let mut toml =
        String::from("# Generated by `rocky import-dbt` from an enforced dbt contract.\n");
    let mut untyped_columns = 0;
    let mut unmapped_constraints = 0;
    let mut not_null_constraints = 0;
    for column in &columns {
        toml.push_str("\n[[columns]]\n");
        let _ = writeln!(toml, "name = {}", toml_string(&column.name));
        if let Some(data_type) = column.data_type.as_deref() {
            match contract_type_name(data_type, adapter) {
                Some(name) => {
                    let _ = writeln!(toml, "type = {}", toml_string(&name));
                }
                None => {
                    untyped_columns += 1;
                    let _ = writeln!(
                        toml,
                        "# dbt data_type {}: not checked, Rocky has no type for it here",
                        toml_string(data_type)
                    );
                }
            }
        }
        let mut not_null = false;
        for constraint in &column.constraints {
            match constraint.to_ascii_lowercase().as_str() {
                "not_null" | "primary_key" => {
                    not_null_constraints += 1;
                    not_null = true;
                }
                _ => unmapped_constraints += 1,
            }
        }
        if not_null {
            toml.push_str(
                "# dbt not_null: not checked here. Rocky cannot prove NOT NULL from the \
                 sources;\n# add a `not_null` test to the model to check the data.\n",
            );
        }
    }
    let required: Vec<String> = columns.iter().map(|c| toml_string(&c.name)).collect();
    let _ = write!(toml, "\n[rules]\nrequired = [{}]\n", required.join(", "));
    Some(ImportedContract {
        toml,
        untyped_columns,
        unmapped_constraints,
        not_null_constraints,
    })
}

/// Map a warehouse type string from a dbt contract to a contract type name.
///
/// `None` for a type Rocky has no name for (`json`, `uuid`, ...), so the
/// contract leaves it unchecked. A decimal maps to bare `Decimal` (any
/// precision and scale): Rocky's inferred precision for computed decimals can
/// differ from the warehouse's, and a false mismatch would refuse a valid
/// model.
///
/// Some names mean different types on different warehouses, so they are
/// read for `adapter` (see [`adapter_type_name`]).
fn contract_type_name(data_type: &str, adapter: Option<&str>) -> Option<String> {
    let normalized = data_type.trim().to_ascii_lowercase();
    if let Some(answer) = adapter_type_name(&normalized, adapter) {
        return answer.map(str::to_string);
    }
    let name = match warehouse_type_to_rocky(data_type) {
        RockyType::Boolean => "Boolean",
        RockyType::Int32 => "Int32",
        RockyType::Int64 => "Int64",
        RockyType::Float32 => "Float32",
        RockyType::Float64 => "Float64",
        RockyType::Decimal { .. } => "Decimal",
        RockyType::String => "String",
        RockyType::Binary => "Binary",
        RockyType::Date => "Date",
        RockyType::Timestamp => "Timestamp",
        RockyType::TimestampNtz => "TimestampNtz",
        RockyType::Variant => "Variant",
        RockyType::Array(_) | RockyType::Map(_, _) | RockyType::Struct(_) | RockyType::Unknown => {
            return None;
        }
    };
    Some(name.to_string())
}

/// The contract type of a name whose meaning depends on the warehouse.
///
/// `None` when the name means the same everywhere (the caller maps it).
/// `Some(None)` leaves the column unchecked: the adapter is unknown, or Rocky
/// does not read the warehouse's type the same way it reads the name.
///
/// - `float` is 64-bit on Snowflake, BigQuery, PostgreSQL and Redshift, and
///   32-bit on DuckDB, Databricks and Spark. On BigQuery, PostgreSQL and
///   Redshift Rocky reads the landed column as `Float64`. On Snowflake it
///   reads the landed `FLOAT` as `Float32`, so neither type would be right:
///   unchecked. Snowflake lands every floating-point name (`double`,
///   `double precision`, `real`, `float4`, `float8`) as that same `FLOAT`,
///   so they are unchecked there too.
/// - A bare `timestamp` is a timestamp Rocky reads as `Timestamp` on DuckDB,
///   PostgreSQL, Redshift, BigQuery, Databricks and Spark. On Snowflake it is
///   `TIMESTAMP_NTZ` by default, which Rocky reads as `TimestampNtz`, while
///   a `CAST(... AS TIMESTAMP)` in the model is `Timestamp`: unchecked.
/// - Snowflake integers are all `NUMBER(38,0)` once landed, which Rocky reads
///   as a decimal, while a computed count is `Int64`: unchecked.
fn adapter_type_name(normalized: &str, adapter: Option<&str>) -> Option<Option<&'static str>> {
    let adapter = adapter.map(str::to_ascii_lowercase);
    let adapter = adapter.as_deref();
    match normalized {
        "double" | "double precision" | "real" | "float4" | "float8"
            if adapter == Some("snowflake") =>
        {
            Some(None)
        }
        "float" => Some(match adapter {
            Some("bigquery" | "postgres" | "redshift") => Some("Float64"),
            Some("duckdb" | "databricks" | "spark") => Some("Float32"),
            _ => None,
        }),
        "timestamp" => Some(match adapter {
            Some("duckdb" | "postgres" | "redshift" | "bigquery" | "databricks" | "spark") => {
                Some("Timestamp")
            }
            _ => None,
        }),
        "int" | "integer" | "bigint" | "smallint" | "tinyint" | "byteint"
            if adapter == Some("snowflake") =>
        {
            Some(None)
        }
        _ => None,
    }
}

/// A TOML basic string.
fn toml_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            c if c.is_control() => {
                let _ = write!(out, "\\u{:04X}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::contracts::CompilerContract;

    fn parse(toml: &str) -> CompilerContract {
        toml::from_str(toml).expect("generated contract parses")
    }

    #[test]
    fn maps_types_and_constraints() {
        let manifest = serde_json::json!({
            "metadata": { "project_name": "p" },
            "nodes": { "model.p.m": {
                "unique_id": "model.p.m", "name": "m", "resource_type": "model",
                "compiled_code": "SELECT 1", "raw_code": "SELECT 1",
                "depends_on": { "nodes": [], "macros": [] },
                "config": { "materialized": "table", "contract": { "enforced": true } },
                "columns": {
                    "id": { "name": "id", "data_type": "bigint", "constraints": [{ "type": "not_null" }, { "type": "primary_key" }] },
                    "total": { "name": "total", "data_type": "decimal(18,2)" },
                    "note": { "name": "note", "data_type": "varchar", "constraints": [{ "type": "not_null" }] },
                    "blob": { "name": "blob", "data_type": "geography", "constraints": [{ "type": "unique" }] }
                },
                "tags": [], "schema": "s", "database": "d"
            }},
            "sources": {}
        });
        let dir = tempfile::TempDir::new().unwrap();
        let path = dir.path().join("manifest.json");
        std::fs::write(&path, manifest.to_string()).unwrap();
        let parsed_manifest = crate::import::dbt_manifest::parse_manifest(&path).unwrap();
        let node = &parsed_manifest.nodes["model.p.m"];
        let contract = contract_from_node(node, Some("duckdb")).expect("enforced contract");
        let parsed = parse(&contract.toml);
        let by_name = |n: &str| parsed.columns.iter().find(|c| c.name == n).unwrap();
        assert_eq!(by_name("id").type_name.as_deref(), Some("Int64"));
        assert_eq!(
            by_name("id").nullable,
            None,
            "a not_null constraint is not checked: Rocky cannot prove it from the sources"
        );
        assert_eq!(by_name("total").type_name.as_deref(), Some("Decimal"));
        assert_eq!(by_name("total").nullable, None);
        assert_eq!(by_name("note").type_name.as_deref(), Some("String"));
        assert_eq!(by_name("note").nullable, None);
        assert_eq!(by_name("blob").type_name, None);
        assert_eq!(parsed.rules.required, ["blob", "id", "note", "total"]);
        assert_eq!(contract.untyped_columns, 1);
        assert_eq!(contract.unmapped_constraints, 1);
        assert_eq!(contract.not_null_constraints, 3);
        assert!(
            contract.toml.contains("# dbt not_null: not checked here"),
            "the file says why: {}",
            contract.toml
        );
        assert!(!contract.toml.contains("nullable = false"));
    }

    fn node_with(columns: &serde_json::Value) -> DbtManifestNode {
        let manifest = serde_json::json!({
            "metadata": { "project_name": "p" },
            "nodes": { "model.p.m": {
                "unique_id": "model.p.m", "name": "m", "resource_type": "model",
                "compiled_code": "SELECT 1", "raw_code": "SELECT 1",
                "depends_on": { "nodes": [], "macros": [] },
                "config": { "materialized": "table", "contract": { "enforced": true } },
                "columns": columns,
                "tags": [], "schema": "s", "database": "d"
            }},
            "sources": {}
        });
        let dir = tempfile::TempDir::new().unwrap();
        let path = dir.path().join("manifest.json");
        std::fs::write(&path, manifest.to_string()).unwrap();
        crate::import::dbt_manifest::parse_manifest(&path)
            .unwrap()
            .nodes
            .remove("model.p.m")
            .unwrap()
    }

    #[test]
    fn float_and_timestamp_are_read_for_the_adapter() {
        let node = node_with(&serde_json::json!({
            "amount": { "name": "amount", "data_type": "float" },
            "at": { "name": "at", "data_type": "timestamp" },
            "n": { "name": "n", "data_type": "integer" },
            "ratio": { "name": "ratio", "data_type": "double" }
        }));
        let types = |adapter: Option<&str>| {
            let contract = contract_from_node(&node, adapter).unwrap();
            let parsed = parse(&contract.toml);
            let type_of = |n: &str| {
                parsed
                    .columns
                    .iter()
                    .find(|c| c.name == n)
                    .unwrap()
                    .type_name
                    .clone()
            };
            (
                type_of("amount"),
                type_of("at"),
                type_of("n"),
                type_of("ratio"),
                contract.untyped_columns,
            )
        };
        let s = |v: &str| Some(v.to_string());
        for adapter in ["bigquery", "postgres", "redshift"] {
            let (amount, at, _, ratio, _) = types(Some(adapter));
            assert_eq!(amount, s("Float64"), "{adapter} float is 64-bit");
            assert_eq!(at, s("Timestamp"), "{adapter}");
            assert_eq!(ratio, s("Float64"));
        }
        for adapter in ["duckdb", "databricks", "spark"] {
            let (amount, at, n, _, untyped) = types(Some(adapter));
            assert_eq!(amount, s("Float32"), "{adapter} float is 32-bit");
            assert_eq!(at, s("Timestamp"), "{adapter}");
            assert_eq!(n, s("Int32"));
            assert_eq!(untyped, 0);
        }
        // Snowflake: every float name lands as FLOAT, and integers land as
        // NUMBER, types Rocky reads differently from the name; a bare
        // timestamp is NTZ: all unchecked.
        let (amount, at, n, ratio, untyped) = types(Some("snowflake"));
        assert_eq!((amount, at, n, ratio), (None, None, None, None));
        assert_eq!(untyped, 4);
        for name in ["double", "DOUBLE PRECISION", "real", "float4", "float8"] {
            assert_eq!(contract_type_name(name, Some("snowflake")), None, "{name}");
        }
        // No adapter: the names that depend on it are unchecked.
        let (amount, at, n, ratio, untyped) = types(None);
        assert_eq!((amount, at), (None, None));
        assert_eq!(n, s("Int32"));
        assert_eq!(ratio, s("Float64"));
        assert_eq!(untyped, 2);
    }
}
