# generated by datamodel-codegen:
#   filename:  ai_contract.schema.json

from __future__ import annotations

from pydantic import BaseModel, conint


class AiContractColumnProfile(BaseModel):
    """
    Observed profile of one column, as reported by `rocky ai-contract`.
    """

    distinct: conint(ge=0)
    max: str | None = None
    min: str | None = None
    name: str
    null_rate: float
    nulls: conint(ge=0)
    observed_values: list[str]
    """
    Observed low-cardinality domain. Empty above the cardinality cap. This is reported as evidence; it is not encoded into the contract file.
    """
    rows: conint(ge=0)
    type: str
    """
    Inferred Rocky type name.
    """


class AiContractOutput(BaseModel):
    """
    JSON output for `rocky ai-contract <model>`.

    Reports the AI-drafted data contract for a model, grounded in the observed per-column profile of its target table. The drafted contract is compile-verified against the model before it's reported, so a successful response is a contract that `rocky compile` accepts.
    """

    attempts: conint(ge=0)
    """
    Number of LLM attempts taken to reach a compile-verified contract.
    """
    command: str
    contract_toml: str
    """
    The drafted contract serialized as `.contract.toml`.
    """
    model: str
    """
    The model the contract was drafted for.
    """
    profile: list[AiContractColumnProfile]
    """
    The observed per-column profile that grounded the draft.
    """
    saved_path: str | None = None
    """
    Path the contract was written to, when `--save` was passed.
    """
    version: str
