# generated by datamodel-codegen:
#   filename:  audit_scorecard.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, conint


class ScorecardDimension1(StrEnum):
    """
    Group by who acted (`agent` / `human`).
    """

    principal = "principal"


class ScorecardDimension2(StrEnum):
    """
    Group by the winning `[[policy.rules]]` index (or the default posture).
    """

    rule = "rule"


class ScorecardDimension3(StrEnum):
    """
    Group by the concrete model the decision was about.
    """

    scope = "scope"


class ScorecardGroup(BaseModel):
    """
    One group's decision aggregate in an [`AuditScorecardOutput`].

    Every rate is a ratio over [`Self::total`] and is independently recomputable from [`Self::decision_refs`], which lists the exact ledger keys (`timestamp|plan_id|model`) that composed the group — so the aggregate summarizes citable rows, never an unverifiable number.
    """

    acceptance_rate: float
    """
    `allow / total` — the proposal acceptance rate.
    """
    allow: conint(ge=0)
    """
    Decisions the plane allowed outright.
    """
    decision_refs: list[str]
    """
    The ledger keys that composed this group (`timestamp|plan_id|model`), newest first — the citations backing every count above.
    """
    denial_rate: float
    """
    `deny / total` — the denial rate.
    """
    deny: conint(ge=0)
    """
    Decisions the plane denied.
    """
    key: str
    """
    The group label: a principal (`agent` / `human`), a rule (`rule 3` / `default posture`), or a model/scope name — per the scorecard's `by`.
    """
    require_review: conint(ge=0)
    """
    Decisions the plane escalated to human review.
    """
    review_rate: float
    """
    `require_review / total` — the escalation rate.
    """
    total: conint(ge=0)
    """
    Decisions in this group within the window.
    """


class ScorecardVerifyAfter(BaseModel):
    """
    The verify-after aggregate inside an [`AuditScorecardOutput`]: pass/fail counts over the post-apply verification custody rows in the window.

    Each row's aggregate verdict is its recorded `effect` (`allow` = every named check passed, `deny` = a check failed or was absent and the apply halted), so the pass rate summarizes exactly what the ledger persists.
    """

    failed: conint(ge=0)
    """
    Rows whose verdict was `deny` (a named check failed or was absent).
    """
    pass_rate: float
    """
    `passed / total`.
    """
    passed: conint(ge=0)
    """
    Rows whose verdict was `allow` (every named check passed).
    """
    total: conint(ge=0)
    """
    Verification custody rows in the window.
    """


class SectionAvailability4(StrEnum):
    """
    The query ran and the section carries data for the window.
    """

    available = "available"


class SectionAvailability5(StrEnum):
    """
    The query ran cleanly but nothing fell inside the window.
    """

    no_data = "no_data"


class SectionAvailability6(StrEnum):
    """
    The underlying signal is not recorded in the state store, so the section cannot be composed. Accompanied by a `note` explaining why.
    """

    unavailable = "unavailable"


class ScorecardUnavailableMetric(BaseModel):
    """
    A metric the scorecard cannot compute from the persisted ledger for this window.

    Declared explicitly (not silently omitted) so the honesty is machine-readable: a consumer sees the metric name, that it is `unavailable`, and exactly why.
    """

    availability: SectionAvailability4 | SectionAvailability5 | SectionAvailability6
    """
    Always [`SectionAvailability::Unavailable`].
    """
    metric: str
    """
    The metric identifier (`reverts`, `escalation_latency`, or `verify_after_pass_rate` when no verification row falls in the window).
    """
    note: str
    """
    Why the metric cannot be derived from the persisted ledger.
    """


class AuditScorecardOutput(BaseModel):
    """
    JSON output for `rocky audit --scorecard` — a trust-calibration digest.

    A decisions-by-group aggregation over the persisted policy-decision ledger, windowed by `--window`. It is the evidence base for widening or tightening autonomy, and it informs human judgment only — nothing here is wired to any automatic policy change.

    Only metrics the ledger actually persists are computed. Post-apply verification outcomes *are* persisted (custody rows with a non-empty `verify_after` check list), so [`Self::verify_after`] reports their pass rate when any fall in the window. Reverts and escalation-resolution latency are not persisted; they are declared in [`Self::unavailable_metrics`] as `unavailable` with the reason, never faked into a number — and `verify_after_pass_rate` joins that list only when no verification row falls in the window. A ledger read failure renders the whole scorecard `unavailable` rather than a smoothed-over zero.
    """

    availability: SectionAvailability4 | SectionAvailability5 | SectionAvailability6
    """
    Whether the scorecard could be composed at all: `unavailable` when the ledger could not be read (fail-closed), `no_data` when no decision falls in the window, `available` otherwise.
    """
    by: ScorecardDimension1 | ScorecardDimension2 | ScorecardDimension3
    """
    The grouping dimension (`--by`).
    """
    command: str
    groups: list[ScorecardGroup]
    """
    One row per group, ranked by decision count descending.
    """
    note: str | None = None
    total_decisions: conint(ge=0)
    """
    Total decisions in the window, across all groups.
    """
    unavailable_metrics: list[ScorecardUnavailableMetric]
    """
    Metrics the persisted ledger cannot support for this window, declared plainly rather than computed. Each is `unavailable` with the reason it cannot be derived.
    """
    verify_after: ScorecardVerifyAfter | None = None
    """
    Aggregate of the post-apply verification custody rows in the window (rows with a non-empty `verify_after` check list). `null` when no verification row falls in the window — then `verify_after_pass_rate` is declared in [`Self::unavailable_metrics`] instead.
    """
    version: str
    window: str
    """
    The window as requested (`all`, `30d`, `24h`, …).
    """
    window_start: str | None = None
    """
    Lower bound of the window (RFC 3339), or `null` for all-time.
    """
