# generated by datamodel-codegen:
#   filename:  branch_delete.schema.json

from __future__ import annotations

from pydantic import BaseModel


class BranchDeleteOutput(BaseModel):
    """
    JSON output for `rocky branch delete`.
    """

    command: str
    name: str
    removed: bool
    """
    Whether a record was actually removed (false if the branch didn't exist).
    """
    version: str
