# generated by datamodel-codegen:
#   filename:  branch_promote.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, RootModel, conint


class ApproverSource(StrEnum):
    """
    Where the approval signature was produced.

    Reserved for future CI / OIDC paths. Today only the `Local` variant is emitted by the CLI.
    """

    local = "local"
    ci_oidc = "ci_oidc"
    pat = "pat"


class AuditEventKind1(StrEnum):
    """
    Categorical kind of an [`AuditEvent`] emitted by `branch promote`.
    """

    promote_started = "promote_started"
    promote_completed = "promote_completed"
    promote_failed = "promote_failed"


class AuditEventKind2(StrEnum):
    """
    Emitted when the approval gate was bypassed via `--skip-approval` or the `ROCKY_BRANCH_APPROVAL_SKIP` env-var override. The skip reason is recorded so a future audit can tell flag-skip apart from env-skip.
    """

    approval_skipped = "approval_skipped"


class AuditEventKind3(StrEnum):
    """
    Emitted when the semantic breaking-change gate blocked the promote. The findings list is carried on the parent [`AuditEvent`] so reviewers see exactly which structural changes triggered the block.
    """

    breaking_changes_blocked = "breaking_changes_blocked"


class AuditEventKind4(StrEnum):
    """
    Emitted when the semantic breaking-change gate detected one or more `Breaking`-severity findings but the operator overrode the block via `--allow-breaking`. Records the findings so the override leaves an audit trail equivalent to `ApprovalSkipped`.
    """

    breaking_changes_allowed = "breaking_changes_allowed"


class AuditEventKind5(StrEnum):
    """
    Emitted when the semantic breaking-change gate could not run — for example because the base ref failed to compile under the current Rocky version. Fail-open: the gate is skipped and the promote proceeds, but the reason is recorded so the bypass is auditable.
    """

    breaking_changes_gate_skipped = "breaking_changes_gate_skipped"


class AuditEventKind6(StrEnum):
    """
    Emitted by `rocky plan promote` when the plan has been successfully written to `.rocky/plans/<plan_id>.json`. Carries the plan_id so an audit consumer can correlate plan creation to a subsequent `rocky apply` event without scanning the filesystem.
    """

    promote_plan_created = "promote_plan_created"


class Kind(StrEnum):
    model_removed = "model_removed"


class BreakingChange1(BaseModel):
    """
    A model present on the base side is absent on the head side.
    """

    kind: Kind
    model: str


class Kind1(StrEnum):
    model_added = "model_added"


class BreakingChange2(BaseModel):
    """
    A model present on the head side is absent on the base side.
    """

    kind: Kind1
    model: str


class Kind2(StrEnum):
    column_dropped = "column_dropped"


class BreakingChange3(BaseModel):
    """
    A column present on the base side is absent on the head side.
    """

    column: str
    data_type: str
    kind: Kind2
    model: str


class Kind3(StrEnum):
    column_added = "column_added"


class BreakingChange4(BaseModel):
    """
    A column was added.
    """

    column: str
    data_type: str
    kind: Kind3
    model: str
    nullable: bool


class Kind4(StrEnum):
    column_type_changed = "column_type_changed"


class BreakingChange5(BaseModel):
    """
    A column's data type changed.
    """

    column: str
    kind: Kind4
    model: str
    narrowing: bool
    """
    `true` when the new type cannot represent every value of the old type (Int64 → Int32, Decimal precision shrink, Timestamp → Date).
    """
    new_type: str
    old_type: str


class Kind5(StrEnum):
    column_nullability_changed = "column_nullability_changed"


class BreakingChange6(BaseModel):
    """
    A column's nullability flipped.
    """

    column: str
    kind: Kind5
    model: str
    new_nullable: bool
    old_nullable: bool


class Kind6(StrEnum):
    column_reordered = "column_reordered"


class BreakingChange7(BaseModel):
    """
    A column's position in the output schema changed. `SELECT *` downstream consumers see different positional projection.
    """

    column: str
    kind: Kind6
    model: str
    new_index: conint(ge=0)
    old_index: conint(ge=0)


class Kind7(StrEnum):
    materialization_strategy_changed = "materialization_strategy_changed"


class BreakingChange8(BaseModel):
    """
    The materialization strategy switched between top-level variants (e.g. `FullRefresh` → `Incremental`).
    """

    kind: Kind7
    model: str
    new_strategy: str
    old_strategy: str


class Kind8(StrEnum):
    materialization_key_changed = "materialization_key_changed"


class BreakingChange9(BaseModel):
    """
    Materialization-specific key columns changed without the top-level variant changing (e.g. `Merge` `unique_key` rewritten, `Incremental` `timestamp_column` swapped).
    """

    key_kind: str
    """
    Which key changed: `unique_key`, `timestamp_column`, `partition_by`, `time_column`, `granularity`, `target_lag`, `update_columns`, `storage_prefix`, or `partition_columns`.
    """
    kind: Kind8
    model: str
    new: list[str]
    old: list[str]


class Kind9(StrEnum):
    replication_columns_changed = "replication_columns_changed"


class BreakingChange10(BaseModel):
    """
    Replication column-selection mode flipped between `All` and `Explicit(...)` or the explicit list changed.
    """

    kind: Kind9
    model: str
    new: list[str]
    old: list[str]


class Kind10(StrEnum):
    partition_by_changed = "partition_by_changed"


class BreakingChange11(BaseModel):
    """
    `LakehouseOptions::partition_by` changed without the strategy changing. Distinct from `MaterializationKeyChanged` since this lives on `format_options` rather than the strategy enum.
    """

    kind: Kind10
    model: str
    new: list[str]
    old: list[str]


class Kind11(StrEnum):
    target_renamed = "target_renamed"


class BreakingChange12(BaseModel):
    """
    Target table reference renamed (catalog, schema, or table component).
    """

    kind: Kind11
    model: str
    new: str
    old: str


class Kind12(StrEnum):
    source_changed = "source_changed"


class BreakingChange13(BaseModel):
    """
    Source reference rebound to a different table.
    """

    kind: Kind12
    model: str
    new: list[str]
    old: list[str]


class Kind13(StrEnum):
    column_mask_changed = "column_mask_changed"


class BreakingChange14(BaseModel):
    """
    A column mask was added, removed, or its strategy changed.
    """

    column: str
    kind: Kind13
    model: str
    new_strategy: str | None = None
    old_strategy: str | None = None


class Kind14(StrEnum):
    lakehouse_format_changed = "lakehouse_format_changed"


class BreakingChange15(BaseModel):
    """
    Lakehouse format switched (e.g. `DeltaTable` → `IcebergTable`).
    """

    kind: Kind14
    model: str
    new: str
    old: str


class Kind15(StrEnum):
    sql_body_changed = "sql_body_changed"


class BreakingChange16(BaseModel):
    """
    SQL body changed without any other detectable structural change. Surfaced as `Info` because the typed-output shape is unchanged, but runtime row contents may differ.
    """

    kind: Kind15
    model: str


class BreakingSeverity1(StrEnum):
    """
    Will break a downstream consumer that reads the model's prior shape.
    """

    breaking = "breaking"


class BreakingSeverity2(StrEnum):
    """
    May break consumers depending on usage; e.g. nullable → NOT NULL, column reordered.
    """

    warning = "warning"


class BreakingSeverity3(StrEnum):
    """
    Informational only — purely additive or backwards-compatible.
    """

    info = "info"


class PromoteTarget(BaseModel):
    """
    One per-target promote step in [`BranchPromoteOutput::targets`].
    """

    error: str | None = None
    """
    Adapter / SQL error text when `succeeded` is `false`.
    """
    source: str
    """
    Fully-qualified branch source the promote read from (catalog.branch_schema.table).
    """
    statement: str
    """
    SQL statement dispatched to the adapter for this target.
    """
    succeeded: bool
    """
    Whether the per-target SQL succeeded. Failures abort the run; on a failure this is `false` for the failing target and absent for any targets that never started.
    """
    target: str
    """
    Fully-qualified production target (catalog.schema.table).
    """


class RejectedApproval(BaseModel):
    """
    An approval artifact that was loaded from disk but rejected.
    """

    approval_id: str
    detail: str
    reason: str
    """
    One of: `bad_signature`, `state_hash_mismatch`, `expired`, `signer_not_allowed`, `parse_error`.
    """


class SignatureAlgorithm2(StrEnum):
    """
    blake3 over a canonical-JSON encoding of the artifact payload, with the approver's git identity bound into the hashed bytes. Detects tamper-after-write but is not asymmetric crypto — see the approval-flow docs for the security model.
    """

    blake3_canonical_json = "blake3_canonical_json"


class SignatureAlgorithm(RootModel[SignatureAlgorithm2]):
    root: SignatureAlgorithm2
    """
    Algorithm tag for an [`ApprovalSignature`].

    The discriminator is on disk from day one so future "real" cryptographic signing variants slot in without migrating existing artifacts.
    """


class ApprovalSignature(BaseModel):
    """
    Signature attached to an [`ApprovalArtifact`].
    """

    algorithm: SignatureAlgorithm
    digest: str
    """
    Hex-encoded digest. For `Blake3CanonicalJson`, this is the 32-byte blake3 hash printed as 64 lowercase hex characters.
    """


class ApproverIdentity(BaseModel):
    """
    Identity of an approver, captured at sign time.

    Email is sourced from `git config user.email`; name from `git config user.name`. Hostname is best-effort from the `hostname` crate and surfaced as an audit aid only — it is not part of the trust boundary. Set `ROCKY_SCRUB_HOST` in the environment to replace the hostname with `"redacted"` when recording public demos.
    """

    email: str
    host: str
    name: str | None = None
    source: ApproverSource


class BreakingFinding(BaseModel):
    """
    A classified finding produced by [`diff_project_ir`].
    """

    change: (
        BreakingChange1
        | BreakingChange2
        | BreakingChange3
        | BreakingChange4
        | BreakingChange5
        | BreakingChange6
        | BreakingChange7
        | BreakingChange8
        | BreakingChange9
        | BreakingChange10
        | BreakingChange11
        | BreakingChange12
        | BreakingChange13
        | BreakingChange14
        | BreakingChange15
        | BreakingChange16
    )
    """
    A single typed semantic change between two `ProjectIr` snapshots.

    Each variant carries the minimum identifying context (model + column + before/after values) needed for a CLI / PR-preview surface to render a useful message without re-loading either IR.
    """
    severity: BreakingSeverity1 | BreakingSeverity2 | BreakingSeverity3
    """
    Severity classification for a single semantic change.
    """


class ApprovalArtifact(BaseModel):
    """
    On-disk approval record for a single approver against a single branch.

    One file per approver under `./.rocky/approvals/<branch>/<approval_id>.json`. `branch_state_hash` binds the approval to the branch's content-addressed state at sign time; if the branch's hash changes (config bytes change), every existing artifact for that branch becomes stale and `branch promote` will refuse to honour it.
    """

    approval_id: str
    """
    Sortable monotonic identifier — timestamp prefix + random tail.
    """
    approver: ApproverIdentity
    branch: str
    branch_state_hash: str
    message: str | None = None
    signature: ApprovalSignature
    signed_at: AwareDatetime


class AuditEvent(BaseModel):
    """
    Single audit-trail event emitted during `branch promote`.

    Routed to stdout JSON only in v1; persistent audit storage is a follow-up.
    """

    actor: ApproverIdentity
    at: AwareDatetime
    branch: str
    branch_state_hash: str
    breaking_changes: list[BreakingFinding] | None = None
    """
    Breaking-change findings carried by `BreakingChangesBlocked` and `BreakingChangesAllowed` events. Always absent for other kinds.
    """
    kind: (
        AuditEventKind1
        | AuditEventKind2
        | AuditEventKind3
        | AuditEventKind4
        | AuditEventKind5
        | AuditEventKind6
    )
    """
    Categorical kind of an [`AuditEvent`] emitted by `branch promote`.
    """
    reason: str | None = None
    """
    Free-form context. Populated for `ApprovalSkipped` to record the origin of the skip, and for `BreakingChangesGateSkipped` to record why the gate could not run (e.g. "base ref did not compile"). Empty for routine state events.
    """


class BranchPromoteOutput(BaseModel):
    """
    JSON output for `rocky branch promote`.
    """

    approvals_rejected: list[RejectedApproval]
    """
    Approval artifacts loaded from disk that failed verification, with the reason for rejection. Surfaced even on a successful promote so operators can spot stale artifacts to clean up.
    """
    approvals_used: list[ApprovalArtifact]
    """
    Approval artifacts that satisfied the gate at promote time. Empty when the gate was disabled (`required = false`) or skipped.
    """
    audit: list[AuditEvent]
    """
    Audit-trail events emitted during this invocation, in order. At minimum: `PromoteStarted` plus one of `PromoteCompleted` / `PromoteFailed`. `ApprovalSkipped` precedes `PromoteStarted` when the gate was bypassed.
    """
    branch: str
    branch_state_hash: str
    breaking_changes: list[BreakingFinding] | None = None
    """
    Semantic breaking-change findings produced by the pre-promote gate. Empty when the gate ran and found no breaking changes; absent when the gate was skipped (compile failure on either side). When present and non-empty either the promote was blocked or `--allow-breaking` was set — see the audit trail for which.
    """
    command: str
    success: bool
    """
    True when every target's SQL succeeded.
    """
    targets: list[PromoteTarget]
    """
    One entry per managed target the promote attempted, in dispatch order.
    """
    version: str
