# generated by datamodel-codegen:
#   filename:  brief.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, conint


class BriefBudgetStatus(BaseModel):
    """
    Budget-burn status against the configured per-run ceiling.
    """

    max_usd_per_run: float
    """
    The configured `[budget] max_usd` per-run ceiling.
    """
    runs_over_budget: conint(ge=0)
    """
    How many runs in the window exceeded the ceiling.
    """
    worst_run_cost_usd: float | None = None
    worst_run_id: str | None = None
    """
    The priciest run in the window (its citation), when a cost was computed.
    """


class BriefDegradedRule(BaseModel):
    """
    A budget-exhausted (degraded) rule inside [`BriefAutonomySection`].
    """

    failures: conint(ge=0)
    """
    Verify-after failures counted in the window.
    """
    limit: conint(ge=0)
    """
    The rule's configured failure ceiling.
    """
    rule_id: conint(ge=0)
    """
    Index of the degraded `[[policy.rules]]` entry.
    """
    window: str
    """
    The rule's configured window (`7d`, `24h`, …).
    """


class BriefDriftEntry(BaseModel):
    """
    A single schema-drift observation inside [`BriefDriftSection`].
    """

    change: str
    """
    Human-readable description of the change.
    """
    graph_hash: str
    """
    The DAG graph hash the change was observed against — the citation for this drift snapshot.
    """
    timestamp: str


class BriefFailedModel(BaseModel):
    """
    A non-successful model execution inside a [`BriefRunEntry`].
    """

    model_name: str
    status: str


class BriefFreshnessEntry(BaseModel):
    """
    A single model's freshness reading inside [`BriefFreshnessSection`].
    """

    freshness_lag_seconds: conint(ge=0)
    model_name: str
    observed_at: str
    run_id: str


class BriefQualityEntry(BaseModel):
    """
    A single model's quality reading inside [`BriefQualitySection`].
    """

    max_null_rate: float | None = None
    """
    The highest per-column null rate observed for the model, if any columns were profiled.
    """
    model_name: str
    observed_at: str
    row_count: conint(ge=0)
    run_id: str


class BriefRunCost(BaseModel):
    """
    Per-run cost inside [`BriefCostSection`].
    """

    bytes_scanned: conint(ge=0) | None = None
    cost_usd: float | None = None
    duration_ms: conint(ge=0)
    run_id: str


class BriefRunEntry(BaseModel):
    """
    A single run needing attention inside [`BriefRunsSection`].
    """

    failed_models: list[BriefFailedModel]
    """
    Models within the run that did not report `success`.
    """
    finished_at: str
    run_id: str
    """
    The run's identifier — the citation to drill in via `rocky replay`.
    """
    started_at: str
    status: str
    trigger: str


class BriefSinceMode1(StrEnum):
    """
    Everything recorded since the previous `--since last` digest (the stored cursor). Advances the cursor on success.
    """

    last = "last"


class BriefSinceMode2(StrEnum):
    """
    A rolling 24-hour window ending now. Does not touch the cursor.
    """

    field_24h = "24h"


class BriefSinceMode3(StrEnum):
    """
    A rolling 7-day window ending now. Does not touch the cursor.
    """

    field_7d = "7d"


class PolicyCapability23(StrEnum):
    """
    Read model output / metadata. Always allowed.
    """

    read = "read"


class PolicyCapability24(StrEnum):
    """
    Draft a plan for later review.
    """

    propose = "propose"


class PolicyCapability25(StrEnum):
    """
    Apply a plan against the warehouse.
    """

    apply = "apply"


class PolicyCapability26(StrEnum):
    """
    Promote a branch / environment.
    """

    promote = "promote"


class PolicyCapability27(StrEnum):
    """
    Backfill historical partitions.
    """

    backfill = "backfill"


class PolicyCapability28(StrEnum):
    """
    Garbage-collect / reclaim storage.
    """

    gc = "gc"


class PolicyCapability29(StrEnum):
    """
    Retry a failed run.
    """

    retry = "retry"


class PolicyCapability30(StrEnum):
    """
    Quarantine a partition / model.
    """

    quarantine = "quarantine"


class PolicyCapability31(StrEnum):
    """
    An additive schema change (refinement of apply/promote).
    """

    schema_change_additive = "schema_change.additive"


class PolicyCapability32(StrEnum):
    """
    A breaking schema change (refinement of apply/promote).
    """

    schema_change_breaking = "schema_change.breaking"


class PolicyCapability33(StrEnum):
    """
    A value-only data change (refinement of apply/promote).
    """

    value_change = "value_change"


class PolicyEffect7(StrEnum):
    """
    Permit the action outright.
    """

    allow = "allow"


class PolicyEffect8(StrEnum):
    """
    Permit only after human review. The safe default posture.
    """

    require_review = "require_review"


class PolicyEffect9(StrEnum):
    """
    Refuse the action. A hard override — no `allow` overturns it.
    """

    deny = "deny"


class PolicyPrincipal5(StrEnum):
    """
    A person.
    """

    human = "human"


class PolicyPrincipal6(StrEnum):
    """
    A non-human caller (AI agent / automation).
    """

    agent = "agent"


class SectionAvailability7(StrEnum):
    """
    The query ran and the section carries data for the window.
    """

    available = "available"


class SectionAvailability8(StrEnum):
    """
    The query ran cleanly but nothing fell inside the window.
    """

    no_data = "no_data"


class SectionAvailability9(StrEnum):
    """
    The underlying signal is not recorded in the state store, so the section cannot be composed. Accompanied by a `note` explaining why.
    """

    unavailable = "unavailable"


class BriefActiveFreeze(BaseModel):
    """
    An active policy freeze inside [`BriefAutonomySection`].
    """

    frozen_at: str
    """
    RFC 3339 wall clock when the freeze was recorded — the citation.
    """
    plan_id: str
    """
    The freeze decision's `plan_id`.
    """
    principal: PolicyPrincipal5 | PolicyPrincipal6
    """
    Who is attempting an action.

    `agent` is a non-human caller (an AI harness authoring, applying, or remediating). `human` is a person. In v0 the principal is supplied explicitly (`rocky policy check --principal …`); auto-detection is a later phase.
    """
    scope: str
    """
    The scope selector the freeze targets.
    """


class BriefAutonomySection(BaseModel):
    """
    Autonomy section — rules whose autonomy budget is currently exhausted (degraded to `require_review`) and policy freezes in force.

    This is a *current-state* projection over the whole decision ledger — each budget uses its own configured window, independent of the digest's `--since`. It fails closed: `unavailable` when the ledger or config can't be read, `no_data` when nothing is degraded or frozen.
    """

    active_freezes: list[BriefActiveFreeze]
    """
    Policy freezes currently in force.
    """
    availability: SectionAvailability7 | SectionAvailability8 | SectionAvailability9
    """
    Whether a brief section's underlying query succeeded and had data.

    The digest is composed section-by-section from independent typed queries over the state store and the decision ledger. Each section fails closed: a query that returns nothing renders as [`SectionAvailability::NoData`], and a source that is not wired into the state store at all renders as [`SectionAvailability::Unavailable`] with a note — never as a smoothed-over "all clear". A brief that claims more than the ledger holds poisons the whole surface, so the marker is machine-readable, not prose.
    """
    degraded_rules: list[BriefDegradedRule]
    """
    Rules whose budget is exhausted right now — each auto-degraded to `require_review` until its failures age out of the window.
    """
    note: str | None = None


class BriefCostSection(BaseModel):
    """
    Cost section — per-run cost re-derived over the window, plus budget burn.
    """

    adapter_type: str | None = None
    """
    The billed-warehouse adapter cost was computed against, if resolvable from `rocky.toml`.
    """
    availability: SectionAvailability7 | SectionAvailability8 | SectionAvailability9
    """
    Whether a brief section's underlying query succeeded and had data.

    The digest is composed section-by-section from independent typed queries over the state store and the decision ledger. Each section fails closed: a query that returns nothing renders as [`SectionAvailability::NoData`], and a source that is not wired into the state store at all renders as [`SectionAvailability::Unavailable`] with a note — never as a smoothed-over "all clear". A brief that claims more than the ledger holds poisons the whole surface, so the marker is machine-readable, not prose.
    """
    budget: BriefBudgetStatus | None = None
    """
    Budget-burn status against the configured per-run `[budget] max_usd`, when one is set.
    """
    note: str | None = None
    per_run: list[BriefRunCost]
    """
    Per-run cost in the window, priciest first. Each cites its `run_id`.
    """
    run_count: conint(ge=0)
    total_bytes_scanned: conint(ge=0) | None = None
    total_cost_usd: float | None = None
    """
    Summed observed cost across the window. `null` when no run produced enough data to compute a cost (e.g. DuckDB, which has no billing).
    """
    total_duration_ms: conint(ge=0)


class BriefDecisionEntry(BaseModel):
    """
    One recorded policy decision, cited for the digest.

    `decision_ref` is the composite ledger key (`"{timestamp}|{plan_id}|{model}"`) — the stable identity a governor drills into via `rocky audit`. `plan_id` and `rule_id` are the other two citations: which plan the decision governed and which `[[policy.rules]]` entry won.
    """

    capability: (
        PolicyCapability23
        | PolicyCapability24
        | PolicyCapability25
        | PolicyCapability26
        | PolicyCapability27
        | PolicyCapability28
        | PolicyCapability29
        | PolicyCapability30
        | PolicyCapability31
        | PolicyCapability32
        | PolicyCapability33
    )
    """
    The class of action a policy rule governs.

    `read` is always allowed (short-circuit). The mutating verbs (`propose` … `quarantine`) name coarse operations; `schema_change.additive`, `schema_change.breaking`, and `value_change` are *refinements* of the apply/promote verbs — a rule naming a bare verb (`apply`/`promote`) matches those refinements too, but a rule naming a refinement matches only that exact refinement.
    """
    decision_ref: str
    """
    Composite ledger key that uniquely identifies this decision.
    """
    effect: PolicyEffect7 | PolicyEffect8 | PolicyEffect9
    """
    The verdict a policy rule (or the default posture) yields.

    Ordered by restrictiveness for incomparable-rule tie-breaking: `Deny` is a hard override (handled separately), and among non-deny verdicts `RequireReview` is more restrictive than `Allow`.
    """
    model: str
    """
    The model the decision was about.
    """
    plan_id: str
    """
    The plan the decision governed.
    """
    principal: PolicyPrincipal5 | PolicyPrincipal6
    """
    Who is attempting an action.

    `agent` is a non-human caller (an AI harness authoring, applying, or remediating). `human` is a person. In v0 the principal is supplied explicitly (`rocky policy check --principal …`); auto-detection is a later phase.
    """
    reason: str
    """
    Human-readable explanation of how the effect was reached.
    """
    rule_id: conint(ge=0) | None = None
    """
    Index of the winning `[[policy.rules]]` entry, or `null` for the default posture.
    """
    timestamp: str
    """
    RFC 3339 timestamp when the decision was recorded.
    """


class BriefDriftSection(BaseModel):
    """
    Drift section — schema drift recorded in the state store.
    """

    availability: SectionAvailability7 | SectionAvailability8 | SectionAvailability9
    """
    Whether a brief section's underlying query succeeded and had data.

    The digest is composed section-by-section from independent typed queries over the state store and the decision ledger. Each section fails closed: a query that returns nothing renders as [`SectionAvailability::NoData`], and a source that is not wired into the state store at all renders as [`SectionAvailability::Unavailable`] with a note — never as a smoothed-over "all clear". A brief that claims more than the ledger holds poisons the whole surface, so the marker is machine-readable, not prose.
    """
    events: list[BriefDriftEntry]
    """
    Drift events in the window, newest first.
    """
    note: str | None = None


class BriefEscalationsSection(BaseModel):
    """
    Escalations section — `require_review` decisions still awaiting a human.
    """

    availability: SectionAvailability7 | SectionAvailability8 | SectionAvailability9
    """
    Whether a brief section's underlying query succeeded and had data.

    The digest is composed section-by-section from independent typed queries over the state store and the decision ledger. Each section fails closed: a query that returns nothing renders as [`SectionAvailability::NoData`], and a source that is not wired into the state store at all renders as [`SectionAvailability::Unavailable`] with a note — never as a smoothed-over "all clear". A brief that claims more than the ledger holds poisons the whole surface, so the marker is machine-readable, not prose.
    """
    note: str | None = None
    pending: list[BriefDecisionEntry]
    """
    The pending decisions, ranked, each fully cited.
    """
    ranking: str
    """
    How the queue is ordered. `"recency"` in v0; blast-radius ranking (CLL × classification × staleness) is a later phase.
    """
    total: conint(ge=0)


class BriefFreshnessSection(BaseModel):
    """
    Freshness / SLO section, derived from recorded quality snapshots.
    """

    availability: SectionAvailability7 | SectionAvailability8 | SectionAvailability9
    """
    Whether a brief section's underlying query succeeded and had data.

    The digest is composed section-by-section from independent typed queries over the state store and the decision ledger. Each section fails closed: a query that returns nothing renders as [`SectionAvailability::NoData`], and a source that is not wired into the state store at all renders as [`SectionAvailability::Unavailable`] with a note — never as a smoothed-over "all clear". A brief that claims more than the ledger holds poisons the whole surface, so the marker is machine-readable, not prose.
    """
    models: list[BriefFreshnessEntry]
    """
    Per-model freshness lag, worst first. Each cites its `run_id`.
    """
    note: str | None = None


class BriefPrincipalActivity(BaseModel):
    """
    Per-principal decision counts inside [`BriefAgentActivitySection`].
    """

    allow: conint(ge=0)
    deny: conint(ge=0)
    principal: PolicyPrincipal5 | PolicyPrincipal6
    """
    Who is attempting an action.

    `agent` is a non-human caller (an AI harness authoring, applying, or remediating). `human` is a person. In v0 the principal is supplied explicitly (`rocky policy check --principal …`); auto-detection is a later phase.
    """
    require_review: conint(ge=0)
    total: conint(ge=0)


class BriefQualitySection(BaseModel):
    """
    Quality / check section, derived from recorded quality snapshots.
    """

    availability: SectionAvailability7 | SectionAvailability8 | SectionAvailability9
    """
    Whether a brief section's underlying query succeeded and had data.

    The digest is composed section-by-section from independent typed queries over the state store and the decision ledger. Each section fails closed: a query that returns nothing renders as [`SectionAvailability::NoData`], and a source that is not wired into the state store at all renders as [`SectionAvailability::Unavailable`] with a note — never as a smoothed-over "all clear". A brief that claims more than the ledger holds poisons the whole surface, so the marker is machine-readable, not prose.
    """
    models: list[BriefQualityEntry]
    """
    Per-model quality readings, newest first. Each cites its `run_id`.
    """
    note: str | None = None


class BriefRunsSection(BaseModel):
    """
    Runs section — the run ledger rolled up by status.
    """

    attention: list[BriefRunEntry]
    """
    Runs that did not fully succeed, newest first — the exception view. Each cites its `run_id`.
    """
    availability: SectionAvailability7 | SectionAvailability8 | SectionAvailability9
    """
    Whether a brief section's underlying query succeeded and had data.

    The digest is composed section-by-section from independent typed queries over the state store and the decision ledger. Each section fails closed: a query that returns nothing renders as [`SectionAvailability::NoData`], and a source that is not wired into the state store at all renders as [`SectionAvailability::Unavailable`] with a note — never as a smoothed-over "all clear". A brief that claims more than the ledger holds poisons the whole surface, so the marker is machine-readable, not prose.
    """
    failed: conint(ge=0)
    note: str | None = None
    partial_failure: conint(ge=0)
    succeeded: conint(ge=0)
    total: conint(ge=0)


class BriefAgentActivitySection(BaseModel):
    """
    Agent-activity section — the policy-decision ledger rolled up by principal.
    """

    allow: conint(ge=0)
    availability: SectionAvailability7 | SectionAvailability8 | SectionAvailability9
    """
    Whether a brief section's underlying query succeeded and had data.

    The digest is composed section-by-section from independent typed queries over the state store and the decision ledger. Each section fails closed: a query that returns nothing renders as [`SectionAvailability::NoData`], and a source that is not wired into the state store at all renders as [`SectionAvailability::Unavailable`] with a note — never as a smoothed-over "all clear". A brief that claims more than the ledger holds poisons the whole surface, so the marker is machine-readable, not prose.
    """
    by_principal: list[BriefPrincipalActivity]
    """
    One roll-up per acting principal (`human` / `agent`).
    """
    decisions: list[BriefDecisionEntry]
    """
    Every decision in the window, newest first, each fully cited.
    """
    deny: conint(ge=0)
    note: str | None = None
    require_review: conint(ge=0)
    total: conint(ge=0)


class BriefOutput(BaseModel):
    """
    JSON output for `rocky brief` — the governor's estate digest.

    A typed projection of the state store and the policy-decision ledger over a time window: agent activity by principal, runs, drift, freshness, quality, cost, and the ranked queue of decisions still awaiting a human. It is composed template-first from typed queries — there is no narration layer — and every line item carries a ledger citation (`run_id`, `plan_id`, or the composite `decision_ref`) so a claim can be independently checked against `rocky audit` / `rocky replay`.
    """

    agent_activity: BriefAgentActivitySection
    """
    Agent- and human-authored policy decisions in the window, grouped by principal and effect.
    """
    autonomy: BriefAutonomySection
    """
    Autonomy-budget degradations and active policy freezes — the dynamic tightening currently in force across the estate.
    """
    command: str
    cost: BriefCostSection
    """
    Cost and budget burn across the window's runs.
    """
    drift: BriefDriftSection
    """
    Schema drift observed in the window.
    """
    escalations: BriefEscalationsSection
    """
    Decisions that resolved to `require_review` and still need a human, ranked.
    """
    freshness: BriefFreshnessSection
    """
    Freshness / SLO status in the window.
    """
    generated_at: str
    """
    RFC 3339 wall clock when the digest was generated (the window's upper bound).
    """
    quality: BriefQualitySection
    """
    Data-quality status in the window.
    """
    runs: BriefRunsSection
    """
    Pipeline runs in the window, with the ones needing attention listed.
    """
    since_mode: BriefSinceMode1 | BriefSinceMode2 | BriefSinceMode3
    """
    How the window was resolved.
    """
    since_timestamp: str | None = None
    """
    RFC 3339 lower bound of the window. `null` only for a first-ever `--since last` with no stored cursor — the digest then spans all of recorded history.
    """
    version: str
