# generated by datamodel-codegen:
#   filename:  compact.schema.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, conint


class CompactTotals(BaseModel):
    """
    Aggregate counts over a `rocky compact --catalog` invocation.
    """

    statement_count: conint(ge=0)
    table_count: conint(ge=0)


class NamedStatement(BaseModel):
    """
    Named SQL statement (purpose + sql), reused by compact and archive.

    `sql` is optional in preparation for the v2 persisted plan format (Cluster 3 C — "SQL as `.o` files"). Today's emission path always populates `Some(string)` for both stdout JSON and the persisted plan; the v2 format will write `None` and rely on the apply path to regenerate SQL from the plan's typed IR.
    """

    purpose: str
    sql: str | None = None


class CompactOutput(BaseModel):
    """
    JSON output for `rocky compact`.

    Two shapes share this struct:

    - **Single-model (`rocky compact <fqn>`)**: `model` is set; `scope`, `catalog`, `tables`, and `totals` are absent. Byte-stable with envelopes that predate the catalog-scope flag. - **Catalog scope (`rocky compact --catalog <name>`)**: `model` is absent, `scope = "catalog"`, `catalog` is set, `tables` keys per-FQN statement bundles, and `totals` carries aggregate counts. The flat `statements` field still carries every SQL statement across all tables for consumers that just iterate it.
    """

    catalog: str | None = None
    """
    Set when invoked as `rocky compact --catalog <name>`. Stores the catalog identifier as resolved (lowercased to match the managed-table resolver's normalization).
    """
    command: str
    dry_run: bool
    model: str | None = None
    """
    Set when invoked as `rocky compact <fqn>`.
    """
    plan_id: str | None = None
    """
    Plan identifier (full 64-char blake3 hex). Populated when the plan is persisted to `.rocky/plans/` so it can be applied later via `rocky compact apply <plan_id>`. Absent when plan persistence is skipped (e.g. `--measure-dedup` path).
    """
    scope: str | None = None
    """
    `"catalog"` for the catalog-scoped path; absent for single-model invocations to keep their envelope byte-stable.
    """
    statements: list[NamedStatement]
    """
    Flat list of every SQL statement across every table. Single-model invocations have one bundle here; `--catalog` invocations have the concatenation of every per-table bundle (in the same order as `tables`'s key iteration order).
    """
    tables: dict[str, Any] | None = None
    """
    Per-table breakdown, keyed by fully-qualified table name. Present only on `--catalog` invocations.
    """
    target_size_mb: conint(ge=0)
    totals: CompactTotals | None = None
    """
    Aggregate counts across the catalog. Present only on `--catalog` invocations.
    """
    version: str


class CompactTableEntry(BaseModel):
    """
    Per-table compaction plan inside a `--catalog` envelope.
    """

    statements: list[NamedStatement]
