# generated by datamodel-codegen:
#   filename:  dag_status.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, conint


class DagNodeStatusOutput1(StrEnum):
    """
    Node has not started yet.
    """

    pending = "pending"


class DagNodeStatusOutput2(StrEnum):
    """
    Node is currently executing.
    """

    running = "running"


class DagNodeStatusOutput3(StrEnum):
    """
    Node completed successfully.
    """

    completed = "completed"


class DagNodeStatusOutput4(StrEnum):
    """
    Node failed; `error` is attached.
    """

    failed = "failed"


class DagNodeStatusOutput5(StrEnum):
    """
    Node was skipped because an ancestor failed.
    """

    skipped = "skipped"


class DagNodeResultOutput(BaseModel):
    """
    One node's record inside [`DagExecutionOutput`].
    """

    duration_ms: conint(ge=0)
    """
    Node duration, in milliseconds.
    """
    error: str | None = None
    """
    Error message when the node failed; omitted otherwise.
    """
    id: str
    """
    Node id.
    """
    kind: str
    """
    Node kind, e.g. `model` or `test`.
    """
    label: str
    """
    Human label.
    """
    layer: conint(ge=0)
    """
    The execution layer the node ran in.
    """
    status: (
        DagNodeStatusOutput1
        | DagNodeStatusOutput2
        | DagNodeStatusOutput3
        | DagNodeStatusOutput4
        | DagNodeStatusOutput5
    )
    """
    Final status of the node.
    """


class DagExecutionOutput(BaseModel):
    """
    Aggregate result of one DAG execution.
    """

    completed: conint(ge=0)
    """
    Nodes that completed.
    """
    duration_ms: conint(ge=0)
    """
    Wall-clock duration of the whole execution, in milliseconds.
    """
    failed: conint(ge=0)
    """
    Nodes that failed.
    """
    nodes: list[DagNodeResultOutput]
    """
    One record per node the executor visited.
    """
    skipped: conint(ge=0)
    """
    Nodes skipped because an ancestor failed.
    """
    total_layers: conint(ge=0)
    """
    Number of execution layers.
    """
    total_nodes: conint(ge=0)
    """
    Number of nodes in the DAG.
    """


class DagStatusOutput(BaseModel):
    """
    The latest recorded DAG execution for `GET /api/v1/dag/status`.

    Populated by the in-process executor only; there is no CLI counterpart. The route answers `503 engine_not_ready` until one execution has been recorded. Bounded by the node count of that execution.
    """

    completed_at: AwareDatetime
    """
    When the execution finished (UTC).
    """
    result: DagExecutionOutput
    """
    The aggregate execution result.
    """
