# generated by datamodel-codegen:
#   filename:  dag_layers.schema.json

from __future__ import annotations

from pydantic import BaseModel, conint


class DagLayersOutput(BaseModel):
    """
    The execution layers for `GET /api/v1/dag/layers`.

    Bounded by the project's model count: every model appears in exactly one layer.
    """

    layers: list[list[str]]
    """
    Topologically sorted layers. Models in one layer have no mutual dependencies and can run in parallel.
    """
    total_models: conint(ge=0)
    """
    Number of models across all layers.
    """
