# generated by datamodel-codegen:
#   filename:  dag_run.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, conint


class DagRunNodeOutput(BaseModel):
    """
    Per-node record in a [`DagRunOutput`].
    """

    duration_ms: conint(ge=0)
    """
    Wall-clock duration of this node's execution.
    """
    error: str | None = None
    """
    Failure reason. Present iff `status = "failed"` (or `"skipped"` due to upstream failure).
    """
    id: str
    """
    Node identifier (e.g. `transformation:stg_orders`).
    """
    kind: str
    """
    Node kind: `source`, `replication`, `transformation`, `quality`, `snapshot`, `load`, `seed`, `test`.
    """
    label: str
    """
    Human-readable label (usually the pipeline or model name).
    """
    layer: conint(ge=0)
    """
    Layer index (0-based): the node's ordering position in the DAG. Same-layer nodes are dispatched together, but nodes that share a state file execute one at a time — so a shared layer bounds ordering, not wall-clock overlap. Seed nodes and nodes writing distinct state files do run concurrently.
    """
    status: str
    """
    Status: `pending`, `running`, `completed`, `failed`, `skipped`.
    """


class Severity(StrEnum):
    """
    Severity level of a diagnostic.

    Serialized in PascalCase (`"Error"`, `"Warning"`, `"Info"`) to stay compatible with existing dagster fixtures and the hand-written `Severity` StrEnum in `integrations/dagster/src/dagster_rocky/types.py`.
    """

    Error = "Error"
    Warning = "Warning"
    Info = "Info"


class SourceSpan(BaseModel):
    """
    Location in a source file.
    """

    col: conint(ge=0)
    file: str
    line: conint(ge=0)


class Diagnostic(BaseModel):
    """
    A compiler diagnostic (error, warning, or informational message).

    `code` and `message` use `Arc<str>` (§P3.5) — cloning a `Diagnostic` in the LSP publish loop becomes a refcount bump. Construction still accepts any `Into<String>` / `&str` via the helper constructors below; the arc wrap happens once at construction time.
    """

    code: str
    """
    Diagnostic code (e.g., "E001", "W001").
    """
    message: str
    """
    Human-readable message.
    """
    model: str
    """
    Which model this diagnostic relates to.
    """
    severity: Severity
    """
    Severity level.
    """
    span: SourceSpan | None = None
    """
    Source location (if available).
    """
    suggestion: str | None = None
    """
    Suggested fix (if any).
    """


class DagRunOutput(BaseModel):
    """
    Output of `rocky run --dag`: per-node execution results plus aggregate counts.
    """

    command: str
    completed: conint(ge=0)
    """
    Nodes that completed successfully.
    """
    consumer_diagnostics: list[Diagnostic] | None = None
    """
    Problems in the project's `consumers/` records (`E060`). Reported once for the whole graph; they never fail a node. Empty (and omitted) when the records are sound.
    """
    duration_ms: conint(ge=0)
    """
    Wall-clock duration of the entire DAG execution.
    """
    failed: conint(ge=0)
    """
    Nodes whose dispatcher returned an error.
    """
    nodes: list[DagRunNodeOutput]
    """
    Per-node execution records, sorted by (layer, id).
    """
    skipped: conint(ge=0)
    """
    Nodes skipped because an upstream failed (or because the dispatcher declined to handle them, e.g. Test nodes).
    """
    total_layers: conint(ge=0)
    """
    Number of execution layers (Kahn topological depth).
    """
    total_nodes: conint(ge=0)
    """
    Total nodes across all layers.
    """
    version: str
    warnings: list[str] | None = None
    """
    Scheduling warnings from dependency inference — physical-read derivation (mutual reads serialized deterministically, unparseable models, colliding targets) and label inference (label collisions where only one claimant orders the reader, unparseable models). Empty when none.
    """
