# generated by datamodel-codegen:
#   filename:  docs.schema.json

from __future__ import annotations

from pydantic import BaseModel, conint


class DocsOutput(BaseModel):
    """
    Output for `rocky docs --output json`.
    """

    command: str
    duration_ms: conint(ge=0)
    models_count: conint(ge=0)
    output_path: str
    pipelines_count: conint(ge=0)
    version: str
