# generated by datamodel-codegen:
#   filename:  freshness.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, Field, conint


class FreshnessStatus(StrEnum):
    """
    Outcome of one freshness check. Serialized `pass` / `warn` / `error` / `runtime_error`, matching dbt's `source freshness` statuses.

    - `pass`: within every threshold. - `warn`: older than `warn_after`, not older than `error_after`. - `error`: older than `error_after`. - `runtime_error`: the check could not be evaluated (invalid config, a failed query, or a value that does not read as a timestamp).
    """

    pass_ = "pass"
    warn = "warn"
    error = "error"
    runtime_error = "runtime_error"


class FreshnessSummary(BaseModel):
    """
    Counts per status across `sources` and `models`.
    """

    error: conint(ge=0)
    pass_: conint(ge=0) = Field(..., alias="pass")
    runtime_error: conint(ge=0)
    warn: conint(ge=0)


class FreshnessCheckResult(BaseModel):
    """
    One freshness check.
    """

    age_seconds: int | None = None
    """
    `checked_at - max_loaded_at`, in seconds. Negative when the newest load time is in the future (clock skew).
    """
    error_after_seconds: conint(ge=0) | None = None
    loaded_at_field: str | None = None
    """
    The column read with `MAX(..)`. `None` when the measurement is the model's last successful build from the state store.
    """
    max_loaded_at: AwareDatetime | None = None
    """
    The newest load time seen. `None` when the table is empty, every value is NULL, the model was never built, or the check could not run.
    """
    measured_from: str
    """
    Where `max_loaded_at` came from: `warehouse` or `state_store`.
    """
    message: str | None = None
    """
    Why the status is what it is, when that is not just the age.
    """
    name: str
    """
    Source `schema.table` (or `catalog.schema.table`), or the model name.
    """
    pipeline: str
    """
    The pipeline that declares the source or loads the model.
    """
    status: FreshnessStatus
    """
    `pass`, `warn`, `error`, or `runtime_error`.
    """
    table: str
    """
    The table the measurement was taken from (`catalog.schema.table`).
    """
    warn_after_seconds: conint(ge=0) | None = None


class FreshnessOutput(BaseModel):
    """
    JSON output for `rocky freshness`.
    """

    checked_at: AwareDatetime
    """
    The instant every age was measured against.
    """
    command: str
    models: list[FreshnessCheckResult]
    """
    One entry per model `[freshness]` block.
    """
    sources: list[FreshnessCheckResult]
    """
    One entry per declared source freshness block.
    """
    summary: FreshnessSummary
    version: str
