# generated by datamodel-codegen:
#   filename:  fulfill.schema.json

from __future__ import annotations

from pydantic import BaseModel


class FulfillOutput(BaseModel):
    """
    JSON output of `rocky fulfill <product>` — the reconciler's stop report: how far the loop advanced, why it stopped, and the exact next command when one exists.
    """

    command: str
    """
    Always `"fulfill"`.
    """
    message: str
    """
    Why the loop stopped, in plain language.
    """
    next_command: str | None = None
    """
    The exact command that unblocks it, when one exists.
    """
    plan_id: str | None = None
    """
    The pinned plan, while one is in flight.
    """
    product: str
    """
    The product name the loop was asked to drive.
    """
    product_id: str
    """
    `product:<name>`.
    """
    spec_digest: str | None = None
    """
    The approved spec digest the state was reached under, if any.
    """
    state: str
    """
    The state the record was left in (its wire tag, e.g. `"needs_input"`, `"proposed"`, `"observing"`, `"blocked"`).
    """
    version: str
