# generated by datamodel-codegen:
#   filename:  gc_apply.schema.json

from __future__ import annotations

from pydantic import BaseModel, conint


class GcCheckOutput(BaseModel):
    """
    One printed eligibility check inside a [`GcCandidateOutput`].
    """

    check: str
    """
    Stable check id: `recipe_recorded`, `recipe_produces_output`, `replayable`, `unreferenced`, `policy_allows`, or `age_threshold`.
    """
    detail: str
    """
    Why the check reached that verdict — the auditable justification.
    """
    passed: bool
    """
    Whether the check passed. A candidate is derivable only when all six are `true`.
    """


class GcEvictedOutput(BaseModel):
    """
    One artifact successfully evicted by `rocky apply <gc-plan>` — a tombstone was recorded and the ledger row retired.
    """

    blake3_hash: str
    model_name: str
    physical_reclaimed: bool
    """
    Whether the bytes were physically deleted through the object-store adapter. **Currently always `false`:** physical reclamation is not implemented (it needs a protocol-aware VACUUM), so eviction is ledger-only and `[gc] physical_delete = true` is a hard error. The bytes stay in place; the durable tombstone records the recipe pointer a later `rocky restore` uses to *attempt* a rebuild (see `physical_status`).
    """
    physical_status: str
    """
    Human-readable physical-reclamation outcome. Since eviction is ledger-only, this is always `not attempted — physical reclamation is future protocol-aware VACUUM work; the tombstone + retired ledger row is the eviction of record`.
    """
    run_id: str
    size_bytes: conint(ge=0)
    tombstone_recorded: bool
    """
    Always `true` on this list — the durable restore tombstone was written atomically with the ledger-row retirement before anything else happened.
    """


class GcRefusedOutput(BaseModel):
    """
    One artifact `rocky apply <gc-plan>` **refused** to evict because it was no longer derivable at apply time (the fail-closed re-verification caught ledger drift since plan time — e.g. a new reference appeared).
    """

    blake3_hash: str
    failed_checks: list[GcCheckOutput]
    """
    The eligibility checks as re-evaluated at apply time, so the refusal is auditable rather than asserted.
    """
    model_name: str
    reason: str
    """
    Why the eviction was refused (the failing check summary).
    """
    run_id: str
    size_bytes: conint(ge=0)


class GcApplyOutput(BaseModel):
    """
    JSON output of `rocky apply <gc-plan>`.

    Reports the eviction outcome per planned artifact. Deletion is the highest -stakes operation, so the output is exhaustive: what was evicted (with its tombstone), what was refused (with the live failing checks), and what was an idempotent no-op (already evicted by a prior apply).
    """

    already_evicted: list[str]
    """
    Content hashes of plan entries that were already absent from the ledger (a prior apply evicted them) — idempotent no-ops, not failures.
    """
    bytes_evicted: conint(ge=0)
    """
    Total bytes evicted.
    """
    bytes_refused: conint(ge=0)
    """
    Total bytes refused.
    """
    command: str
    evicted: list[GcEvictedOutput]
    """
    Artifacts evicted — tombstone written, ledger row retired.
    """
    evicted_count: conint(ge=0)
    """
    Count of evicted artifacts.
    """
    notes: list[str]
    """
    Operator caveats (e.g. eviction is ledger-only, restore's narrower coverage). Each eviction's tombstone records a durable pointer to the recipe's provenance — the path `rocky restore <target>` *attempts* a hash-exact rebuild from, which succeeds only for a recipe that reads no recorded upstreams (a multi-input recipe is refused).
    """
    plan_id: str
    refused: list[GcRefusedOutput]
    """
    Artifacts refused because they were no longer derivable at apply time.
    """
    refused_count: conint(ge=0)
    """
    Count of refused artifacts.
    """
    version: str
