# generated by datamodel-codegen:
#   filename:  health.schema.json

from __future__ import annotations

from pydantic import BaseModel


class HealthOutput(BaseModel):
    """
    Liveness payload for the auth-exempt `GET /api/v1/health`.

    Server-lifecycle only: it says the process answers HTTP and which engine release it is. It carries no project state, so it is safe to hand to a prober that holds no token.
    """

    status: str
    """
    Always `"ok"` when the server answers at all.
    """
    version: str
    """
    Engine release (`CARGO_PKG_VERSION`).
    """
