# generated by datamodel-codegen:
#   filename:  lint.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, conint


class LintCounts(BaseModel):
    """
    Finding counts by severity for `rocky lint`.
    """

    error: conint(ge=0)
    info: conint(ge=0)
    warning: conint(ge=0)


class LintSeverity1(StrEnum):
    """
    Fails the run (non-zero exit).
    """

    error = "error"


class LintSeverity2(StrEnum):
    """
    Reported; does not fail the run.
    """

    warning = "warning"


class LintSeverity3(StrEnum):
    """
    Reported; does not fail the run.
    """

    info = "info"


class LintFinding(BaseModel):
    """
    One `rocky lint` finding.
    """

    code: str
    """
    Rule code, e.g. `S001`.
    """
    col: conint(ge=0)
    """
    1-based column, counted in characters.
    """
    file: str
    fixable: bool
    """
    `true` when `rocky lint --fix` can rewrite this finding.
    """
    hint: str
    """
    Short suggestion for the fix.
    """
    line: conint(ge=0)
    """
    1-based line.
    """
    message: str
    rule: str
    """
    Short rule name, e.g. `ambiguous-column`.
    """
    severity: LintSeverity1 | LintSeverity2 | LintSeverity3
    """
    Severity of a `rocky lint` finding. `rocky lint` exits non-zero when it reports at least one `error`.
    """


class LintOutput(BaseModel):
    """
    JSON output for `rocky lint`.
    """

    ast_rules_skipped: list[str]
    """
    Files whose SQL did not parse. The AST rules (`S001`, `S003`, `S004`) did not run on them; the text rules did.
    """
    command: str
    counts: LintCounts
    """
    Finding counts by severity.
    """
    files_checked: conint(ge=0)
    """
    Number of `.sql` files read.
    """
    files_fixed: list[str]
    """
    Files `--fix` changed.
    """
    findings: list[LintFinding]
    """
    Findings left after any `--fix` pass, ordered by file, line and column.
    """
    fixed: conint(ge=0)
    """
    Findings `--fix` rewrote. `0` without `--fix`.
    """
    version: str
