# generated by datamodel-codegen:
#   filename:  list_adapters.schema.json

from __future__ import annotations

from pydantic import BaseModel


class ListAdapterEntry(BaseModel):
    adapter_type: str
    host: str | None = None
    name: str


class ListAdaptersOutput(BaseModel):
    """
    JSON output for `rocky list adapters`.
    """

    adapters: list[ListAdapterEntry]
    command: str
    version: str
