# generated by datamodel-codegen:
#   filename:  meta.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, conint


class MetaTokenScope1(StrEnum):
    """
    Every route, mutating ones included.
    """

    full = "full"


class MetaTokenScope2(StrEnum):
    """
    `GET`, `HEAD` and `OPTIONS` only.
    """

    read_only = "read_only"


class MetaOutput(BaseModel):
    """
    Feature-detection payload for `GET /api/v1/meta`.

    Fingerprints the running engine + bound config so an embedder can pin against a build without version-sniffing. Every field is computed at request time — none are baked literals — so `state_schema_version`, `schemas_hash`, and `config_hash` track the live engine and the on-disk config even across a long-running sidecar.
    """

    capabilities: list[str]
    """
    Feature/capability tokens the build advertises.
    """
    config_hash: str | None = None
    """
    Fingerprint of the resolved `rocky.toml` (contents + path) this sidecar bound, recomputed per request. `null` when no config resolved.
    """
    engine_version: str
    """
    Engine release (`CARGO_PKG_VERSION`).
    """
    routes: list[str]
    """
    The `/api/v1` routes this build serves.
    """
    schemas_hash: str
    """
    Fingerprint of the exported JSON-schema set (the `schemas/*.schema.json` contract). Derived from the live registered schemas, so it moves on every codegen; embedders detect an output-shape change without version-sniffing.
    """
    state_schema_version: conint(ge=0)
    """
    Current state-store schema version, read from the engine's `current_schema_version()` getter at request time (never a literal).
    """
    token_scope: MetaTokenScope1 | MetaTokenScope2 | None = None
    """
    What the server's bearer token may do: `full` reaches every route, `read_only` only safe methods. `null` when no token is configured (a loopback server without `--ui`, which asks no request for one). The UI reads it to enable or disable its write controls. Never the secret.
    """
