# generated by datamodel-codegen:
#   filename:  optimize.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field, conint


class OptimizeRecommendation(BaseModel):
    """
    One materialization-strategy recommendation. Mirrors `rocky_core::optimize::MaterializationCost` but lives in the CLI crate so we don't have to derive JsonSchema across the workspace.
    """

    compute_cost_per_run: float
    """
    Projected per-run compute cost (USD). Populated from `rocky_core::optimize::MaterializationCost::compute_cost_per_run` so Dagster's `checks.py` can surface it as metadata without re-deriving from config.
    """
    current_strategy: str
    downstream_references: conint(ge=0)
    """
    How many downstream models depend on this one. Drives whether the recommendation favours table materialisation (many consumers) vs a view.
    """
    estimated_monthly_savings: float
    model_name: str
    reasoning: str
    recommended_strategy: str
    storage_cost_per_month: float
    """
    Projected monthly storage cost (USD).
    """


class ProductionRunScope(BaseModel):
    """
    Which runs a report about production counted (#2201).

    Shadow and branch runs are never counted. Runs recorded before runs carried a scope are counted or not per report, and `unrecorded_runs_counted` says which.
    """

    excluded_runs: conint(ge=0)
    """
    Shadow and branch runs the report left out.
    """
    production_runs: conint(ge=0)
    """
    Runs recorded as production that the report read.
    """
    unrecorded_runs: conint(ge=0)
    """
    Runs with no recorded scope that the report read.
    """
    unrecorded_runs_counted: bool
    """
    `true` when runs with no recorded scope count as production in this report. Their write target is unknown.
    """


class OptimizeOutput(BaseModel):
    """
    JSON output for `rocky optimize`.

    `recommendations` is empty when no run history exists; `message` is populated in that case to explain why.
    """

    command: str
    message: str | None = None
    recommendations: list[OptimizeRecommendation]
    run_scope: ProductionRunScope | None = Field(
        {
            "excluded_runs": 0,
            "production_runs": 0,
            "unrecorded_runs": 0,
            "unrecorded_runs_counted": False,
        },
        validate_default=True,
    )
    """
    Which runs the recommendations were computed from. Shadow and branch runs are left out; runs with no recorded scope are counted, so history from before #2200 still informs the averages (#2201).
    """
    total_models_analyzed: conint(ge=0)
    version: str
