# generated by datamodel-codegen:
#   filename:  package_add.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field, conint


class PackageDiagnostic(BaseModel):
    """
    A finding from `rocky package`: `E055` (refused) or `W055` (vendored, but something needs a look).
    """

    code: str
    message: str
    model: str | None = None
    """
    The model the finding is about, when there is one.
    """
    path: str | None = None
    """
    The vendored file the finding is about, when there is one.
    """
    severity: str
    """
    `error` or `warning`.
    """


class PackageDroppedTest(BaseModel):
    """
    A dbt test on a package model that was not mapped to Rocky.
    """

    attached_to: str | None = None
    reason: str
    test: str


class PackageFailedModel(BaseModel):
    """
    A package model that could not be vendored.
    """

    name: str
    reason: str


class PackageSourceOutput(BaseModel):
    """
    A raw source table a vendored package reads.
    """

    catalog: str
    name: str
    """
    `<source_name>.<table>` as the package declares it.
    """
    schema_: str = Field(..., alias="schema")
    table: str


class PackageVendorReport(BaseModel):
    """
    What `add` / `update` did for one package.
    """

    adapter: str
    """
    Rocky adapter type the package was compiled against.
    """
    dbt_version: str
    failed_models: list[PackageFailedModel]
    files_deleted: list[str]
    """
    Vendored files deleted because upstream removed them.
    """
    files_incoming: list[str]
    """
    Files you edited that changed upstream: the new version is at `<path>.incoming`.
    """
    files_kept_edited: list[str]
    """
    Files you edited that were left as they are.
    """
    files_unchanged: conint(ge=0)
    files_written: list[str]
    """
    Files written in place.
    """
    hub: str
    """
    dbt Hub name (`fivetran/stripe`).
    """
    includes: list[str]
    """
    Dependency packages whose models were vendored alongside.
    """
    incremental_fallbacks: list[str]
    """
    dbt `incremental` models that did not stay incremental.
    """
    mode: str
    """
    How the SQL was compiled: `compile-only` (`dbt compile` alone; nothing written to the warehouse), `build-empty` (`dbt run --empty` first) or `compiled` (`--compiled <dir>`).
    """
    models: list[str]
    """
    Every vendored model, sorted.
    """
    models_added: list[str]
    """
    Models new in this run (all of them on `add`).
    """
    models_removed: list[str]
    """
    Models the previous version had and this one does not.
    """
    name: str
    """
    dbt project name of the package; its directory under `models/packages/`.
    """
    sources: list[PackageSourceOutput]
    target_schema: str
    """
    Schema the vendored models build into.
    """
    tests_dropped: list[PackageDroppedTest]
    tests_mapped: conint(ge=0)
    """
    dbt generic tests mapped to Rocky `[[tests]]`.
    """
    vars_hash: str
    version: str
    """
    Version `dbt deps` resolved.
    """
    version_spec: str
    """
    Version requirement the package was added with; empty means latest.
    """


class PackageAddOutput(BaseModel):
    """
    JSON output of `rocky package add`.
    """

    command: str
    diagnostics: list[PackageDiagnostic]
    lockfile: str
    """
    Path of `rocky-packages.lock`.
    """
    package: PackageVendorReport
    version: str
