# generated by datamodel-codegen:
#   filename:  package_remove.schema.json

from __future__ import annotations

from pydantic import BaseModel


class PackageRemoveOutput(BaseModel):
    """
    JSON output of `rocky package remove`.
    """

    command: str
    files_deleted: list[str]
    lockfile: str
    name: str
    version: str
