# generated by datamodel-codegen:
#   filename:  plan_promote.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, RootModel, conint


class ApproverSource(StrEnum):
    """
    Where the approval signature was produced.

    Reserved for future CI / OIDC paths. Today only the `Local` variant is emitted by the CLI.
    """

    local = "local"
    ci_oidc = "ci_oidc"
    pat = "pat"


class AuditEventKind7(StrEnum):
    """
    Categorical kind of an [`AuditEvent`] emitted by `branch promote`.
    """

    promote_started = "promote_started"
    promote_completed = "promote_completed"
    promote_failed = "promote_failed"


class AuditEventKind8(StrEnum):
    """
    Emitted when the approval gate was bypassed via `--skip-approval` or the `ROCKY_BRANCH_APPROVAL_SKIP` env-var override. The skip reason is recorded so a future audit can tell flag-skip apart from env-skip.
    """

    approval_skipped = "approval_skipped"


class AuditEventKind9(StrEnum):
    """
    Emitted when the semantic breaking-change gate blocked the promote. The findings list is carried on the parent [`AuditEvent`] so reviewers see exactly which structural changes triggered the block.
    """

    breaking_changes_blocked = "breaking_changes_blocked"


class AuditEventKind10(StrEnum):
    """
    Emitted when the semantic breaking-change gate detected one or more `Breaking`-severity findings but the operator overrode the block via `--allow-breaking`. Records the findings so the override leaves an audit trail equivalent to `ApprovalSkipped`.
    """

    breaking_changes_allowed = "breaking_changes_allowed"


class AuditEventKind11(StrEnum):
    """
    Emitted when the semantic breaking-change gate could not run — for example because the base ref failed to compile under the current Rocky version. Fail-open: the gate is skipped and the promote proceeds, but the reason is recorded so the bypass is auditable.
    """

    breaking_changes_gate_skipped = "breaking_changes_gate_skipped"


class AuditEventKind12(StrEnum):
    """
    Emitted by `rocky plan promote` when the plan has been successfully written to `.rocky/plans/<plan_id>.json`. Carries the plan_id so an audit consumer can correlate plan creation to a subsequent `rocky apply` event without scanning the filesystem.
    """

    promote_plan_created = "promote_plan_created"


class Kind(StrEnum):
    model_removed = "model_removed"


class BreakingChange(BaseModel):
    """
    A model present on the base side is absent on the head side.
    """

    kind: Kind
    model: str


class Kind57(StrEnum):
    model_added = "model_added"


class BreakingChange53(BaseModel):
    """
    A model present on the head side is absent on the base side.
    """

    kind: Kind57
    model: str


class Kind58(StrEnum):
    column_dropped = "column_dropped"


class BreakingChange54(BaseModel):
    """
    A column present on the base side is absent on the head side.
    """

    column: str
    data_type: str
    kind: Kind58
    model: str


class Kind59(StrEnum):
    column_added = "column_added"


class BreakingChange55(BaseModel):
    """
    A column was added.
    """

    column: str
    data_type: str
    kind: Kind59
    model: str
    nullable: bool


class Kind60(StrEnum):
    column_type_changed = "column_type_changed"


class BreakingChange56(BaseModel):
    """
    A column's data type changed.
    """

    column: str
    kind: Kind60
    model: str
    narrowing: bool
    """
    `true` when the new type cannot represent every value of the old type (Int64 → Int32, Decimal precision shrink, Timestamp → Date).
    """
    new_type: str
    old_type: str


class Kind61(StrEnum):
    column_nullability_changed = "column_nullability_changed"


class BreakingChange57(BaseModel):
    """
    A column's nullability flipped.
    """

    column: str
    kind: Kind61
    model: str
    new_nullable: bool
    old_nullable: bool


class Kind62(StrEnum):
    column_reordered = "column_reordered"


class BreakingChange58(BaseModel):
    """
    A column's position in the output schema changed. `SELECT *` downstream consumers see different positional projection.
    """

    column: str
    kind: Kind62
    model: str
    new_index: conint(ge=0)
    old_index: conint(ge=0)


class Kind63(StrEnum):
    materialization_strategy_changed = "materialization_strategy_changed"


class BreakingChange59(BaseModel):
    """
    The materialization strategy switched between top-level variants (e.g. `FullRefresh` → `Incremental`).
    """

    kind: Kind63
    model: str
    new_strategy: str
    old_strategy: str


class Kind64(StrEnum):
    materialization_key_changed = "materialization_key_changed"


class BreakingChange60(BaseModel):
    """
    Materialization-specific key columns changed without the top-level variant changing (e.g. `Merge` `unique_key` rewritten, `Incremental` `timestamp_column` swapped).
    """

    key_kind: str
    """
    Which key changed: `unique_key`, `timestamp_column`, `partition_by`, `time_column`, `granularity`, `target_lag`, `update_columns`, `storage_prefix`, or `partition_columns`.
    """
    kind: Kind64
    model: str
    new: list[str]
    old: list[str]


class Kind65(StrEnum):
    replication_columns_changed = "replication_columns_changed"


class BreakingChange61(BaseModel):
    """
    Replication column-selection mode flipped between `All` and `Explicit(...)` or the explicit list changed.
    """

    kind: Kind65
    model: str
    new: list[str]
    old: list[str]


class Kind66(StrEnum):
    partition_by_changed = "partition_by_changed"


class BreakingChange62(BaseModel):
    """
    `LakehouseOptions::partition_by` changed without the strategy changing. Distinct from `MaterializationKeyChanged` since this lives on `format_options` rather than the strategy enum.
    """

    kind: Kind66
    model: str
    new: list[str]
    old: list[str]


class Kind67(StrEnum):
    target_renamed = "target_renamed"


class BreakingChange63(BaseModel):
    """
    Target table reference renamed (catalog, schema, or table component).
    """

    kind: Kind67
    model: str
    new: str
    old: str


class Kind68(StrEnum):
    source_changed = "source_changed"


class BreakingChange64(BaseModel):
    """
    Source reference rebound to a different table.
    """

    kind: Kind68
    model: str
    new: list[str]
    old: list[str]


class Kind69(StrEnum):
    column_mask_changed = "column_mask_changed"


class BreakingChange65(BaseModel):
    """
    A column mask was added, removed, or its strategy changed.
    """

    column: str
    kind: Kind69
    model: str
    new_strategy: str | None = None
    old_strategy: str | None = None


class Kind70(StrEnum):
    lakehouse_format_changed = "lakehouse_format_changed"


class BreakingChange66(BaseModel):
    """
    Lakehouse format switched (e.g. `DeltaTable` → `IcebergTable`).
    """

    kind: Kind70
    model: str
    new: str
    old: str


class Kind71(StrEnum):
    sql_body_changed = "sql_body_changed"


class BreakingChange67(BaseModel):
    """
    SQL body changed without any other detectable structural change. Surfaced as `Info` because the typed-output shape is unchanged, but runtime row contents may differ.
    """

    kind: Kind71
    model: str


class BreakingSeverity10(StrEnum):
    """
    Will break a downstream consumer that reads the model's prior shape.
    """

    breaking = "breaking"


class BreakingSeverity11(StrEnum):
    """
    May break consumers depending on usage; e.g. nullable → NOT NULL, column reordered.
    """

    warning = "warning"


class BreakingSeverity12(StrEnum):
    """
    Informational only — purely additive or backwards-compatible.
    """

    info = "info"


class PromoteTargetPlan(BaseModel):
    """
    Per-model promote step captured in a [`PromotePlan`].

    Mirrors the shape of [`PromoteTarget`] but contains only plan-time fields (`target`, `source`, `statement`). Execution outcome (`succeeded`, `error`) is added at apply time and lives on [`PromoteTarget`].

    `statement` is persisted verbatim so `rocky apply` executes the **exact** SQL generated at plan time — skipping re-discovery and ensuring the `plan_id` digest is invalidated if the SQL would differ.
    """

    source: str
    """
    Fully-qualified branch source the promote will read from (catalog.branch_schema.table).
    """
    statement: str
    """
    `CREATE OR REPLACE TABLE <target> AS SELECT * FROM <source>` SQL, dialect-quoted at plan time.
    """
    target: str
    """
    Fully-qualified production target (catalog.schema.table).
    """


class RejectedApproval(BaseModel):
    """
    An approval artifact that was loaded from disk but rejected.
    """

    approval_id: str
    detail: str
    reason: str
    """
    One of: `bad_signature`, `state_hash_mismatch`, `expired`, `signer_not_allowed`, `parse_error`.
    """


class SignatureAlgorithm3(StrEnum):
    """
    blake3 over a canonical-JSON encoding of the artifact payload, with the approver's git identity bound into the hashed bytes. Detects tamper-after-write but is not asymmetric crypto — see the approval-flow docs for the security model.
    """

    blake3_canonical_json = "blake3_canonical_json"


class SignatureAlgorithm(RootModel[SignatureAlgorithm3]):
    root: SignatureAlgorithm3
    """
    Algorithm tag for an [`ApprovalSignature`].

    The discriminator is on disk from day one so future "real" cryptographic signing variants slot in without migrating existing artifacts.
    """


class ApprovalSignature(BaseModel):
    """
    Signature attached to an [`ApprovalArtifact`].
    """

    algorithm: SignatureAlgorithm
    digest: str
    """
    Hex-encoded digest. For `Blake3CanonicalJson`, this is the 32-byte blake3 hash printed as 64 lowercase hex characters.
    """


class ApproverIdentity(BaseModel):
    """
    Identity of an approver, captured at sign time.

    Email is sourced from `git config user.email`; name from `git config user.name`. Hostname is best-effort from the `hostname` crate and surfaced as an audit aid only — it is not part of the trust boundary. Set `ROCKY_SCRUB_HOST` in the environment to replace the hostname with `"redacted"` when recording public demos.
    """

    email: str
    host: str
    name: str | None = None
    source: ApproverSource


class BreakingFinding(BaseModel):
    """
    A classified finding produced by [`diff_project_ir`].
    """

    change: (
        BreakingChange
        | BreakingChange53
        | BreakingChange54
        | BreakingChange55
        | BreakingChange56
        | BreakingChange57
        | BreakingChange58
        | BreakingChange59
        | BreakingChange60
        | BreakingChange61
        | BreakingChange62
        | BreakingChange63
        | BreakingChange64
        | BreakingChange65
        | BreakingChange66
        | BreakingChange67
    )
    """
    A single typed semantic change between two `ProjectIr` snapshots.

    Each variant carries the minimum identifying context (model + column + before/after values) needed for a CLI / PR-preview surface to render a useful message without re-loading either IR.
    """
    severity: BreakingSeverity10 | BreakingSeverity11 | BreakingSeverity12
    """
    Severity classification for a single semantic change.
    """


class ApprovalArtifact(BaseModel):
    """
    On-disk approval record for a single approver against a single branch.

    One file per approver under `./.rocky/approvals/<branch>/<approval_id>.json`. `branch_state_hash` binds the approval to the branch's content-addressed state at sign time; if the branch's hash changes (config bytes change), every existing artifact for that branch becomes stale and `branch promote` will refuse to honour it.
    """

    approval_id: str
    """
    Sortable monotonic identifier — timestamp prefix + random tail.
    """
    approver: ApproverIdentity
    branch: str
    branch_state_hash: str
    message: str | None = None
    signature: ApprovalSignature
    signed_at: AwareDatetime


class AuditEvent(BaseModel):
    """
    Single audit-trail event emitted during `branch promote`.

    Routed to stdout JSON only in v1; persistent audit storage is a follow-up.
    """

    actor: ApproverIdentity
    at: AwareDatetime
    branch: str
    branch_state_hash: str
    breaking_changes: list[BreakingFinding] | None = None
    """
    Breaking-change findings carried by `BreakingChangesBlocked` and `BreakingChangesAllowed` events. Always absent for other kinds.
    """
    kind: (
        AuditEventKind7
        | AuditEventKind8
        | AuditEventKind9
        | AuditEventKind10
        | AuditEventKind11
        | AuditEventKind12
    )
    """
    Categorical kind of an [`AuditEvent`] emitted by `branch promote`.
    """
    reason: str | None = None
    """
    Free-form context. Populated for `ApprovalSkipped` to record the origin of the skip, and for `BreakingChangesGateSkipped` to record why the gate could not run (e.g. "base ref did not compile"). Empty for routine state events.
    """


class PromotePlan(BaseModel):
    """
    Persisted payload for a `rocky plan promote` run plan.

    Written to `.rocky/plans/<plan_id>.json` by `rocky plan promote` and read back by `rocky apply <plan_id>` (dispatched as `PlanKind::Promote`).

    ## What is persisted vs re-derived

    - **Persisted**: branch name + refs, state hash at plan time, approval artifacts used/rejected, breaking-change findings, per-target SQL statements, and the plan-time audit events. - **Re-derived at apply time**: nothing related to approvals or breaking-change gate — those gates ran at plan time and their outcomes are captured here. The warehouse adapter is resolved at apply time (to call `execute_statement`), but discovery is NOT re-run.

    ## Branch state drift at apply time

    `branch_state_hash` reflects the branch metadata + config bytes at plan time. If the branch's config or metadata changes between `rocky plan promote` and `rocky apply`, the persisted hash differs from the live hash. By default, `rocky apply` does **not** re-check the hash — the gates already ran at plan time, and that is the point of the plan/apply split. Operators who need a strict re-check can re-run `rocky plan promote` to produce a fresh plan.

    Warehouse table contents are not covered by `branch_state_hash` in v1 — if a branch's tables are mutated between plan and apply, `rocky apply` will promote whatever data is in the branch schema at apply time.
    """

    allow_breaking: bool | None = False
    """
    Whether `--allow-breaking` was set at plan time.
    """
    approvals_rejected: list[RejectedApproval]
    """
    Approval artifacts loaded from disk that failed verification at plan time.
    """
    approvals_used: list[ApprovalArtifact]
    """
    Approval artifacts that satisfied the gate at plan time.
    """
    base_ref: str
    """
    Git ref that `base_ref` was resolved to at plan time (e.g. `"main"`).
    """
    branch_name: str
    """
    Branch name being promoted.
    """
    branch_state_hash: str
    """
    Content-addressed hash of the branch metadata + config bytes at plan time. Stored for audit purposes; not re-validated at apply time.
    """
    breaking_changes: list[BreakingFinding] | None = None
    """
    Semantic breaking-change findings produced by the pre-promote gate at plan time. Empty when the gate ran and found no breaking changes; absent when the gate was skipped (compile failure on either side).
    """
    created_at: AwareDatetime
    """
    When this plan was persisted.
    """
    head_ref: str
    """
    Git HEAD SHA at plan time — informational for audit purposes.
    """
    plan_audit: list[AuditEvent]
    """
    Plan-time audit events (approvals gate + breaking-change gate outcomes). Apply-time events (`PromoteStarted`, `PromoteCompleted`, `PromoteFailed`) are appended in `BranchPromoteOutput.audit` at apply time.
    """
    targets: list[PromoteTargetPlan]
    """
    Per-model SQL plan, in dispatch order. SQL is persisted verbatim so `rocky apply` executes the exact statements generated at plan time.
    """
