# generated by datamodel-codegen:
#   filename:  policy_check.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, conint


class PolicyCapability37(StrEnum):
    """
    Read model output / metadata. Always allowed.
    """

    read = "read"


class PolicyCapability38(StrEnum):
    """
    Draft a plan for later review.
    """

    propose = "propose"


class PolicyCapability39(StrEnum):
    """
    Apply a plan against the warehouse.
    """

    apply = "apply"


class PolicyCapability40(StrEnum):
    """
    Promote a branch / environment.
    """

    promote = "promote"


class PolicyCapability41(StrEnum):
    """
    Backfill historical partitions.
    """

    backfill = "backfill"


class PolicyCapability42(StrEnum):
    """
    Garbage-collect / reclaim storage.
    """

    gc = "gc"


class PolicyCapability43(StrEnum):
    """
    Restore a gc-evicted artifact from its tombstone (*attempts* a rebuild, then verifies hash-exact — supported only for a recipe that reads no recorded upstreams; a multi-input recipe is refused).
    """

    restore = "restore"


class PolicyCapability44(StrEnum):
    """
    Retry a failed run.
    """

    retry = "retry"


class PolicyCapability45(StrEnum):
    """
    Quarantine a partition / model.
    """

    quarantine = "quarantine"


class PolicyCapability46(StrEnum):
    """
    An additive schema change (refinement of apply/promote).
    """

    schema_change_additive = "schema_change.additive"


class PolicyCapability47(StrEnum):
    """
    A breaking schema change (refinement of apply/promote).
    """

    schema_change_breaking = "schema_change.breaking"


class PolicyCapability48(StrEnum):
    """
    A value-only data change (refinement of apply/promote).
    """

    value_change = "value_change"


class PolicyEffect10(StrEnum):
    """
    Permit the action outright.
    """

    allow = "allow"


class PolicyEffect11(StrEnum):
    """
    Permit only after human review. The safe default posture.
    """

    require_review = "require_review"


class PolicyEffect12(StrEnum):
    """
    Refuse the action. A hard override — no `allow` overturns it.
    """

    deny = "deny"


class PolicyModelAttributes(BaseModel):
    """
    The compiled attributes of the checked model, echoed back so the explain output is self-contained.
    """

    classifications: list[str]
    """
    Distinct column-classification values present on the model.
    """
    contracted: bool
    """
    Whether the model sits behind a contract (best-effort: a sibling `.contract.toml` exists).
    """
    downstreams: conint(ge=0)
    """
    Direct downstream-consumer count (models that `depends_on` this one). Informational — the `max_downstreams` ceiling reads [`Self::reachable_downstreams`].
    """
    layer: str | None = None
    """
    Medallion/semantic layer (the model's `layer` tag), if any.
    """
    reachable_downstreams: conint(ge=0) | None = None
    """
    Transitive downstream reachability — the full blast radius (direct + indirect), excluding the model itself. This is what a rule's `max_downstreams` ceiling is compared against. `null` when the blast radius could not be computed (the ceiling then fails closed).
    """
    tags: dict[str, str]
    """
    Model-level governance tags.
    """


class PolicyPrincipal7(StrEnum):
    """
    A person.
    """

    human = "human"


class PolicyPrincipal8(StrEnum):
    """
    A non-human caller (AI agent / automation).
    """

    agent = "agent"


class PolicyCheckOutput(BaseModel):
    """
    JSON output for `rocky policy check`.

    An explain surface: reports the *base* effect the agent policy plane resolves for a `(principal, capability, model)` triple, the winning rule (if any), and why. The check itself is read-only and static; the same evaluator is enforced at `apply`, `promote`, and the MCP write tools, where active freezes and autonomy-budget burn are also projected and can only tighten the effect reported here.
    """

    capability: (
        PolicyCapability37
        | PolicyCapability38
        | PolicyCapability39
        | PolicyCapability40
        | PolicyCapability41
        | PolicyCapability42
        | PolicyCapability43
        | PolicyCapability44
        | PolicyCapability45
        | PolicyCapability46
        | PolicyCapability47
        | PolicyCapability48
    )
    """
    The capability that was checked.
    """
    command: str
    effect: PolicyEffect10 | PolicyEffect11 | PolicyEffect12
    """
    Resolved effect: `allow`, `require_review`, or `deny`.
    """
    matched_rule: conint(ge=0) | None = None
    """
    Zero-based index of the winning rule in `[[policy.rules]]`, or `null` when the decision came from a short-circuit (`read`) or the default posture (no rule matched).
    """
    model: str
    """
    The model that was checked.
    """
    model_attributes: PolicyModelAttributes
    """
    The compiled model attributes the matcher read.
    """
    principal: PolicyPrincipal7 | PolicyPrincipal8
    """
    The principal that was checked (`human` / `agent`).
    """
    reason: str
    """
    Human-readable explanation of how the effect was reached.
    """
    version: str
