# generated by datamodel-codegen:
#   filename:  policy_check.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, conint


class PolicyCapability12(StrEnum):
    """
    Read model output / metadata. Always allowed.
    """

    read = "read"


class PolicyCapability13(StrEnum):
    """
    Draft a plan for later review.
    """

    propose = "propose"


class PolicyCapability14(StrEnum):
    """
    Apply a plan against the warehouse.
    """

    apply = "apply"


class PolicyCapability15(StrEnum):
    """
    Promote a branch / environment.
    """

    promote = "promote"


class PolicyCapability16(StrEnum):
    """
    Backfill historical partitions.
    """

    backfill = "backfill"


class PolicyCapability17(StrEnum):
    """
    Garbage-collect / reclaim storage.
    """

    gc = "gc"


class PolicyCapability18(StrEnum):
    """
    Retry a failed run.
    """

    retry = "retry"


class PolicyCapability19(StrEnum):
    """
    Quarantine a partition / model.
    """

    quarantine = "quarantine"


class PolicyCapability20(StrEnum):
    """
    An additive schema change (refinement of apply/promote).
    """

    schema_change_additive = "schema_change.additive"


class PolicyCapability21(StrEnum):
    """
    A breaking schema change (refinement of apply/promote).
    """

    schema_change_breaking = "schema_change.breaking"


class PolicyCapability22(StrEnum):
    """
    A value-only data change (refinement of apply/promote).
    """

    value_change = "value_change"


class PolicyEffect4(StrEnum):
    """
    Permit the action outright.
    """

    allow = "allow"


class PolicyEffect5(StrEnum):
    """
    Permit only after human review. The safe default posture.
    """

    require_review = "require_review"


class PolicyEffect6(StrEnum):
    """
    Refuse the action. A hard override — no `allow` overturns it.
    """

    deny = "deny"


class PolicyModelAttributes(BaseModel):
    """
    The compiled attributes of the checked model, echoed back so the explain output is self-contained.
    """

    classifications: list[str]
    """
    Distinct column-classification values present on the model.
    """
    contracted: bool
    """
    Whether the model sits behind a contract (best-effort: a sibling `.contract.toml` exists).
    """
    downstreams: conint(ge=0)
    """
    Direct downstream-consumer count (informational; `max_downstreams` is parse-only in v0).
    """
    layer: str | None = None
    """
    Medallion/semantic layer (the model's `layer` tag), if any.
    """
    tags: dict[str, str]
    """
    Model-level governance tags.
    """


class PolicyPrincipal3(StrEnum):
    """
    A person.
    """

    human = "human"


class PolicyPrincipal4(StrEnum):
    """
    A non-human caller (AI agent / automation).
    """

    agent = "agent"


class PolicyCheckOutput(BaseModel):
    """
    JSON output for `rocky policy check`.

    Explain-mode only: reports the effect the agent policy plane *would* resolve for a `(principal, capability, model)` triple, the winning rule (if any), and why. It does not gate any real command in v0.
    """

    capability: (
        PolicyCapability12
        | PolicyCapability13
        | PolicyCapability14
        | PolicyCapability15
        | PolicyCapability16
        | PolicyCapability17
        | PolicyCapability18
        | PolicyCapability19
        | PolicyCapability20
        | PolicyCapability21
        | PolicyCapability22
    )
    """
    The capability that was checked.
    """
    command: str
    effect: PolicyEffect4 | PolicyEffect5 | PolicyEffect6
    """
    Resolved effect: `allow`, `require_review`, or `deny`.
    """
    matched_rule: conint(ge=0) | None = None
    """
    Zero-based index of the winning rule in `[[policy.rules]]`, or `null` when the decision came from a short-circuit (`read`) or the default posture (no rule matched).
    """
    model: str
    """
    The model that was checked.
    """
    model_attributes: PolicyModelAttributes
    """
    The compiled model attributes the matcher read.
    """
    principal: PolicyPrincipal3 | PolicyPrincipal4
    """
    The principal that was checked (`human` / `agent`).
    """
    reason: str
    """
    Human-readable explanation of how the effect was reached.
    """
    version: str
