# generated by datamodel-codegen:
#   filename:  policy_check.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, conint


class PolicyCapability1(StrEnum):
    """
    Read model output / metadata. Always allowed.
    """

    read = "read"


class PolicyCapability2(StrEnum):
    """
    Draft a plan for later review.
    """

    propose = "propose"


class PolicyCapability3(StrEnum):
    """
    Apply a plan against the warehouse.
    """

    apply = "apply"


class PolicyCapability4(StrEnum):
    """
    Promote a branch / environment.
    """

    promote = "promote"


class PolicyCapability5(StrEnum):
    """
    Backfill historical partitions.
    """

    backfill = "backfill"


class PolicyCapability6(StrEnum):
    """
    Garbage-collect / reclaim storage.
    """

    gc = "gc"


class PolicyCapability7(StrEnum):
    """
    Retry a failed run.
    """

    retry = "retry"


class PolicyCapability8(StrEnum):
    """
    Quarantine a partition / model.
    """

    quarantine = "quarantine"


class PolicyCapability9(StrEnum):
    """
    An additive schema change (refinement of apply/promote).
    """

    schema_change_additive = "schema_change.additive"


class PolicyCapability10(StrEnum):
    """
    A breaking schema change (refinement of apply/promote).
    """

    schema_change_breaking = "schema_change.breaking"


class PolicyCapability11(StrEnum):
    """
    A value-only data change (refinement of apply/promote).
    """

    value_change = "value_change"


class PolicyEffect1(StrEnum):
    """
    Permit the action outright.
    """

    allow = "allow"


class PolicyEffect2(StrEnum):
    """
    Permit only after human review.
    """

    require_review = "require_review"


class PolicyEffect3(StrEnum):
    """
    Refuse the action. A hard override — no `allow` overturns it.
    """

    deny = "deny"


class PolicyModelAttributes(BaseModel):
    """
    The compiled attributes of the checked model, echoed back so the explain output is self-contained.
    """

    classifications: list[str]
    """
    Distinct column-classification values present on the model.
    """
    contracted: bool
    """
    Whether the model sits behind a contract (best-effort: a sibling `.contract.toml` exists).
    """
    downstreams: conint(ge=0)
    """
    Direct downstream-consumer count (informational; `max_downstreams` is parse-only in v0).
    """
    layer: str | None = None
    """
    Medallion/semantic layer (the model's `layer` tag), if any.
    """
    tags: dict[str, str]
    """
    Model-level governance tags.
    """


class PolicyPrincipal1(StrEnum):
    """
    A person.
    """

    human = "human"


class PolicyPrincipal2(StrEnum):
    """
    A non-human caller (AI agent / automation).
    """

    agent = "agent"


class PolicyCheckOutput(BaseModel):
    """
    JSON output for `rocky policy check`.

    Explain-mode only: reports the effect the agent policy plane *would* resolve for a `(principal, capability, model)` triple, the winning rule (if any), and why. It does not gate any real command in v0.
    """

    capability: (
        PolicyCapability1
        | PolicyCapability2
        | PolicyCapability3
        | PolicyCapability4
        | PolicyCapability5
        | PolicyCapability6
        | PolicyCapability7
        | PolicyCapability8
        | PolicyCapability9
        | PolicyCapability10
        | PolicyCapability11
    )
    """
    The capability that was checked.
    """
    command: str
    effect: PolicyEffect1 | PolicyEffect2 | PolicyEffect3
    """
    Resolved effect: `allow`, `require_review`, or `deny`.
    """
    matched_rule: conint(ge=0) | None = None
    """
    Zero-based index of the winning rule in `[[policy.rules]]`, or `null` when the decision came from a short-circuit (`read`) or the default posture (no rule matched).
    """
    model: str
    """
    The model that was checked.
    """
    model_attributes: PolicyModelAttributes
    """
    The compiled model attributes the matcher read.
    """
    principal: PolicyPrincipal1 | PolicyPrincipal2
    """
    The principal that was checked (`human` / `agent`).
    """
    reason: str
    """
    Human-readable explanation of how the effect was reached.
    """
    version: str
