# generated by datamodel-codegen:
#   filename:  policy_freeze.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel


class PolicyEffect(StrEnum):
    """
    Permit the action outright.
    """

    allow = "allow"


class PolicyEffect15(StrEnum):
    """
    Permit only after human review. The safe default posture.
    """

    require_review = "require_review"


class PolicyEffect16(StrEnum):
    """
    Refuse the action. A hard override — no `allow` overturns it.
    """

    deny = "deny"


class PolicyPrincipal9(StrEnum):
    """
    A person.
    """

    human = "human"


class PolicyPrincipal10(StrEnum):
    """
    A non-human caller (AI agent / automation).
    """

    agent = "agent"


class PolicyFreezeEntry(BaseModel):
    """
    One principal's freeze/unfreeze record inside a [`PolicyFreezeOutput`].
    """

    decision_ref: str
    """
    Composite ledger key citation (`"{timestamp}|{plan_id}|{scope}"`).
    """
    effect: PolicyEffect | PolicyEffect15 | PolicyEffect16
    """
    The recorded effect (`deny` for a freeze, `allow` for an unfreeze).
    """
    plan_id: str
    """
    The freeze decision's `plan_id`.
    """
    principal: PolicyPrincipal9 | PolicyPrincipal10
    """
    The principal whose actions were frozen/unfrozen.
    """
    reason: str
    """
    Human-readable description of the freeze/unfreeze.
    """


class PolicyFreezeOutput(BaseModel):
    """
    JSON output for `rocky policy freeze` / `rocky policy unfreeze` — the kill switch.

    A freeze records a decision entry per matched principal into the existing policy-decision ledger; at the enforcement seam an active freeze forces `deny`. `unfreeze` records a superseding entry that lifts it. No config file is rewritten and no new table is created.
    """

    command: str
    """
    `policy_freeze` or `policy_unfreeze`.
    """
    entries: list[PolicyFreezeEntry]
    """
    One entry per affected principal.
    """
    lifted: bool
    """
    `true` when this call lifted a freeze rather than establishing one.
    """
    recorded_at: str
    """
    RFC 3339 wall clock when the freeze/unfreeze was recorded.
    """
    scope: str
    """
    The scope selector the freeze targets (`any`, `layer=…`, `tag=…`, …).
    """
    version: str
