# generated by datamodel-codegen:
#   filename:  policy_show.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import AwareDatetime, BaseModel, conint


class PolicyAutonomyBudgetOutput(BaseModel):
    """
    A rule's autonomy budget: `failures` within `window` degrade its effect.
    """

    failures: conint(ge=0)
    window: str


class PolicyCapability(StrEnum):
    """
    Read model output / metadata. Always allowed.
    """

    read = "read"


class PolicyCapability51(StrEnum):
    """
    Draft a plan for later review.
    """

    propose = "propose"


class PolicyCapability52(StrEnum):
    """
    Apply a plan against the warehouse.
    """

    apply = "apply"


class PolicyCapability53(StrEnum):
    """
    Promote a branch / environment.
    """

    promote = "promote"


class PolicyCapability54(StrEnum):
    """
    Backfill historical partitions.
    """

    backfill = "backfill"


class PolicyCapability55(StrEnum):
    """
    Garbage-collect / reclaim storage.
    """

    gc = "gc"


class PolicyCapability56(StrEnum):
    """
    Restore a gc-evicted artifact from its tombstone (*attempts* a rebuild, then verifies hash-exact — supported only for a recipe that reads no recorded upstreams; a multi-input recipe is refused).
    """

    restore = "restore"


class PolicyCapability57(StrEnum):
    """
    Retry a failed run.
    """

    retry = "retry"


class PolicyCapability58(StrEnum):
    """
    Quarantine a partition / model.
    """

    quarantine = "quarantine"


class PolicyCapability59(StrEnum):
    """
    An additive schema change (refinement of apply/promote).
    """

    schema_change_additive = "schema_change.additive"


class PolicyCapability60(StrEnum):
    """
    A breaking schema change (refinement of apply/promote).
    """

    schema_change_breaking = "schema_change.breaking"


class PolicyCapability61(StrEnum):
    """
    A value-only data change (refinement of apply/promote).
    """

    value_change = "value_change"


class PolicyEffect17(StrEnum):
    """
    Permit the action outright.
    """

    allow = "allow"


class PolicyEffect18(StrEnum):
    """
    Permit only after human review. The safe default posture.
    """

    require_review = "require_review"


class PolicyEffect19(StrEnum):
    """
    Refuse the action. A hard override — no `allow` overturns it.
    """

    deny = "deny"


class PolicyFreezeSources(BaseModel):
    """
    Which freeze sources the report read.
    """

    ledger: str
    """
    `"read"`, or `"absent"` when the project has no state store yet.
    """
    markers: str
    """
    `"read"`, or `"not_configured"` when `[state]` keeps no durable markers (a local backend, or `freeze_marker_writes = false`).
    """


class PolicyPrincipal11(StrEnum):
    """
    A person.
    """

    human = "human"


class PolicyPrincipal12(StrEnum):
    """
    A non-human caller (AI agent / automation).
    """

    agent = "agent"


class PolicyRuleScopeOutput(BaseModel):
    """
    What a rule matches. Every field is as authored; an empty list or `None` means the field does not narrow the rule.
    """

    any: bool
    classifications: list[str]
    contracted: bool | None = None
    exclude_classifications: list[str]
    layer: str | None = None
    max_downstreams: conint(ge=0) | None = None
    """
    The blast-radius ceiling: the rule matches only a model with at most this many downstreams.
    """
    models: list[str]
    tags: dict[str, str]


class PolicyFreezeInForce(BaseModel):
    """
    One freeze in force.
    """

    freeze_id: str | None = None
    """
    The marker's id.
    """
    plan_id: str | None = None
    """
    The ledger decision's plan id.
    """
    principal: PolicyPrincipal11 | PolicyPrincipal12 | None = None
    """
    The frozen principal. Absent on a marker that froze both.
    """
    reason: str
    scope: str
    """
    The scope selector as given to `rocky policy freeze`; `any` is every model.
    """
    since: AwareDatetime | None = None
    """
    When the freeze was recorded, when the source recorded it.
    """
    source: str
    """
    `"ledger"` (a `rocky policy freeze` decision) or `"marker"` (a durable freeze marker in the remote object tier).
    """


class PolicyRuleEntry(BaseModel):
    """
    One `[[policy.rules]]` entry.
    """

    autonomy_budget: PolicyAutonomyBudgetOutput | None = None
    """
    The rolling failure ceiling that degrades this rule's effect.
    """
    capability: (
        PolicyCapability
        | PolicyCapability51
        | PolicyCapability52
        | PolicyCapability53
        | PolicyCapability54
        | PolicyCapability55
        | PolicyCapability56
        | PolicyCapability57
        | PolicyCapability58
        | PolicyCapability59
        | PolicyCapability60
        | PolicyCapability61
    )
    """
    The class of action a policy rule governs.

    `read` is always allowed (short-circuit). The mutating verbs (`propose` … `quarantine`) name coarse operations; `schema_change.additive`, `schema_change.breaking`, and `value_change` are *refinements* of the apply/promote verbs — a rule naming a bare verb (`apply`/`promote`) matches those refinements too, but a rule naming a refinement matches only that exact refinement.
    """
    conditions: Any | None = None
    """
    Free-form conditions the rule was written with, as authored. The engine parses them and never evaluates them: no `conditions` predicate narrows a rule's effect today, so a reader must not show them as part of what decided an outcome. They are here because a policy screen should be able to show what a rule's author wrote, including the part not yet in force.
    """
    effect: PolicyEffect17 | PolicyEffect18 | PolicyEffect19
    """
    The verdict a policy rule (or the default posture) yields.

    Ordered by restrictiveness for incomparable-rule tie-breaking: `Deny` is a hard override (handled separately), and among non-deny verdicts `RequireReview` is more restrictive than `Allow`.
    """
    id: conint(ge=0)
    """
    Zero-based position in `[[policy.rules]]`; the `matched_rule` that `rocky policy check` reports.
    """
    principal: PolicyPrincipal11 | PolicyPrincipal12
    """
    Who is attempting an action.

    `agent` is a non-human caller (an AI harness authoring, applying, or remediating). `human` is a person. In v0 the principal is supplied explicitly (`rocky policy check --principal …`); auto-detection is a later phase.
    """
    scope: PolicyRuleScopeOutput


class PolicyRulesOutput(BaseModel):
    """
    JSON output for `rocky policy show`, and the body of `GET /api/v1/policy`: the policy plane as configured and as it stands.

    The rules carry their position in `[[policy.rules]]` as `id`, the only identity a rule has today and the number `rocky policy check` reports as `matched_rule`. `freezes` is every freeze in force, from the decision ledger and, when the project keeps them, the durable freeze markers; `freeze_sources` says which of the two was read. A source that exists but cannot be read is an error, never an empty list: an empty list would say "nothing is frozen" for a plane whose freezes could not be read at all.
    """

    command: str
    """
    Always `"policy_show"`.
    """
    configured: bool
    """
    Whether `rocky.toml` carries a `[policy]` block. `false` is the default posture: no rules, `default_agent_effect` as the engine defaults it.
    """
    default_agent_effect: PolicyEffect17 | PolicyEffect18 | PolicyEffect19
    """
    The effect an agent gets when no rule matches.
    """
    freeze_sources: PolicyFreezeSources
    freezes: list[PolicyFreezeInForce]
    """
    Every freeze in force, ledger entries first, then markers.
    """
    policy_version: conint(ge=0)
    rules: list[PolicyRuleEntry]
    """
    The rules in file order.
    """
    version: str
