# generated by datamodel-codegen:
#   filename:  preview_diff.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field, conint


class BisectionStatsOutput(BaseModel):
    """
    CLI-side mirror of [`rocky_core::compare::bisection::BisectionStats`]. Kept separate so the JSON schema lives alongside the rest of the `rocky preview diff` output types — same pattern as [`BudgetBreachOutput`] mirroring `rocky_core::config::BudgetBreach`.
    """

    chunks_examined: conint(ge=0)
    """
    Total non-empty chunk-checksum entries returned across both sides and all recursion levels.
    """
    depth_capped: bool
    """
    `true` if the runner hit the `max_depth` cap before any chunk fell below the leaf threshold. The dense range was still materialized exhaustively, so the diff is correct — just slower.
    """
    depth_max: conint(ge=0)
    """
    Maximum recursion depth reached.
    """
    leaves_materialized: conint(ge=0)
    """
    Number of leaf chunks materialized for row-by-row diff.
    """
    null_pk_rows_base: conint(ge=0)
    """
    Rows on the base side whose primary-key column was NULL. Excluded from chunk membership; counted at the root so a null-PK divergence surfaces instead of silently dropping rows.
    """
    null_pk_rows_branch: conint(ge=0)
    """
    Rows on the branch side whose primary-key column was NULL.
    """
    split_strategy: str
    """
    How the runner split the primary-key space into chunks. One of `"int_range"`, `"composite"`, `"hash_bucket"`, `"first_column"`.
    """


class PreviewColumnTypeChange(BaseModel):
    """
    One column-type change entry.
    """

    from_: str = Field(..., alias="from")
    name: str
    to: str


class PreviewDiffSummary(BaseModel):
    """
    Aggregate diff counts for [`PreviewDiffOutput`].
    """

    any_coverage_warning: bool
    """
    `true` if **any** per-model diff is either a sampled diff with `sampling_window.coverage_warning = true` or a bisection diff with `bisection_stats.depth_capped = true`. Both conditions indicate the row-level findings might be incomplete and a reviewer shouldn't infer "no change" from a clean result.
    """
    models_unchanged: conint(ge=0)
    models_unknown: conint(ge=0)
    """
    Models whose row-count delta could not be computed — the warehouse adapter or materialization strategy reported no `rows_affected` on the branch side, the base side, or both (#2032). These are counted separately from `models_unchanged`: "no recorded delta" is not the same claim as "no change", and folding the two together is exactly the false-clean report this field exists to prevent. A model here contributes `null` (not `0`) to its own `rows_added`/`rows_removed` and is excluded from `total_rows_added`/`total_rows_removed`, so those totals are a floor, not an exact count, whenever this is > 0.
    """
    models_with_changes: conint(ge=0)
    total_rows_added: conint(ge=0)
    """
    Sum of `rows_added` over models with a KNOWN delta only — models counted in `models_unknown` contribute nothing here (never `0`, which would be indistinguishable from a genuine no-op).
    """
    total_rows_changed: conint(ge=0)
    total_rows_removed: conint(ge=0)


class Kind(StrEnum):
    sampled = "sampled"


class Kind74(StrEnum):
    bisection = "bisection"


class PreviewRowSampleChange(BaseModel):
    """
    One `(column, base, branch)` triple in [`PreviewRowSample::changes`].
    """

    base_value: str
    branch_value: str
    column: str


class PreviewSamplingWindow(BaseModel):
    """
    Sampling-window metadata surfaced verbatim in the PR comment.

    `coverage_warning = true` flags that the row count outside the sampling window is non-trivial; reviewers should not infer "no change" from a clean sample if this flag is set.
    """

    coverage: str
    """
    Sampling-strategy tag. `"first_n_by_order"` is the standard PK-ordered window; `"not_yet_sampled"` is a placeholder used when the sampling layer didn't run (e.g. the structural-only fallback path).
    """
    coverage_warning: bool
    limit: conint(ge=0)
    ordered_by: str


class PreviewStructuralDiff(BaseModel):
    """
    Column-level structural diff. Mirrors the shape produced by `rocky ci-diff` at the column granularity.
    """

    added_columns: list[str] | None = None
    removed_columns: list[str] | None = None
    type_changes: list[PreviewColumnTypeChange] | None = None
    """
    One entry per column whose type changed. Each carries `name`, `from`, `to`.
    """


class PreviewRowSample(BaseModel):
    """
    One representative changed row in [`PreviewSampledRowDiff::samples`].
    """

    changes: list[PreviewRowSampleChange]
    """
    Pairs of `(column_name, base_value, branch_value)` for every column that differs on this row.
    """
    primary_key: str


class PreviewSampledRowDiff(BaseModel):
    """
    Sampled row-level diff. All counts are over the sampling window.
    """

    rows_added: conint(ge=0) | None = None
    """
    `None` — emitted as JSON `null`, deliberately NOT omitted via `skip_serializing_if` — when the row count needed to compute this delta was unavailable on the branch side, the base side, or both (an ordinary transformation run's adapter/strategy reports no `rows_affected`). `Some(0)` means a genuine, measured no-op; `null` means unmeasured. Collapsing the two into `0` is the exact defect this field exists to prevent — a full-refresh model going from 10 rows to 20 must never report `rows_added: 0` (#2032).
    """
    rows_changed: conint(ge=0)
    rows_removed: conint(ge=0) | None = None
    """
    Same absent-vs-zero contract as `rows_added`.
    """
    samples: list[PreviewRowSample] | None = None
    """
    Up to `--max-samples` (default 5) representative changed rows for human review. Pure noise when sampling found no change.
    """


class PreviewBisectionRowDiff(BaseModel):
    """
    Row-level diff produced by the checksum-bisection algorithm. All counts are exhaustive over the diffed table — no sampling window.
    """

    rows_added: conint(ge=0)
    rows_changed: conint(ge=0)
    rows_removed: conint(ge=0)
    samples: list[PreviewRowSample] | None = None
    """
    Up to `--max-samples` (default 5) representative changed rows surfaced from the leaves. Bisection samples only carry the primary key — column-level diffs are not retained on the kernel's leaf record. Empty when no rows differ.
    """


class PreviewModelDiffAlgorithm1(BaseModel):
    """
    Sampled diff — `LIMIT N` rows ordered by primary key (or first column). Carries a coverage warning when changes outside the sampling window are not surfaced.
    """

    kind: Kind
    sampled: PreviewSampledRowDiff
    sampling_window: PreviewSamplingWindow


class PreviewModelDiffAlgorithm2(BaseModel):
    """
    Checksum-bisection exhaustive diff. Walks the chunk lattice and materializes leaves for row-by-row compare. Carries [`BisectionStatsOutput`] so consumers can audit the recursion trace.
    """

    bisection_stats: BisectionStatsOutput
    diff: PreviewBisectionRowDiff
    kind: Kind74


class PreviewModelDiff(BaseModel):
    """
    Per-model diff. Combines a structural (column-level) delta with a row-level diff that was produced by either the sampled or the checksum-bisection algorithm. The active algorithm is encoded by the `kind` discriminator on [`PreviewModelDiffAlgorithm`].
    """

    algorithm: PreviewModelDiffAlgorithm1 | PreviewModelDiffAlgorithm2
    """
    Row-level diff payload, tagged by which algorithm produced it. Different models in the same run can carry different variants: a model with a single-column integer primary key runs through the bisection kernel, while a model that lacks a usable PK falls back to the sampled algorithm.
    """
    model_name: str
    structural: PreviewStructuralDiff


class PreviewDiffOutput(BaseModel):
    """
    JSON output for `rocky preview diff`.

    Combines the structural diff (column added/removed/type-changed) from the existing `rocky_core::ci_diff` machinery with a row-level diff produced by either the sampled or the checksum-bisection algorithm. Each per-model entry's `algorithm` field carries a `kind` discriminator (`"sampled"` or `"bisection"`) plus the matching payload.

    **Sampled correctness ceiling.** The sampled algorithm reads `LIMIT N` rows ordered by primary key (or first column). Changes outside that window appear as no-change unless the row count itself differs; `sampling_window.coverage_warning = true` flags that risk. **Bisection** walks the chunk lattice exhaustively over a single-column primary key; `bisection_stats.depth_capped = true` flags the rare case where the recursion bottomed out at the depth cap before reaching leaf size. `summary.any_coverage_warning` rolls both signals up.
    """

    base_note: str | None = None
    """
    Present when no run was recorded on `base_ref`: the diff is NOT computed against any stand-in (an empty summary is returned) and this note explains the absence and the remedy (#1345).
    """
    base_ref: str
    branch_name: str
    command: str
    markdown: str
    """
    Pre-rendered Markdown suitable for posting as a GitHub PR comment.
    """
    models: list[PreviewModelDiff]
    summary: PreviewDiffSummary
    version: str
