# generated by datamodel-codegen:
#   filename:  product_verify.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel


class PolicyEffect21(StrEnum):
    """
    Permit the action outright.
    """

    allow = "allow"


class PolicyEffect22(StrEnum):
    """
    Permit only after human review. The safe default posture.
    """

    require_review = "require_review"


class PolicyEffect23(StrEnum):
    """
    Refuse the action. A hard override — no `allow` overturns it.
    """

    deny = "deny"


class VerifyStatus1(StrEnum):
    """
    The frozen posture holds and every check passed.
    """

    pass_ = "pass"


class VerifyStatus2(StrEnum):
    """
    A human must edit configuration (the paste block says how).
    """

    needs_input = "needs_input"


class VerifyStatus3(StrEnum):
    """
    A check failed outright (e.g. agent apply resolves `allow`).
    """

    fail = "fail"


class ProductVerifyOutput(BaseModel):
    """
    JSON output of `rocky product verify`.
    """

    apply_effect: PolicyEffect21 | PolicyEffect22 | PolicyEffect23 | None = None
    """
    The resolved agent-apply effect, when evaluation ran.
    """
    command: str
    output_model: str
    """
    The resolved output model name.
    """
    paste_block: str | None = None
    """
    The corrected `[policy]` block to paste, on a posture `needs_input`.
    """
    product_id: str
    """
    `product:<name>`.
    """
    propose_effect: PolicyEffect21 | PolicyEffect22 | PolicyEffect23 | None = None
    """
    The resolved agent-propose effect, when evaluation ran.
    """
    reason: str
    """
    Why, in plain language.
    """
    spec_digest: str
    """
    `sha256:<hex>` over the spec's raw bytes.
    """
    status: VerifyStatus1 | VerifyStatus2 | VerifyStatus3
    """
    `pass`, `needs_input`, or `fail` — also the exit code (0 / 1 / 2).
    """
    version: str
