# generated by datamodel-codegen:
#   filename:  product_journal.schema.json

from __future__ import annotations

from pydantic import BaseModel, conint


class ProductJournalEntry(BaseModel):
    """
    One persisted fulfillment journal row, as `rocky product journal` prints it: the loop's own record of a transition, field for field.
    """

    at: str | None = None
    """
    RFC 3339 instant of the transition, when recorded.
    """
    event: str
    """
    What happened, in the loop's plain language (`spec approved`, …). A label to render, not an enum to switch on.
    """
    from_state: str | None = None
    """
    The state tag before the transition, when one existed.
    """
    idempotency_key: str | None = None
    """
    The idempotency key pinned by this event, when it pinned one.
    """
    plan_id: str | None = None
    """
    The plan involved, when the event concerns one (propose, apply).
    """
    seq: conint(ge=0)
    """
    Sequence number, also encoded in the row's store key.
    """
    spec_digest: str | None = None
    """
    The spec digest involved, when the event concerns one.
    """
    to_state: str
    """
    The state tag after the transition.
    """


class ProductJournalOutput(BaseModel):
    """
    JSON output of `rocky product journal <name>`.

    The product's fulfillment journal, whole and in append order, read through the same store function the fulfillment loop reads through. A known product with no rows is an empty journal; a product the project does not know (no spec file, no store record) is a refusal, never an empty journal.
    """

    command: str
    count: conint(ge=0)
    """
    `rows.len()`, repeated so a consumer can assert it received the whole journal.
    """
    product: str
    """
    The product name as given.
    """
    product_id: str
    """
    `product:<name>`, the store key every record of the product hangs off.
    """
    rows: list[ProductJournalEntry]
    """
    Every journal row, in append order.
    """
    version: str
