# generated by datamodel-codegen:
#   filename:  product_compile.schema.json

from __future__ import annotations

from pydantic import BaseModel


class ProductApprovalOutput(BaseModel):
    """
    The approval record, as echoed by compile/status output.
    """

    approved_at: str | None = None
    """
    RFC3339 approval instant.
    """
    approver: str
    """
    Best-effort approver identity.
    """
    snapshot_path: str
    """
    Project-root-relative path of the immutable snapshot file.
    """
    spec_digest: str
    """
    The approved `sha256:<hex>` spec digest.
    """


class ProductArtifactOutput(BaseModel):
    """
    One emitted artifact, as reported by `rocky product compile`.
    """

    path: str
    """
    Project-root-relative POSIX path.
    """
    sha256: str
    """
    `sha256:<hex>` over the committed bytes.
    """


class ProductCompileOutput(BaseModel):
    """
    JSON output of `rocky product compile`.
    """

    approval: ProductApprovalOutput | None = None
    """
    The current approval record, when one exists. Compile is a READER of the approval: when present, the snapshot bytes were re-verified against the record digest before this output was produced.
    """
    artifacts: list[ProductArtifactOutput]
    """
    The artifacts this phase committed (manifest excluded).
    """
    command: str
    manifest_path: str
    """
    Project-root-relative path of the committed lowering manifest.
    """
    output_model: str
    """
    The resolved output model name.
    """
    phase: str
    """
    Which lowering phase this run committed: `lowered_contract` (Phase A) or `merged` (Phase B).
    """
    product_id: str
    """
    `product:<name>`.
    """
    spec_digest: str
    """
    `sha256:<hex>` over the compiled spec's raw bytes.
    """
    spec_matches_approval: bool | None = None
    """
    Whether the compiled spec's digest equals the approved digest. `null` when no approval exists. `false` is not an error at compile time — it means the working spec has moved past the approval (the loop's supersession trigger).
    """
    spec_path: str
    """
    Project-root-relative spec path.
    """
    version: str
