# generated by datamodel-codegen:
#   filename:  project.schema.json

from __future__ import annotations

from pydantic import BaseModel, conint


class ProjectAdapterOutput(BaseModel):
    """
    One adapter of the bound config.
    """

    adapter_type: str
    """
    The adapter's `type` as configured (`duckdb`, `databricks`, …).
    """
    name: str


class ProjectDiagnosticsOutput(BaseModel):
    """
    The compile's diagnostics, counted. All zero before the first compile.
    """

    has_errors: bool
    total: conint(ge=0)
    warnings: conint(ge=0)


class ProjectPipelineOutput(BaseModel):
    """
    One pipeline of the bound config.
    """

    name: str
    pipeline_type: str
    """
    `replication`, `transformation`, `quality`, `snapshot` or `load`.
    """


class ProjectRunOutput(BaseModel):
    """
    The newest run, as the dashboard summarised it.
    """

    finished_at: str
    """
    RFC 3339.
    """
    models_executed: conint(ge=0)
    run_id: str
    started_at: str
    """
    RFC 3339.
    """
    status: str
    """
    The run's recorded status (`Success`, `PartialFailure`, `Failure`, …).
    """
    trigger: str
    """
    What started it (`Manual`, `Schedule`, `Webhook`, …).
    """


class ProjectOutput(BaseModel):
    """
    The project a sidecar serves, for `GET /api/v1/project`: what the server-rendered dashboard at `/` used to show, as a typed payload.

    Server-only, no CLI twin. Bounded by construction: names of pipelines and adapters (a handful), counts for models and diagnostics, and the one newest run. The model names are on `GET /api/v1/models` and the DAG.
    """

    adapters: list[ProjectAdapterOutput]
    """
    Every `[adapter.<name>]`, in config order.
    """
    config_error: str | None = None
    """
    Why the config could not be loaded, when it could not. The lists below are then empty.
    """
    config_path: str | None = None
    """
    The bound config's path; `null` when the sidecar has none.
    """
    diagnostics: ProjectDiagnosticsOutput
    """
    The compile's diagnostics, counted.
    """
    last_run: ProjectRunOutput | None = None
    """
    The newest run in the state store the server resolved; `null` when none was recorded.
    """
    models_compiled: conint(ge=0) | None = None
    """
    Models in the in-memory compile result; `null` before the first compile finishes.
    """
    name: str
    """
    The directory the bound `rocky.toml` lives in, or `rocky` when no config is bound.
    """
    pipelines: list[ProjectPipelineOutput]
    """
    Every `[pipeline.<name>]`, in config order.
    """
