# generated by datamodel-codegen:
#   filename:  replay.schema.json

from __future__ import annotations

from pydantic import BaseModel, conint


class ReplayModelOutput(BaseModel):
    """
    A single model execution inside a replayed run.
    """

    bytes_scanned: conint(ge=0) | None = None
    """
    Adapter-reported bytes figure used for cost accounting. This is the *billing-relevant* number per adapter, not literal scan volume:

    - **BigQuery:** `totalBytesBilled` — includes the 10 MB per-query minimum floor; matches the BigQuery console's "Bytes billed" field, **not** "Bytes processed". - **Databricks:** when populated, byte count from the statement-execution manifest (`total_byte_count`); `None` today until the manifest plumbing lands. - **Snowflake:** `None` — deferred by design (QUERY_HISTORY round-trip cost; Snowflake cost is duration × DBU, not bytes-driven). - **DuckDB:** `None` — no billed-bytes concept.
    """
    bytes_written: conint(ge=0) | None = None
    """
    Adapter-reported bytes-written figure. Currently `None` on every adapter — BigQuery doesn't expose a bytes-written figure for query jobs, and the Databricks / Snowflake paths haven't wired it yet.
    """
    duration_ms: conint(ge=0)
    finished_at: str
    model_name: str
    rows_affected: conint(ge=0) | None = None
    sql_hash: str
    started_at: str
    status: str


class ReplayOutput(BaseModel):
    """
    JSON output for `rocky replay <run_id|latest>`.

    Inspection-only surface over the state store's [`RunRecord`]: shows every model that ran, with the SQL hash, row counts, bytes, and timings captured at the time. Re-execution (with pinned inputs + content-addressed writes) is deferred to a follow-up when the Arc-1 storage path arrives.
    """

    command: str
    config_hash: str
    finished_at: str
    models: list[ReplayModelOutput]
    run_id: str
    started_at: str
    status: str
    trigger: str
    version: str
