# generated by datamodel-codegen:
#   filename:  retention_status.schema.json

from __future__ import annotations

from pydantic import BaseModel, conint


class ModelRetentionStatus(BaseModel):
    """
    Per-model retention declaration + (eventually) warehouse-observed value.

    - `configured_days` is `None` when the model's sidecar has no `retention` key. - `warehouse_days` is populated by the (v2) `--drift` probe via `SHOW TBLPROPERTIES` on Databricks or `SHOW PARAMETERS ... FOR TABLE` on Snowflake. Always `None` in v1. - `in_sync` is `true` iff `configured_days == warehouse_days`, or both are `None`. A model with no configured retention is never flagged as out-of-sync.
    """

    configured_days: conint(ge=0) | None = None
    in_sync: bool
    model: str
    warehouse_days: conint(ge=0) | None = None


class RetentionStatusOutput(BaseModel):
    """
    JSON output for `rocky retention-status`.

    Reports which models declare a `retention = "<N>[dy]"` sidecar value and — when `--drift` is set in a future wave — whether the warehouse's current retention matches. Today `warehouse_days` is always `None` because the probe is deferred to v2; the schema is stable so v2 can populate the field without a JSON shape break.
    """

    command: str
    models: list[ModelRetentionStatus]
    version: str
