# generated by datamodel-codegen:
#   filename:  rocky_product.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict


class ColumnSpec(BaseModel):
    """
    One declared output column.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    """
    Column name; must be a bare identifier.
    """
    nullable: bool
    """
    Whether the column may hold nulls.
    """
    type: str
    """
    Rocky type name, optionally parameterized.
    """


class FreshnessSeverity1(StrEnum):
    """
    Staleness is reported as a failure.
    """

    error = "error"


class FreshnessSeverity2(StrEnum):
    """
    Staleness is reported as a warning.
    """

    warning = "warning"


class FreshnessSpec(BaseModel):
    """
    Declared freshness: the lag budget plus the column that witnesses it.

    `time_column` is required. Without it the observation-phase staleness check (`MAX(time_column)` against the budget) has nothing to read, and freshness would be a claim with no witness.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    max_lag: str
    """
    Lag budget in the duration grammar (`"24h"`).
    """
    severity: FreshnessSeverity1 | FreshnessSeverity2 | None = None
    """
    Optional severity for the staleness report.
    """
    time_column: str
    """
    The timestamp column the staleness check reads.
    """


class OutputSpec(BaseModel):
    """
    The one output model and the guarantees around it.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    checks: list[str] | None = None
    """
    Opaque SQL boolean expressions, checked by the engine.
    """
    classifications: dict[str, str] | None = None
    """
    Column classification tags.

    Held in an insertion-ordered map because the sidecar merge must be able to preserve an order it is given. The parser fills it in sorted key order: `toml::Value` hands back a sorted map, so document order is not recoverable here without span-based parsing. Sorted is deterministic, which is what byte-stable output needs; recovering true document order belongs with the merge that actually rewrites a human's file.
    """
    columns: list[ColumnSpec]
    """
    Every declared column.
    """
    freshness: FreshnessSpec | None = None
    """
    Optional freshness declaration.
    """
    grain: list[str]
    """
    The columns that identify one row.
    """
    model: str | None = None
    """
    Model name; defaults to the product name when omitted.
    """


class SourceSpec(BaseModel):
    """
    Grounding sources: exact `catalog.schema.table` triples only.

    v0 has no globs and no `include` selectors, because no engine counterpart exists. An `include` key is refused as an unknown key; a glob smuggled inside `tables` is refused here.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    tables: list[str]
    """
    One or more exact table references.
    """


class TrustSpec(BaseModel):
    """
    The trust dial. `propose_only` is the only v0 value.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    agent: str
    """
    How much the agent may do unattended.
    """


class ProductSpec(BaseModel):
    """
    The `[product]` table.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    intent: str
    """
    Plain-language statement of what the product is for.
    """
    name: str
    """
    Product name; names the state directory and the default model.
    """
    output: OutputSpec
    """
    What the product must produce.
    """
    source: SourceSpec
    """
    Where the data comes from.
    """
    trust: TrustSpec
    """
    How much the agent is trusted.
    """


class SpecFile(BaseModel):
    """
    The whole document: an optional version pin plus `[product]`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    product: ProductSpec
    """
    The product declaration.
    """
    spec_version: int | None = None
    """
    Optional schema-version pin.
    """
