# generated by datamodel-codegen:
#   filename:  run.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, conint


class AnomalyOutput(BaseModel):
    """
    Row count anomaly detected by historical baseline comparison.
    """

    baseline_avg: float
    current_count: conint(ge=0)
    deviation_pct: float
    reason: str
    table: str


class AttemptRecord(BaseModel):
    """
    One attempt at materializing a model, recorded when the run loop's classified-retry layer is active.

    A model that succeeds on the first try records a single attempt; a model that failed transiently and was re-run records one entry per attempt, the last of which is the outcome that stuck. The trail is **execution metadata** — it lives on [`ModelExecution`] alongside the identity hashes, never inside them, so a retried-then-succeeded execution stays byte-indistinguishable downstream from a first-try success (same `recipe_hash` / `input_hash` / output hash).

    Reused verbatim on `MaterializationOutput.attempts` (the run-JSON surface), so it derives `JsonSchema`; that is the one attempt type on both the wire and the state record.
    """

    attempt: conint(ge=0)
    """
    1-based attempt index. Attempt 1 is the first try; 2+ are retries.
    """
    backoff_ms: conint(ge=0) | None = None
    """
    Milliseconds slept as backoff *after* this attempt before the next retry. `None` on the final (kept) attempt and on any attempt that was not followed by a retry.
    """
    duration_ms: conint(ge=0)
    """
    Wall-clock duration of this attempt, in milliseconds.
    """
    error: str | None = None
    """
    The failure message (truncated), for a failed attempt; `None` on success.
    """
    failure_class: str | None = None
    """
    The run-loop [`FailureClass`](crate::failure_class::FailureClass) label (`"transient"` / `"permanent"` / `"unknown"`) for a failed attempt; `None` on a successful attempt.
    """
    outcome: str
    """
    `"success"` or `"failed"`.
    """
    transient_kind: str | None = None
    """
    The transient sub-kind label (`"network"`, `"timeout"`, …) when the failure was transient; `None` otherwise.
    """


class BudgetBreachOutput(BaseModel):
    """
    One budget breach surfaced on [`RunOutput::budget_breaches`].

    Kept as a CLI-side struct (rather than re-using [`rocky_core::config::BudgetBreach`]) so the JSON schema lives alongside the other `rocky run` output types. The fields mirror `BudgetBreach` one-to-one.
    """

    actual: float
    limit: float
    limit_type: str
    """
    Which limit was breached: `"max_usd"`, `"max_duration_ms"`, or `"max_bytes_scanned"`.
    """


class ContainedModelOutput(BaseModel):
    """
    One model withheld from a run because an upstream failed (or was itself withheld) and failure-containment continued the disjoint subgraphs.

    This is the blast radius of a failure — the run's `errors[]` name the root cause(s). A withheld model was **not built** this run: its target was left untouched (never rebuilt on a failed upstream's stale/missing output). This is model-graph containment, distinct from the quality pipeline's row-level `quarantine` surface.
    """

    blocked_by: list[str]
    """
    The failed-or-withheld upstream(s) that reach this model — its direct poisoned dependencies. The run's `errors[]` carry the root-cause detail.
    """
    model: str
    """
    The withheld model's name (matches the model entry in the project DAG).
    """
    unblock_hint: str
    """
    Operator hint: resolve the named upstream failure(s), then re-run.
    """


class DriftActionOutput(BaseModel):
    action: str
    reason: str
    table: str


class DriftSummary(BaseModel):
    actions_taken: list[DriftActionOutput]
    tables_checked: conint(ge=0)
    tables_drifted: conint(ge=0)


class ExcludedTableOutput(BaseModel):
    """
    A table that the discovery adapter reported but that is missing from the source warehouse, so the run skipped it. Tracked separately from `errors` because it is not a runtime failure — the row never made it past the pre-flight existence check.
    """

    asset_key: list[str]
    """
    Dagster-style asset key path (`[source_type, ...components, table]`).
    """
    reason: str
    """
    Why the table was excluded. Currently always `"missing_from_source"` but kept as a free-form field so future causes (disabled, sync_paused, ...) can be added without a schema break.
    """
    source_schema: str
    """
    Source schema the table was expected to live in.
    """
    table_name: str
    """
    Bare table name as reported by the discovery adapter.
    """


class ExecutionSummary(BaseModel):
    """
    Summary of execution parallelism and throughput.
    """

    adaptive_concurrency: bool | None = None
    """
    Whether adaptive concurrency (AIMD throttle) was enabled for this run.
    """
    concurrency: conint(ge=0)
    final_concurrency: conint(ge=0) | None = None
    """
    Final concurrency level at end of run (may differ from initial if adaptive concurrency adjusted it). Only present when adaptive concurrency is enabled.
    """
    rate_limits_detected: conint(ge=0) | None = None
    """
    Number of rate-limit signals (HTTP 429 / UC_REQUEST_LIMIT_EXCEEDED) that triggered concurrency reduction. Only present when adaptive concurrency is enabled.
    """
    tables_failed: conint(ge=0)
    """
    Tables that failed during the **execution phase** — copy or runtime failures while materializing. This does **not** include models excluded before execution started (for example, a model that failed to compile); those are counted only in the top-level `RunOutput.tables_failed`. For overall run pass/fail, read the top-level `tables_failed` / `status`, not this `execution.tables_failed`.
    """
    tables_processed: conint(ge=0)


class FailureKind1(StrEnum):
    """
    TCP / TLS / DNS / connection-establishment failure.
    """

    connection_failed = "connection-failed"


class FailureKind2(StrEnum):
    """
    Credentials rejected, token expired or otherwise invalid.
    """

    auth_failed = "auth-failed"


class FailureKind3(StrEnum):
    """
    Warehouse rejected the SQL — syntax error, schema mismatch, missing permission, semantic analysis failure.
    """

    query_rejected = "query-rejected"


class FailureKind4(StrEnum):
    """
    Retry-worthy failure — 5xx, network glitch, statement aborted by a transient warehouse condition.
    """

    transient = "transient"


class FailureKind5(StrEnum):
    """
    Rate limit hit or a configured budget cap (retry budget, circuit breaker, account-level quota).
    """

    quota_exceeded = "quota-exceeded"


class FailureKind6(StrEnum):
    """
    Requested catalog / schema / table not present.
    """

    not_found = "not-found"


class FailureKind7(StrEnum):
    """
    A model failed to compile (parse / type-check / contract diagnostic) before any SQL was issued — e.g. a `time_interval` model whose `time_column` is absent from its SELECT output (E020). The model never reached the warehouse; the run surfaces it as a failure instead of silently skipping it.
    """

    compile_error = "compile-error"


class FailureKind8(StrEnum):
    """
    Fallback when the failure could not be classified — e.g. errors raised outside the connector layer that reach this struct type-erased through `anyhow::Error`.
    """

    unknown = "unknown"


class MaterializationMetadata(BaseModel):
    column_count: conint(ge=0) | None = None
    """
    Number of columns in the materialized table's typed schema. Populated for derived models (where the compiler resolved a typed schema); `None` for source-replication tables that inherit their schema from upstream.
    """
    compile_time_ms: conint(ge=0) | None = None
    """
    Compile time in milliseconds for the model that produced this materialization. Populated only for derived models. Mirrors the relevant slice of `PhaseTimings.total_ms`.
    """
    sql_hash: str | None = None
    """
    Short hash (16 hex chars) of the generated SQL string. Lets orchestrators detect "what changed?" between runs without diffing full SQL bodies. Computed via `xxh3_64` of the canonical SQL the engine sent to the warehouse.
    """
    strategy: str
    target_table_full_name: str | None = None
    """
    Fully-qualified target table identifier in `catalog.schema.table` format. Useful for click-through links to the warehouse UI from the Dagster asset detail page. Always set when the materialization targets a known table.
    """
    watermark: AwareDatetime | None = None


class MetricsSnapshot(BaseModel):
    """
    Serializable metrics summary for JSON output.
    """

    anomalies_detected: conint(ge=0)
    error_rate_pct: float
    query_duration_max_ms: conint(ge=0)
    query_duration_p50_ms: conint(ge=0)
    query_duration_p95_ms: conint(ge=0)
    retries_attempted: conint(ge=0)
    retries_succeeded: conint(ge=0)
    statements_executed: conint(ge=0)
    table_duration_max_ms: conint(ge=0)
    table_duration_p50_ms: conint(ge=0)
    table_duration_p95_ms: conint(ge=0)
    tables_failed: conint(ge=0)
    tables_processed: conint(ge=0)


class ModelCostEntry(BaseModel):
    """
    Per-model cost attribution entry inside [`RunCostSummary`].
    """

    asset_key: list[str]
    """
    Asset key path for the model this entry covers.
    """
    cost_usd: float | None = None
    """
    Observed cost for this materialization. `None` when the adapter type isn't billed or the formula couldn't be computed.
    """
    duration_ms: conint(ge=0)


class ModelDecision1(StrEnum):
    """
    The model was (re-)materialized this run — its SQL ran (or its content-addressed write executed).
    """

    build = "build"


class ModelDecision2(StrEnum):
    """
    The `--skip-unchanged` gate proved the model's logic and upstream data unchanged since the last successful build and skipped re-materialization.
    """

    skip = "skip"


class ModelDecision3(StrEnum):
    """
    A content-addressed model pointed-to a prior run's already-written parquet via a zero-copy commit instead of executing its SQL.
    """

    reused = "reused"


class ModelDecisionOutput(BaseModel):
    """
    One per-model decision entry on [`RunOutput::model_decisions`].

    Surfaces the skip/build/reuse verdict the engine reached for a single transformation model, plus a short human-readable reason that mirrors the gate's actual decision point (never re-derived — threaded from the evaluation result). Orchestrators (Dagster) and the VS Code extension use it to explain *why* a model ran, was skipped, or was reused.
    """

    decision: ModelDecision1 | ModelDecision2 | ModelDecision3
    """
    What the engine decided for this model.
    """
    model: str
    """
    The model's name (matches the model entry in the project DAG).
    """
    reason: str
    """
    Short human-readable justification reflecting the exact decision the gate made (e.g. "logic and upstream data unchanged since last build", "not skip-eligible", "upstream data may have changed", "reused prior run's bytes (strong proof)").
    """


class OverrideWarningOutput(BaseModel):
    """
    Soft warning surfaced on [`RunOutput::override_warnings`] when an override rule matched no tables this run.

    Distinct kinds let orchestrators (Dagster) branch on cause without parsing free-form messages.
    """

    connector: str | None = None
    """
    Echo of `match.connector` from the rule, for cross-reference.
    """
    kind: str
    """
    Coarse kind: `"zero_match"` (rule matched no pair at all) or `"connector_match_empty"` (the connector half of the match resolved nothing).
    """
    message: str
    """
    Human-readable explanation, for logs and Dagster UI rendering.
    """
    rule_index: conint(ge=0)
    """
    Position of the rule in `[[table_overrides]]`, 0-based — same index the validator's error messages use.
    """
    table: str | None = None
    """
    Echo of `match.table` from the rule, for cross-reference.
    """


class PartitionInfo(BaseModel):
    """
    Partition window information for a single `time_interval` materialization.

    `key` is the canonical Rocky partition key (e.g. `"2026-04-07"` for daily; `"2026-04-07T13"` for hourly). `start` / `end` are the half-open `[start, end)` window the SQL substituted for `@start_date` / `@end_date`. `batched_with` lists any additional partition keys that were merged into this batch when `batch_size > 1` — empty for the default one-partition-per-statement case.
    """

    batched_with: list[str] | None = None
    end: AwareDatetime
    key: str
    start: AwareDatetime


class PartitionSummary(BaseModel):
    """
    Per-model summary of `time_interval` partition execution.

    One entry per partitioned model touched by the run. Lets dagster-rocky (and other orchestrators) display per-model partition stats without re-counting the per-partition `MaterializationOutput.partition` entries.
    """

    model: str
    partitions_failed: conint(ge=0)
    partitions_planned: conint(ge=0)
    partitions_skipped: conint(ge=0) | None = None
    """
    Partitions that were already `Computed` in the state store and skipped by the runtime (currently always 0; reserved for the `--missing` change-detection optimization).
    """
    partitions_succeeded: conint(ge=0)


class PermissionSummary(BaseModel):
    catalogs_created: conint(ge=0)
    grants_added: conint(ge=0)
    grants_revoked: conint(ge=0)
    schemas_created: conint(ge=0)


class QuarantineOutput(BaseModel):
    """
    Row-quarantine outcome for a single table processed by the quality pipeline. Emitted when `[pipeline.x.checks.quarantine]` is enabled and the table has at least one error-severity row-level assertion that lowers to a boolean predicate.

    Row counts are reported when the warehouse adapter supplies them. Adapters that cannot count rows written by a `CREATE OR REPLACE TABLE` leave the counts as `None`.
    """

    asset_key: list[str]
    """
    Dagster-style asset key path (`[catalog, schema, table]`) of the source table the quarantine acted on.
    """
    error: str | None = None
    """
    Error message from the first failing statement, if any.
    """
    mode: str
    """
    Quarantine mode that was applied. One of `"split"`, `"tag"`, `"drop"` (matches [`rocky_core::config::QuarantineMode`]).
    """
    ok: bool
    """
    `true` when every quarantine statement executed successfully. `false` means a partial failure — inspect `error` for details.
    """
    quarantine_table: str | None = None
    """
    Fully-qualified name of the `__quarantine` output table. Empty for `mode = "drop"` (failing rows discarded) and `mode = "tag"`.
    """
    quarantined_rows: conint(ge=0) | None = None
    """
    Number of rows in the `__quarantine` output, when the adapter can report it.
    """
    valid_rows: conint(ge=0) | None = None
    """
    Number of rows in the `__valid` output, when the adapter can report it.
    """
    valid_table: str | None = None
    """
    Fully-qualified `catalog.schema.table` name of the `__valid` output table. Empty for `mode = "tag"` (source is rewritten in place).
    """


class RunCostSummary(BaseModel):
    """
    Aggregate cost attribution for a `rocky run` invocation.

    The run finalizer walks every [`MaterializationOutput`] in [`RunOutput::materializations`], computes a per-model dollar cost using [`rocky_core::cost::compute_observed_cost_usd`], and stuffs the totals here. Consumers (Dagster, custom dashboards) can then read either the per-model breakdown or the run total without re-deriving the cost model themselves.
    """

    adapter_type: str
    """
    Adapter type the cost formula was parameterised against, for audit. Values mirror `AdapterConfig.type`: "databricks", "snowflake", "bigquery", "duckdb".
    """
    per_model: list[ModelCostEntry]
    """
    Per-model cost attribution, ordered as in [`RunOutput::materializations`].
    """
    total_bytes_scanned: conint(ge=0) | None = None
    """
    Sum of every per-model `bytes_scanned` that produced a number. `None` when no materialization reported a byte count (the non-BigQuery adapters today, which still inherit the default stub on `WarehouseAdapter::execute_statement_with_stats`). Surfaced so consumers — and the `[budget]` `max_bytes_scanned` gate — can read scan volume without re-walking [`RunOutput::materializations`].
    """
    total_cost_usd: float | None = None
    """
    Sum of every per-model `cost_usd` that produced a number. `None` when no materialization produced a cost.
    """
    total_duration_ms: conint(ge=0)
    """
    Wall-clock time summed across every materialization. Separate from [`RunOutput::duration_ms`] (which includes setup / governance overhead) so budget enforcement can target model-compute time specifically.
    """


class RunStatus1(StrEnum):
    """
    Status of a pipeline run.

    `Success` / `PartialFailure` / `Failure` cover the terminal outcomes of a run that actually executed. `SkippedIdempotent` / `SkippedInFlight` are the short-circuit outcomes of `rocky run --idempotency-key` — see [`crate::idempotency`].
    """

    Success = "Success"
    PartialFailure = "PartialFailure"
    Failure = "Failure"


class RunStatus2(StrEnum):
    """
    The run was short-circuited because an idempotency key already mapped to a prior completed run. No work was done.
    """

    SkippedIdempotent = "SkippedIdempotent"


class RunStatus3(StrEnum):
    """
    The run was short-circuited because another caller held the idempotency key's in-flight claim. No work was done.
    """

    SkippedInFlight = "SkippedInFlight"


class TableErrorOutput(BaseModel):
    """
    Error from a table that failed during parallel processing.
    """

    asset_key: list[str]
    cooldown_seconds: conint(ge=0) | None = None
    """
    Backoff hint in whole seconds. Populated by adapters whose failure mode carries a known cooldown — currently only the Databricks and Snowflake warehouse adapters when their shared circuit breaker trips (and the breaker was configured with `retry.circuit_breaker_recovery_timeout_secs`). Orchestrators (Dagster, etc.) use it as a `retry_after` hint when scheduling a delayed re-run. Mirrors the source-side shape on [`FailedSourceOutput::cooldown_seconds`]. Absent for failure classes without an engine-supplied hint.
    """
    error: str
    failure_kind: (
        FailureKind1
        | FailureKind2
        | FailureKind3
        | FailureKind4
        | FailureKind5
        | FailureKind6
        | FailureKind7
        | FailureKind8
        | None
    ) = "unknown"
    """
    Coarse classification of the failure so orchestrators can branch on kind (retry, page, surface) without parsing `error`. Defaults to [`FailureKind::Unknown`] for errors that reached the output layer type-erased.
    """


class TestSeverity7(StrEnum):
    """
    Test failure is a hard error — pipeline fails.
    """

    error = "error"


class TestSeverity8(StrEnum):
    """
    Test failure is a warning — pipeline continues.
    """

    warning = "warning"


class CheckResult1(BaseModel):
    """
    Row count comparison between source and target tables.
    """

    name: str
    passed: bool
    severity: TestSeverity7 | TestSeverity8 | None = "error"
    """
    Severity reported when the check fails. `error` causes the quality pipeline to exit non-zero (subject to `fail_on_error`); `warning` is advisory and does not fail the run.
    """
    source_count: conint(ge=0)
    target_count: conint(ge=0)


class CheckResult2(BaseModel):
    """
    Column presence comparison between source and target schemas.
    """

    name: str
    passed: bool
    severity: TestSeverity7 | TestSeverity8 | None = "error"
    """
    Severity reported when the check fails. `error` causes the quality pipeline to exit non-zero (subject to `fail_on_error`); `warning` is advisory and does not fail the run.
    """
    extra: list[str]
    missing: list[str]


class CheckResult3(BaseModel):
    """
    Data freshness measured as lag from the max timestamp to now.
    """

    name: str
    passed: bool
    severity: TestSeverity7 | TestSeverity8 | None = "error"
    """
    Severity reported when the check fails. `error` causes the quality pipeline to exit non-zero (subject to `fail_on_error`); `warning` is advisory and does not fail the run.
    """
    lag_seconds: conint(ge=0)
    threshold_seconds: conint(ge=0)


class CheckResult4(BaseModel):
    """
    Null rate for a specific column, sampled via TABLESAMPLE.
    """

    name: str
    passed: bool
    severity: TestSeverity7 | TestSeverity8 | None = "error"
    """
    Severity reported when the check fails. `error` causes the quality pipeline to exit non-zero (subject to `fail_on_error`); `warning` is advisory and does not fail the run.
    """
    column: str
    null_rate: float
    threshold: float


class CheckResult5(BaseModel):
    """
    Row-level assertion evaluated via the `TestDecl` surface (`not_null`, `unique`, `accepted_values`, `relationships`, `expression`, `row_count_range`).

    `failing_rows` is the count of rows that violated the assertion; `0` means the check passed. For `row_count_range`, `failing_rows` stores the observed row count (the caller asserts pass/fail via the configured bounds).
    """

    name: str
    passed: bool
    severity: TestSeverity7 | TestSeverity8 | None = "error"
    """
    Severity reported when the check fails. `error` causes the quality pipeline to exit non-zero (subject to `fail_on_error`); `warning` is advisory and does not fail the run.
    """
    column: str | None = None
    """
    Column under test, when the assertion has one.
    """
    failing_rows: conint(ge=0)
    """
    Number of failing rows (0 when passed). For `row_count_range`, this stores the observed total row count.
    """
    kind: str
    """
    Assertion kind — the `TestType` discriminant serialized as snake_case (e.g., `"not_null"`, `"accepted_values"`).
    """


class CheckResult6(BaseModel):
    """
    User-defined SQL check evaluated against a threshold.
    """

    name: str
    passed: bool
    severity: TestSeverity7 | TestSeverity8 | None = "error"
    """
    Severity reported when the check fails. `error` causes the quality pipeline to exit non-zero (subject to `fail_on_error`); `warning` is advisory and does not fail the run.
    """
    query: str
    result_value: conint(ge=0)
    threshold: conint(ge=0)


class CheckResult7(BaseModel):
    """
    Cross-source overlap: the same business key found in more than one sibling source feeding a shared consolidation target.
    """

    name: str
    passed: bool
    severity: TestSeverity7 | TestSeverity8 | None = "error"
    """
    Severity reported when the check fails. `error` causes the quality pipeline to exit non-zero (subject to `fail_on_error`); `warning` is advisory and does not fail the run.
    """
    contributing_tables: list[str]
    """
    Fully-qualified sibling tables that were compared.
    """
    overlap_count: conint(ge=0)
    """
    Count of distinct keys that appear in more than one sibling table.
    """
    sample: list[str]
    """
    Bounded sample of overlapping key values (stringified) for triage.
    """


class MaterializationOutput(BaseModel):
    asset_key: list[str]
    attempts: list[AttemptRecord] | None = None
    """
    The classified-retry attempt trail for this materialization: one [`AttemptRecord`](rocky_core::state::AttemptRecord) per try. Empty (and omitted from JSON) for a clean first-try success — the run loop only stamps a trail once a retry actually happened, so a non-retried build's output stays byte-identical to before this layer shipped. [`RunOutput::to_run_record`] copies this verbatim onto the persisted `ModelExecution.attempts` — one attempt type on both the wire and the state record.
    """
    bytes_scanned: conint(ge=0) | None = None
    """
    Adapter-reported bytes figure used for cost accounting, summed across all statements executed for this materialization. This is the *billing-relevant* number per adapter, not literal scan volume — so anyone comparing this to a warehouse console should know which column lines up.

    - **BigQuery:** `statistics.query.totalBytesBilled` (with the 10 MB per-query minimum already applied) — matches the BigQuery console's "Bytes billed" field, **not** "Bytes processed". Fed straight into [`rocky_core::cost::compute_observed_cost_usd`] to produce `cost_usd`. - **Databricks:** when populated, byte count from the statement-execution manifest (`total_byte_count`); `None` today until the manifest plumbing lands. - **Snowflake:** `None` — deferred by design (QUERY_HISTORY round-trip cost; Snowflake cost is duration × DBU, not bytes-driven). - **DuckDB:** `None` — no billed-bytes concept.
    """
    bytes_written: conint(ge=0) | None = None
    """
    Adapter-reported bytes-written figure, summed across all statements. Currently `None` on every adapter — BigQuery doesn't expose a bytes-written figure for query jobs, and the Databricks / Snowflake paths haven't wired it yet. Reserved so a future release can populate it without a schema break.
    """
    cost_usd: float | None = None
    """
    Observed dollar cost of this materialization, computed post-hoc from the adapter-appropriate formula (duration × DBU rate for Databricks/Snowflake, bytes × $/TB for BigQuery, zero for DuckDB). `None` when the warehouse type isn't billed or the adapter didn't report the inputs the formula needs. Populated by the run finalizer via `rocky_core::cost::compute_observed_cost_usd`.
    """
    duration_ms: conint(ge=0)
    job_ids: list[str] | None = None
    """
    Warehouse-side job identifiers for the SQL statements rocky issued to materialize this output. Populated for adapters whose REST API surfaces a job reference per statement (BigQuery today via `jobReference.jobId`).

    Useful for cross-checking rocky's reported figures against the warehouse's own statistics — e.g., feeding a job ID into `bq show -j <id>` and comparing `totalBytesBilled` to [`Self::bytes_scanned`]. Empty `Vec` for adapters that don't surface a job concept (DuckDB) or haven't wired it yet (Databricks, Snowflake).
    """
    metadata: MaterializationMetadata
    partition: PartitionInfo | None = None
    """
    Partition window this materialization targeted, present only when the model's strategy is `time_interval`. `None` for unpartitioned strategies (full_refresh, incremental, merge).
    """
    rows_copied: conint(ge=0) | None = None
    started_at: AwareDatetime
    """
    Wall-clock timestamp captured at the moment the engine began executing this model. Used by `RunOutput::to_run_record` to build accurate per-model windows on the persisted `ModelExecution` — replaces the prior lossy reconstruction (`finished_at - duration`) that mis-ordered parallel runs. `finished_at` is derived as `started_at + duration_ms`; keeping one source of truth avoids drift between the two.
    """
    tenant: str | None = None
    """
    Tenant this materialization is attributed to, taken from the discover-time schema-pattern `{tenant}` component. Present only for replication pipelines whose schema pattern declares a `{tenant}` placeholder; transformation / `time_interval` models and non-tenant patterns leave it `None`. Carried onto the persisted `rocky_core::state::ModelExecution` by [`RunOutput::to_run_record`] so `rocky cost --by tenant` can roll per-model cost up to a tenant dimension. Omitted from JSON when `None` so non-tenant outputs stay byte-identical.
    """


class TableCheckOutput(BaseModel):
    asset_key: list[str]
    checks: list[
        CheckResult1
        | CheckResult2
        | CheckResult3
        | CheckResult4
        | CheckResult5
        | CheckResult6
        | CheckResult7
    ]


class RunOutput(BaseModel):
    """
    JSON output for `rocky run`.
    """

    anomalies: list[AnomalyOutput] | None = None
    budget_breaches: list[BudgetBreachOutput] | None = None
    """
    Budget breaches detected at end of run. Empty when no `[budget]` block is configured or all configured limits were respected. Each breach is also emitted as a `budget_breach` [`rocky_observe::events::PipelineEvent`] and fires the `on_budget_breach` hook so subscribers see them live.
    """
    check_results: list[TableCheckOutput]
    command: str
    contained: list[ContainedModelOutput] | None = None
    """
    Models withheld this run because an upstream failed (or was itself withheld) and `[resilience] contain_failures` continued the disjoint subgraphs — the blast radius of the failures named in `errors[]`. Empty (and omitted) for a run that did not withhold anything: the default fail-fast run, and any successful run, record nothing here.
    """
    cost_summary: RunCostSummary | None = None
    """
    Aggregate cost attribution across every materialization in this run (per-model entries + run totals). `None` for DuckDB-only pipelines or when no materializations produced a cost number.
    """
    drift: DriftSummary
    duration_ms: conint(ge=0)
    errors: list[TableErrorOutput] | None = None
    excluded_tables: list[ExcludedTableOutput] | None = None
    """
    Tables that the discovery adapter reported as enabled but that do not exist in the source warehouse (e.g. Fivetran has them configured but hasn't synced them, or they carry the `do_not_alter__` broken-table marker). Surfaced so orchestrators can flag the gap in their UIs instead of silently dropping the assets.
    """
    execution: ExecutionSummary
    filter: str
    idempotency_key: str | None = None
    """
    The `--idempotency-key` value this run was invoked with, echoed back for operator cross-reference in logs and `rocky history`. `None` for runs that didn't pass the flag.
    """
    interrupted: bool
    """
    `true` when the run was cancelled by a SIGINT (Ctrl-C). Surfaced so orchestrators can distinguish "user interrupted" from "run failed". Tables that hadn't reached `Success` or `Failed` at interrupt time are recorded as `TableStatus::Interrupted` in the state store. Always serialised (even when `false`) so consumers don't have to treat its absence specially.
    """
    materializations: list[MaterializationOutput]
    metrics: MetricsSnapshot | None = None
    model_decisions: list[ModelDecisionOutput] | None = None
    """
    Per-model build/skip/reuse decision + reason, surfaced for transformation runs so orchestrators can explain *why* each model ran, was skipped, or was reused. Populated only when the `--skip-unchanged` gate is active or `[reuse]` is enabled; empty (and omitted) for a default run, which stays byte-identical.
    """
    override_warnings: list[OverrideWarningOutput] | None = None
    """
    Soft warnings raised by the per-table override resolver — one entry per `[[table_overrides]]` rule that matched zero `(connector, table)` pairs this run, or whose connector half resolved nothing. Discovery-time-only — the pipeline runs to completion regardless. Empty for runs whose pipeline declares no overrides.
    """
    partition_summaries: list[PartitionSummary] | None = None
    """
    Per-model partition execution summaries, present only when the run touched one or more `time_interval` models. Empty for runs that didn't execute any partitioned models.
    """
    permissions: PermissionSummary
    pipeline_type: str | None = None
    """
    Pipeline type that was executed (e.g., "replication").
    """
    quarantine: list[QuarantineOutput] | None = None
    """
    Row-quarantine outcomes — one entry per table the quality pipeline quarantined. Empty for runs that did not use `[pipeline.x.checks.quarantine]`.
    """
    resumed_from: str | None = None
    shadow: bool | None = None
    """
    True when running in shadow mode (targets rewritten).
    """
    skipped_by_run_id: str | None = None
    """
    Prior run whose idempotency key deflected this call, or the run currently holding the in-flight claim. Populated only when `status` is `skipped_idempotent` or `skipped_in_flight`.
    """
    status: RunStatus1 | RunStatus2 | RunStatus3
    """
    Terminal status of the run. `success` / `partial_failure` / `failure` match the lifecycle semantics callers already understand; the two `skipped_*` variants short-circuit via the idempotency key (see `idempotency_key` below). Always populated — non-skipped runs derive this field from `tables_failed` / materialization counts, so JSON consumers no longer need to re-derive status from counts themselves.
    """
    tables_copied: conint(ge=0)
    tables_failed: conint(ge=0)
    """
    Total number of failed tables/models for the run, **including** pre-execution compile failures: a model that fails to type-check is counted here even though it never reached the execution phase. This is the authoritative failure count — consumers should key overall pass/fail on the top-level `tables_failed` / `status` / `errors`, not on `execution.tables_failed`, which counts only execution-phase (copy / runtime) failures and excludes models excluded before execution.
    """
    tables_skipped: conint(ge=0) | None = None
    version: str
