# generated by datamodel-codegen:
#   filename:  schedule_status.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, conint


class ScheduleClaimStatus(BaseModel):
    """
    One claim recorded against a pipeline.
    """

    attempts: conint(ge=0)
    """
    Attempts made against this claim.
    """
    logical_ts: AwareDatetime | None = None
    """
    The occurrence this claim belongs to. Null for a webhook demand, whose claim key carries a minted id rather than an instant.
    """
    outcome: str | None = None
    """
    The terminal outcome, when the claim is `completed`.
    """
    source: str
    """
    The demand source (`cron` | `after` | `freshness` | `webhook`).
    """
    state: str
    """
    Claim state (`submitted` | `released` | `completed`).
    """
    submission_id: str
    """
    The submission id — the join key to `GET /api/v1/jobs/{id}` and to run history.
    """


class ScheduleStatusCounts(BaseModel):
    """
    Roll-up counts over the reported pipelines.
    """

    config_errors: conint(ge=0)
    """
    How many declare a schedule that cannot be resolved.
    """
    enabled: conint(ge=0)
    """
    Of those, how many are enabled.
    """
    in_flight: conint(ge=0)
    """
    How many have a `submitted` claim — a run believed to be in flight.
    """
    overdue: conint(ge=0)
    """
    How many have a `next_fire_at` in the past (overdue).
    """
    scheduled: conint(ge=0)
    """
    Pipelines declaring a schedule (the length of `pipelines`).
    """
    throttled: conint(ge=0)
    """
    How many are currently inside a backoff window.
    """


class ScheduleThrottleKind1(StrEnum):
    """
    The failure backoff ladder (grows with `consecutive_failures`).
    """

    failure_backoff = "failure_backoff"


class ScheduleThrottleKind2(StrEnum):
    """
    The fixed backoff applied after a partial run.
    """

    partial_backoff = "partial_backoff"


class ScheduleThrottleStatus(BaseModel):
    """
    An active backoff window.
    """

    kind: ScheduleThrottleKind1 | ScheduleThrottleKind2
    """
    Which backoff is suppressing the demand.
    """
    resume_at: AwareDatetime
    """
    When the demand becomes eligible again.
    """


class TickLockState1(StrEnum):
    """
    No lock file exists — no tick has ever run in this project.
    """

    never = "never"


class TickLockState2(StrEnum):
    """
    Not currently held. The normal state between ticks.
    """

    free = "free"


class TickLockState3(StrEnum):
    """
    Held by a live reconciler (fresh heartbeat) — a tick is in progress.
    """

    held = "held"


class TickLockState4(StrEnum):
    """
    Held with a heartbeat stale past the takeover window: a wedged reconciler. The next tick overrides the lock and proceeds.
    """

    wedged = "wedged"


class ScheduleLockStatus(BaseModel):
    """
    The tick lock's state.
    """

    heartbeat_age_seconds: conint(ge=0) | None = None
    """
    Age of the lock's heartbeat in seconds, when one is readable.
    """
    state: TickLockState1 | TickLockState2 | TickLockState3 | TickLockState4
    """
    Lock state. Note `free` is the normal steady state — see [`TickLockState`].
    """


class SchedulePipelineStatus(BaseModel):
    """
    One scheduled pipeline's status.
    """

    after: list[str] | None = None
    """
    Upstream pipelines driving the `after` trigger.
    """
    awaiting_first_anchor: bool
    """
    True when no tick has recorded a cron anchor yet. The first tick records the anchor *without* firing, so `next_fire_at` is not yet projectable — which is a different thing from "this will never fire".
    """
    catchup: str
    """
    Catch-up policy: `latest` (fire the newest missed occurrence) or `skip` (jump the anchor forward, firing none of them).
    """
    claims: list[ScheduleClaimStatus] | None = None
    """
    Claims recorded for this pipeline, newest occurrence first.
    """
    config_error: str | None = None
    """
    The config error making this pipeline unschedulable, when its schedule cannot be resolved. The reconciler fails closed and never fires it, so this is why an otherwise-configured pipeline is silent.
    """
    consecutive_failures: conint(ge=0)
    """
    Consecutive failures driving the backoff ladder.
    """
    cron: str | None = None
    """
    The cron expression, when one is configured.
    """
    enabled: bool
    """
    False when the schedule declares `enabled = false`.
    """
    freshness_budget_seconds: conint(ge=0) | None = None
    """
    The resolved freshness budget in seconds, when that trigger is active.
    """
    last_attempt_at: AwareDatetime | None = None
    """
    When the last attempt started.
    """
    last_attempt_outcome: str | None = None
    """
    The last attempt's terminal outcome (`success` | `partial` | `failure`).
    """
    last_evaluated_at: AwareDatetime | None = None
    """
    When the reconciler last evaluated this pipeline's demand. Staleness here — not the tick lock — is what indicates a dead timer.
    """
    last_fire_logical_ts: AwareDatetime | None = None
    """
    The logical timestamp of the last occurrence that fired.
    """
    next_fire_at: AwareDatetime | None = None
    """
    When the cron is next expected to fire.

    **A timestamp in the past means overdue.** The projection is anchored on the stored cursor, not on the clock, so a stalled timer reports the slot it missed rather than a healthy-looking future one. Null for `after`/`freshness` schedules, which have no projectable instant.
    """
    pipeline: str
    """
    The pipeline name.
    """
    throttle: ScheduleThrottleStatus | None = None
    """
    The active backoff window, when the pipeline is throttled.
    """


class ScheduleStatusOutput(BaseModel):
    """
    A read-only snapshot of the scheduler: what is scheduled, when each pipeline last evaluated and fired, when it is next expected to, what is claimed in flight, and whether a reconciler holds the tick lock.

    API-only (`GET /api/v1/schedule`), so it carries no `version`/`command` preamble — it mirrors [`MetaOutput`] and `JobStatus`, not the CLI-backed [`TickOutput`].

    This is a **status read, not an evaluation**: it reports stored cursors, claims and lock state without deciding what is due. `rocky tick --dry-run` is the evaluation. Keeping the two apart makes this endpoint side-effect free and `O(pipelines)` rather than `O(runs × pipelines)`.
    """

    counts: ScheduleStatusCounts
    """
    Roll-up counts across `pipelines`.
    """
    now: AwareDatetime
    """
    The instant this snapshot was taken. Every projection below is relative to it.
    """
    pipelines: list[SchedulePipelineStatus]
    """
    Every schedulable pipeline declaring a `[schedule]`, sorted by name. Load pipelines are excluded — they are not schedulable (a scheduled load would re-ingest every discovered file), so reporting one as scheduled would promise a fire that can never happen.
    """
    tick_lock: ScheduleLockStatus
    """
    Whether a reconciler currently holds the tick lock.
    """
    timezone: str
    """
    The project timezone cron occurrences resolve in.
    """
