# generated by datamodel-codegen:
#   filename:  state_reconcile_watermark.schema.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel


class ReconciledWatermark(BaseModel):
    previous: AwareDatetime | None = None
    table: str
    target_max: AwareDatetime | None = None
    watermark: AwareDatetime


class ReconcileWatermarkOutput(BaseModel):
    """
    Result of repairing incremental cursors from physical target tables.
    """

    command: str
    dry_run: bool
    pipeline: str
    version: str
    watermarks: list[ReconciledWatermark]
