# generated by datamodel-codegen:
#   filename:  test.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field, conint


class DeclarativeTestResult(BaseModel):
    """
    Result of a single declarative test assertion.
    """

    column: str | None = None
    """
    Column under test, if applicable.
    """
    detail: str | None = None
    """
    Human-readable detail (e.g., "3 NULL rows found" or execution error).
    """
    model: str
    """
    Model name the test belongs to.
    """
    severity: str
    """
    Severity declared in the sidecar ("error" or "warning").
    """
    sql: str
    """
    The SQL that was executed.
    """
    status: str
    """
    "pass", "fail", or "error".
    """
    table: str
    """
    Fully-qualified target table (catalog.schema.table).
    """
    test_type: str
    """
    Test type (e.g., "not_null", "unique", "row_count_range").
    """


class DeclarativeTestSummary(BaseModel):
    """
    Summary of declarative test execution (from `[[tests]]` in model sidecars).
    """

    errored: conint(ge=0)
    failed: conint(ge=0)
    passed: conint(ge=0)
    results: list[DeclarativeTestResult]
    total: conint(ge=0)
    warned: conint(ge=0)


class ModelTestResult(BaseModel):
    """
    One per-model outcome from the local model-execution test.

    `status` is `"pass"` or `"fail"`. `error` is set only when `status = "fail"`. Mirrors `rocky_engine::test_runner::ModelTestResult` with the status flattened to a string so consumers (Pydantic, TypeScript) get a stable, JSON-Schema-friendly shape.
    """

    error: str | None = None
    model: str
    status: str
    """
    `"pass"` or `"fail"`.
    """


class TestFailure(BaseModel):
    """
    One failed test, mirroring the (name, error) tuple in `rocky_engine::test_runner::TestResult::failures` but with named fields because schemars/JSON Schema can't represent positional tuples cleanly.
    """

    error: str
    name: str


class TestOutput(BaseModel):
    """
    JSON output for `rocky test`.
    """

    command: str
    declarative: DeclarativeTestSummary | None = None
    """
    Results from declarative `[[tests]]` in model sidecars. Present only when `--declarative` is used.
    """
    failed: conint(ge=0)
    failures: list[TestFailure]
    model_results: list[ModelTestResult] | None = Field([], validate_default=True)
    """
    Per-model outcomes for the (DuckDB-backed) model-execution test — passes too, not just failures. Lets the VS Code Inspector Tests tab and the dagster integration render "good_mart: pass" without inferring it from `total - failures`. Empty when only declarative tests ran. Filtered to `--model` when that flag is set.
    """
    passed: conint(ge=0)
    total: conint(ge=0)
    version: str
