# generated by datamodel-codegen:
#   filename:  tick.schema.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, conint


class ExecutedRunOutput(BaseModel):
    """
    One demand that executed to a terminal outcome this tick.
    """

    attempts: conint(ge=0)
    """
    Total submissions made for this demand (the claim's monotonic audit counter): `1` unless in-tick retries fired.
    """
    exit_code: int
    """
    The child's exit code: `0` success, `2` partial, `1`/other failure.
    """
    logical_ts: AwareDatetime
    """
    The logical timestamp of the demand.
    """
    outcome: str
    """
    The mapped terminal outcome: `success` | `partial` | `failure`.
    """
    pipeline: str
    """
    The pipeline that ran.
    """
    source: str
    """
    The source that made it due: `cron` | `after` | `freshness` | `webhook`.
    """
    submission_id: str
    """
    The submission id of the recorded attempt — the precise join key between this demand and *its* run record (`rocky history` shows the same id). This is the reconciler's demand↔run identity; there is no separate `run_id` field because a run is joined to its demand by `submission_id`.
    """


class SkippedDemandOutput(BaseModel):
    """
    One demand suppressed this tick.
    """

    missed: conint(ge=0) | None = None
    """
    Number of missed cron occurrences — present for `catchup_skipped`.
    """
    pipeline: str | None = None
    """
    The pipeline the skip belongs to. `None` for a whole-tick skip (`tick_in_progress`, `state_busy`), which is not tied to a single pipeline.
    """
    reason: str
    """
    Why it was skipped: `not_due` | `disabled` | `in_flight` | `tick_in_progress` | `catchup_skipped` | `failure_backoff` | `partial_backoff` | `dedup` | `history_unavailable` | `state_busy`.
    """
    resume_at: AwareDatetime | None = None
    """
    When the demand becomes eligible again — present for `failure_backoff` and `partial_backoff`.
    """
    source: str | None = None
    """
    The demand source, when the skip is source-specific: `cron` | `after` | `freshness` | `webhook`. `None` for a pipeline- or tick-level skip.
    """


class SourceEvaluation(BaseModel):
    """
    One demand source's outcome within a pipeline's evaluation.
    """

    missed: conint(ge=0) | None = None
    """
    Number of missed cron occurrences — present for `catchup_skipped`.
    """
    reason: str
    """
    The reason string for this source: `due` | `not_due` | `disabled` | `catchup_skipped` | `failure_backoff` | `partial_backoff` | `superseded` | `history_unavailable`.
    """
    resume_at: AwareDatetime | None = None
    """
    When the source becomes eligible again — present for `failure_backoff` and `partial_backoff`.
    """
    source: str
    """
    The demand source: `cron` | `after` | `freshness` | `webhook`.
    """


class TickCounts(BaseModel):
    """
    Roll-up counts for a tick.
    """

    due: conint(ge=0)
    """
    Pipelines found due.
    """
    evaluated: conint(ge=0)
    """
    Pipelines evaluated this tick.
    """
    executed: conint(ge=0)
    """
    Demands executed to a terminal outcome.
    """
    failed: conint(ge=0)
    """
    Executed runs that failed (exit 1/other).
    """
    partial: conint(ge=0)
    """
    Executed runs that were partial (exit 2).
    """
    skipped: conint(ge=0)
    """
    Demands suppressed (the length of `skipped`).
    """
    succeeded: conint(ge=0)
    """
    Executed runs that succeeded (exit 0).
    """


class PipelineDemandStatus(BaseModel):
    """
    One pipeline's demand evaluation this tick.
    """

    due: bool
    """
    Whether any source made the pipeline due this tick.
    """
    due_source: str | None = None
    """
    The source that made it due (`cron` | `after` | `freshness` | `webhook`), when `due` is true.
    """
    logical_ts: AwareDatetime | None = None
    """
    The logical timestamp of the due demand (the cron occurrence, the max upstream-success time, or the staleness-breach detection time), when `due` is true.
    """
    pipeline: str
    """
    The pipeline name.
    """
    sources: list[SourceEvaluation]
    """
    Per-source outcome for every source considered (the due source included, with reason `due`).
    """


class TickOutput(BaseModel):
    """
    JSON output for `rocky tick` — one demand-reconciliation pass.

    A tick evaluates every scheduled pipeline's standing demand once, runs what is due (sequentially, via child `rocky run` processes), and records the outcome. This payload is the machine surface: an orchestration wrapper (a systemd timer, cron, CI) reads it to see what ran, what was suppressed, and why.

    **Honesty note:** exit code `0` does NOT mean the estate is healthy. A pipeline sitting in `failure_backoff`/`partial_backoff` produces quiet exit-`0` ticks after the tick that first observed its failure. Exit codes alert on *this tick's* work; ongoing sickness is carried by the `skipped` reasons + `counts` here and the `consecutive_failures` metric. Alert on those, not on exit codes alone.

    The feature is **experimental** while the native reconciler soaks.
    """

    command: str
    counts: TickCounts
    """
    Roll-up counts across `evaluated`/`executed`/`skipped`.
    """
    dry_run: bool
    """
    True when invoked with `--dry-run`: demand was evaluated and reported, but nothing executed and no state was written.
    """
    duration_ms: conint(ge=0)
    """
    Wall-clock duration of the whole tick, including child run time.
    """
    evaluated: list[PipelineDemandStatus]
    """
    Per-pipeline evaluation: the demand sources considered, whether the pipeline was due, and the per-source reason.
    """
    executed: list[ExecutedRunOutput]
    """
    Demands that ran to a terminal outcome this tick, in execution order.
    """
    lock_overridden: bool
    """
    True when this tick proceeded via the wedge override — it found the tick lock held but its heartbeat stale past the takeover window, so it ran without the lock and leaned on the claim state machine for correctness. Surfaced loudly because it signals a wedged prior reconciler.
    """
    now: AwareDatetime
    """
    The instant the tick evaluated demand against (`--now`, or the wall clock). Echoed for determinism and audit — occurrence math, `after`, and freshness are all resolved as of this instant.
    """
    skipped: list[SkippedDemandOutput]
    """
    Demands suppressed this tick, each with a stable reason string.
    """
    tick_in_progress: bool
    """
    True when the whole tick was skipped because a live reconciler already held the tick lock (a `tick_in_progress` skip is also emitted in `skipped`). The CLI still exits `0`.
    """
    version: str
