# generated by datamodel-codegen:
#   filename:  adapter_config.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, conint


class AdapterKind1(StrEnum):
    """
    Warehouse data movement (reads / writes table bytes).
    """

    data = "data"


class AdapterKind2(StrEnum):
    """
    Metadata-only discovery (enumerates source schemas / connectors).
    """

    discovery = "discovery"


class FivetranCacheBackend1(StrEnum):
    """
    No-op backend; every fetch goes to the Fivetran API. Default when `[adapter.fivetran.cache]` is absent.
    """

    none = "none"


class FivetranCacheBackend2(StrEnum):
    """
    Local-filesystem JSON files. Cheapest, no external dependency.
    """

    file = "file"


class FivetranCacheBackend3(StrEnum):
    """
    S3 / GCS / Azure / `file://` via the `object_store` crate.
    """

    object_store = "object_store"


class FivetranCacheBackend4(StrEnum):
    """
    Valkey / Redis. Requires the `valkey` Cargo feature.
    """

    valkey = "valkey"


class FivetranCacheBackend5(StrEnum):
    """
    Valkey (primary) + object_store (secondary). Requires the `valkey` Cargo feature.
    """

    tiered = "tiered"


class FivetranCacheConfig(BaseModel):
    """
    Persistent state cache configuration for the Fivetran adapter (FR-A).

    Cache backends shared across processes let several `rocky` invocations against one Fivetran org dedupe their discover fetches — the first process pays the API cost, every subsequent process within the TTL window reads the canonical envelope from the cache. See `engine/crates/rocky-fivetran/src/state_cache/` for the implementation details.

    ## TOML shape

    ```toml [adapter.fivetran.cache] backend = "tiered"                              # "none" | "file" | "object_store" | "valkey" | "tiered" file_root = ".rocky/fivetran-state/"            # required for backend = "file" object_store_url = "s3://my-bucket/rocky/fv/"   # required for backend = "object_store" / "tiered" valkey_url = "rediss://valkey:6379/"            # required for backend = "valkey" / "tiered" valkey_ttl_seconds = 600                        # default 600 ```

    ## Backend selection

    - `none` — disable the cache; default when the block is absent. - `file` — local-filesystem JSON files under `file_root`. - `object_store` — S3 / GCS / Azure / `file://`; URL parsed by `object_store::parse_url`. Credentials come from the SDK default chain (`AWS_*` env vars, IAM role, `GOOGLE_APPLICATION_CREDENTIALS`, etc.) — Rocky doesn't introduce its own credential surface. - `valkey` — Redis / Valkey; requires building rocky-fivetran with the `valkey` Cargo feature. URL accepts `redis://` and `rediss://` (TLS). - `tiered` — composes Valkey (primary, fast) + object-store (secondary, durable). Requires both URLs.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    backend: (
        FivetranCacheBackend1
        | FivetranCacheBackend2
        | FivetranCacheBackend3
        | FivetranCacheBackend4
        | FivetranCacheBackend5
        | None
    ) = "none"
    """
    Which backend to instantiate. Defaults to [`FivetranCacheBackend::None`] so a stub `[adapter.fivetran.cache]` block with no `backend` key is well-defined.
    """
    file_root: str | None = None
    """
    Root directory for `backend = "file"`. Required for that backend; ignored otherwise. May contain `${VAR}` / `${VAR:-default}` env-var references; resolved at config-load time.
    """
    object_store_url: str | None = None
    """
    URL passed to `object_store::parse_url` for `backend = "object_store"` or `backend = "tiered"` (secondary layer). Examples: `s3://bucket/prefix/`, `gs://bucket/prefix/`, `az://container/prefix/`, `file:///path/`.
    """
    valkey_ttl_seconds: conint(ge=0) | None = None
    """
    TTL applied to every `SET` against the Valkey backend. Defaults to 600s when unset. Ignored for non-Valkey backends.
    """
    valkey_url: str | None = None
    """
    Connection URL for `backend = "valkey"` or `backend = "tiered"` (primary layer). Standard `redis://` (plain) or `rediss://` (TLS).
    """


class RetryConfig(BaseModel):
    """
    Retry policy for transient warehouse errors (HTTP 429/503, rate limits, timeouts).

    Rocky retries transient errors with exponential backoff and optional jitter to prevent thundering herd across concurrent runs.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    backoff_multiplier: float | None = 2.0
    """
    Backoff multiplier applied after each retry (e.g. 2.0 = double each time).
    """
    circuit_breaker_recovery_timeout_secs: conint(ge=0) | None = None
    """
    Seconds the breaker will stay `Open` before a single trial request is allowed through (half-open state). On trial success the breaker closes and resumes normal traffic; on trial failure it re-opens immediately. `None` preserves the pre-Arc-3 "manual-reset-only" behaviour — a tripped breaker stays tripped for the rest of the run.
    """
    circuit_breaker_threshold: conint(ge=0) | None = 5
    """
    Circuit breaker: trip after this many consecutive transient failures across statements. Once tripped, all subsequent statements fail immediately without attempting execution. Default: 5. Set to 0 to disable.
    """
    initial_backoff_ms: conint(ge=0) | None = 1000
    """
    Initial backoff duration in milliseconds before the first retry.
    """
    jitter: bool | None = True
    """
    Add random jitter to prevent concurrent runs from retrying in lockstep.
    """
    max_backoff_ms: conint(ge=0) | None = 30000
    """
    Maximum backoff duration in milliseconds (caps exponential growth).
    """
    max_retries: conint(ge=0) | None = 3
    """
    Maximum number of retry attempts. Set to 0 to disable retries (e.g. for CI).
    """
    max_retries_per_run: conint(ge=0) | None = None
    """
    Cross-statement retry budget for a single run (§P2.7). When set, adapters construct a [`crate::retry_budget::RetryBudget`] from this value and decrement it on every retry; once exhausted, remaining statements fail fast with adapter-specific `RetryBudgetExhausted` errors instead of burning the warehouse's rate-limit quota.

    `None` (default) keeps legacy behaviour — per-statement [`RetryConfig::max_retries`] is the only bound. `Some(0)` means no retries are allowed for the whole run.
    """


class AdapterConfig(BaseModel):
    """
    Configuration for a named adapter instance.

    The `type` field determines which adapter crate handles this config. Adapter-specific fields are captured via `serde(flatten)`.

    Credential fields (`token`, `client_secret`, `api_key`, `api_secret`, `password`, `oauth_token`) are wrapped in [`RedactedString`] so that `Debug` output never leaks secrets.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    account: str | None = None
    """
    Snowflake account identifier (e.g., "xy12345.us-east-1").
    """
    api_key: str | None = None
    api_secret: str | None = None
    cache: FivetranCacheConfig | None = None
    """
    Optional cache backend for the Fivetran state envelope.

    When set on a `type = "fivetran"` adapter, the resolved envelope is read from and written to the configured cache backend so concurrent `rocky` processes share one fetcher per org. Ignored on every other adapter type. When absent the adapter behaves as if `backend = "none"` — every fetch goes straight to the Fivetran API.
    """
    client_id: str | None = None
    client_secret: str | None = None
    database: str | None = None
    """
    Default database for the session.
    """
    destination_id: str | None = None
    host: str | None = None
    http_path: str | None = None
    kind: AdapterKind1 | AdapterKind2 | None = None
    """
    Role this adapter block plays. See [`AdapterKind`] for the required-vs-optional rules per adapter type.
    """
    location: str | None = None
    """
    BigQuery processing location (e.g., "US", "EU", "us-central1").
    """
    oauth_token: str | None = None
    """
    OAuth access token (pre-obtained from an IdP).
    """
    password: str | None = None
    """
    Snowflake password (for password auth).
    """
    pat: str | None = None
    """
    Programmatic Access Token (issued via Snowsight User Profile). Sent as a Bearer token with the `PROGRAMMATIC_ACCESS_TOKEN` token-type header — distinct from `oauth_token`.
    """
    path: str | None = None
    """
    Optional file path for a persistent DuckDB database. When unset, the adapter uses an in-memory database. A persistent path is required when the same DuckDB adapter is also used as a discovery source — discovery and warehouse share the same database.
    """
    private_key_path: str | None = None
    """
    Path to RSA private key file (PEM) for key-pair auth.
    """
    project_id: str | None = None
    """
    Google Cloud project ID.
    """
    retry: RetryConfig | None = Field(
        {
            "backoff_multiplier": 2.0,
            "circuit_breaker_recovery_timeout_secs": None,
            "circuit_breaker_threshold": 5,
            "initial_backoff_ms": 1000,
            "jitter": True,
            "max_backoff_ms": 30000,
            "max_retries": 3,
            "max_retries_per_run": None,
        },
        validate_default=True,
    )
    """
    Retry policy for this adapter.
    """
    role: str | None = None
    """
    Snowflake role to use for the session.
    """
    timeout_secs: conint(ge=0) | None = None
    token: str | None = None
    type: str
    """
    Adapter type: "databricks", "fivetran", "duckdb", etc.
    """
    username: str | None = None
    """
    Snowflake username (for password or key-pair auth).
    """
    warehouse: str | None = None
    """
    Snowflake warehouse to use for query execution.
    """
