# generated by datamodel-codegen:
#   filename:  archive.schema.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, conint


class ArchiveTotals(BaseModel):
    """
    Aggregate counts over a `rocky archive --catalog` invocation.
    """

    statement_count: conint(ge=0)
    table_count: conint(ge=0)


class NamedStatement(BaseModel):
    """
    Named SQL statement (purpose + sql), reused by compact and archive.

    `sql` is optional in preparation for the v2 persisted plan format (Cluster 3 C — "SQL as `.o` files"). Today's emission path always populates `Some(string)` for both stdout JSON and the persisted plan; the v2 format will write `None` and rely on the apply path to regenerate SQL from the plan's typed IR.
    """

    purpose: str
    sql: str | None = None


class ArchiveOutput(BaseModel):
    """
    JSON output for `rocky archive`.

    Mirrors [`CompactOutput`]: single-model invocations populate `model` and leave the catalog-scope fields absent; `--catalog` invocations populate `catalog`, `scope = "catalog"`, `tables`, and `totals`. The flat `statements` list carries every statement across every table.
    """

    catalog: str | None = None
    """
    Set when invoked as `rocky archive --catalog <name>`.
    """
    command: str
    dry_run: bool
    model: str | None = None
    older_than: str
    older_than_days: conint(ge=0)
    plan_id: str | None = None
    """
    Plan identifier (full 64-char blake3 hex). Populated when the plan is persisted to `.rocky/plans/` so it can be applied later via `rocky archive apply <plan_id>`. Absent when plan persistence is skipped.
    """
    scope: str | None = None
    """
    `"catalog"` for the catalog-scoped path; absent for single-model invocations.
    """
    statements: list[NamedStatement]
    tables: dict[str, Any] | None = None
    totals: ArchiveTotals | None = None
    version: str


class ArchiveTableEntry(BaseModel):
    """
    Per-table archive plan inside a `--catalog` envelope.
    """

    statements: list[NamedStatement]
