# generated by datamodel-codegen:
#   filename:  catalog.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, conint


class AssetKind(StrEnum):
    """
    Asset kind discriminator for [`CatalogAsset`].
    """

    Source = "Source"
    Model = "Model"
    View = "View"
    MaterializedView = "MaterializedView"


class CatalogColumn(BaseModel):
    """
    A column on a catalog asset.
    """

    data_type: str | None = None
    """
    Declared or inferred type of the column, when known.
    """
    name: str
    nullable: bool | None = None
    """
    Whether the column accepts nulls, when known.
    """


class CatalogStats(BaseModel):
    """
    Aggregate counts for the emitted catalog.
    """

    asset_count: conint(ge=0)
    assets_with_star: conint(ge=0)
    """
    Number of assets whose lineage was derived from `SELECT *` (and is therefore inferred rather than parsed). Surfaces partial-lineage coverage as a single number in the summary.
    """
    column_count: conint(ge=0)
    duration_ms: conint(ge=0)
    edge_count: conint(ge=0)
    orphan_columns: conint(ge=0)
    """
    Number of columns with no producing edge — typically the result of a star expansion that could not resolve an upstream column.
    """


class EdgeConfidence(StrEnum):
    """
    Confidence grading for a [`CatalogEdge`].

    Coarse-grained on purpose: every consumer threshold-checks at "good enough", and a 3-bucket enum is simpler than a numeric score. A numeric `confidence_score` field can be added alongside this enum later without breaking callers.
    """

    High = "High"
    Medium = "Medium"
    Low = "Low"


class CatalogAsset(BaseModel):
    """
    A single asset (model or source) in the catalog.
    """

    columns: list[CatalogColumn]
    downstream_models: list[str]
    fqn: str
    """
    Fully-qualified target identifier (`catalog.schema.table`) when resolvable, otherwise the model name.
    """
    intent: str | None = None
    """
    Free-form natural-language description of the asset's purpose, when supplied via the model's sidecar config.
    """
    kind: AssetKind
    """
    Whether the asset is a project-managed model or an external source.
    """
    last_materialized_at: AwareDatetime | None = None
    """
    Timestamp of the last successful materialization, when known.
    """
    last_run_id: str | None = None
    """
    Identifier of the last successful run that produced the asset, when known.
    """
    model_name: str
    """
    Model or source name as it appears in lineage edges.
    """
    upstream_models: list[str]


class CatalogEdge(BaseModel):
    """
    A single column-level lineage edge.
    """

    confidence: EdgeConfidence
    """
    Confidence the producing edge is fully understood. `Medium` is emitted for star-expanded projections (where lineage is inferred rather than parsed from an explicit projection); `High` for edges sourced from explicit columns.
    """
    source_column: str
    source_model: str
    target_column: str
    target_model: str
    transform: str
    """
    Transform kind: "direct", "cast", "expression", or "aggregation: <fn>". Stringified to match the existing lineage edge shape.
    """


class CatalogOutput(BaseModel):
    """
    JSON output for `rocky catalog`.

    A persisted, queryable snapshot of column-level lineage across the project. Emitted to `./.rocky/catalog/catalog.json` (default) so any non-Rocky consumer (BI tool, governance dashboard, PR bot) can read the artifact without invoking the engine. The CLI's own stdout is a one-screen summary; this struct is the structured payload backing `--output json`.
    """

    assets: list[CatalogAsset]
    command: str
    config_hash: str
    """
    Stable fingerprint of the `rocky.toml` bytes. Lets a downstream consumer detect whether the catalog was built against a config that has since changed.
    """
    edges: list[CatalogEdge]
    generated_at: AwareDatetime
    last_run_id: str | None = None
    """
    Identifier of the last successful run that produced these assets, when known. Absent until the catalog is enriched with run-history metadata.
    """
    project_name: str
    """
    Pipeline name used to build the catalog. When the project has multiple pipelines, this is the first one in declaration order.
    """
    stats: CatalogStats
    version: str
