# generated by datamodel-codegen:
#   filename:  ci_diff.schema.json
#   timestamp: 2026-04-15T23:28:11+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, conint


class ColumnChangeType1(StrEnum):
    """
    Column was added in the incoming side.
    """

    added = "added"


class ColumnChangeType2(StrEnum):
    """
    Column was removed (present on base, absent on incoming).
    """

    removed = "removed"


class ColumnChangeType3(StrEnum):
    """
    Column data type changed between base and incoming.
    """

    type_changed = "type_changed"


class ColumnDiff(BaseModel):
    """
    A single column-level difference within a model.
    """

    change_type: ColumnChangeType1 | ColumnChangeType2 | ColumnChangeType3
    """
    Kind of change.
    """
    column_name: str
    """
    Column name.
    """
    new_type: str | None = None
    """
    New data type (empty for removed columns).
    """
    old_type: str | None = None
    """
    Previous data type (empty for added columns).
    """


class DiffSummary(BaseModel):
    """
    High-level summary across all models in a diff run.
    """

    added: conint(ge=0)
    modified: conint(ge=0)
    removed: conint(ge=0)
    total_models: conint(ge=0)
    unchanged: conint(ge=0)


class ModelDiffStatus1(StrEnum):
    """
    Model output is identical across both sides.
    """

    unchanged = "unchanged"


class ModelDiffStatus2(StrEnum):
    """
    Model exists on both sides but output differs.
    """

    modified = "modified"


class ModelDiffStatus3(StrEnum):
    """
    Model exists only on the incoming (PR) side.
    """

    added = "added"


class ModelDiffStatus4(StrEnum):
    """
    Model exists only on the base (target branch) side.
    """

    removed = "removed"


class DiffResult(BaseModel):
    """
    Diff result for a single model between two pipeline states.
    """

    column_changes: list[ColumnDiff] | None = None
    """
    Column-level changes (empty for unchanged models).
    """
    model_name: str
    """
    Fully-qualified model name (e.g. `catalog.schema.table`).
    """
    row_count_after: conint(ge=0) | None = None
    """
    Row count on the incoming (PR) side. `None` for removed models.
    """
    row_count_before: conint(ge=0) | None = None
    """
    Row count on the base (target branch) side. `None` for added models.
    """
    sample_changed_rows: list[list[str]] | None = None
    """
    Optional sample of changed rows for human review.
    """
    status: ModelDiffStatus1 | ModelDiffStatus2 | ModelDiffStatus3 | ModelDiffStatus4
    """
    High-level status.
    """


class CiDiffOutput(BaseModel):
    """
    JSON output for `rocky ci-diff`.

    Reports which models changed between two git refs, with optional column-level structural diffs when compilation succeeds on both sides.
    """

    base_ref: str
    """
    Git ref used as the comparison base (e.g. `main`).
    """
    command: str
    head_ref: str
    """
    Git ref for the incoming changes (typically `HEAD`).
    """
    markdown: str
    """
    Pre-rendered Markdown suitable for posting as a GitHub PR comment.
    """
    models: list[DiffResult]
    """
    Per-model diff results.
    """
    summary: DiffSummary
    """
    Aggregate counts of changed models.
    """
    version: str
