# generated by datamodel-codegen:
#   filename:  ci.schema.json
#   timestamp: 2026-04-15T01:23:11+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, conint


class Severity(StrEnum):
    """
    Severity level of a diagnostic.

    Serialized in PascalCase (`"Error"`, `"Warning"`, `"Info"`) to stay compatible with existing dagster fixtures and the hand-written `Severity` StrEnum in `integrations/dagster/src/dagster_rocky/types.py`.
    """

    Error = "Error"
    Warning = "Warning"
    Info = "Info"


class SourceSpan(BaseModel):
    """
    Location in a source file.
    """

    col: conint(ge=0)
    file: str
    line: conint(ge=0)


class TestFailure(BaseModel):
    """
    One failed test, mirroring the (name, error) tuple in `rocky_engine::test_runner::TestResult::failures` but with named fields because schemars/JSON Schema can't represent positional tuples cleanly.
    """

    error: str
    name: str


class Diagnostic(BaseModel):
    """
    A compiler diagnostic (error, warning, or informational message).
    """

    code: str
    """
    Diagnostic code (e.g., "E001", "W001").
    """
    message: str
    """
    Human-readable message.
    """
    model: str
    """
    Which model this diagnostic relates to.
    """
    severity: Severity
    """
    Severity level.
    """
    span: SourceSpan | None = None
    """
    Source location (if available).
    """
    suggestion: str | None = None
    """
    Suggested fix (if any).
    """


class CiOutput(BaseModel):
    """
    JSON output for `rocky ci`.
    """

    command: str
    compile_ok: bool
    diagnostics: list[Diagnostic]
    exit_code: int
    failures: list[TestFailure]
    models_compiled: conint(ge=0)
    tests_failed: conint(ge=0)
    tests_ok: bool
    tests_passed: conint(ge=0)
    version: str
