# generated by datamodel-codegen:
#   filename:  column_lineage.schema.json

from __future__ import annotations

from pydantic import BaseModel


class LineageQualifiedColumn(BaseModel):
    column: str
    model: str


class LineageEdgeRecord(BaseModel):
    source: LineageQualifiedColumn
    target: LineageQualifiedColumn
    transform: str
    """
    Transform kind: "direct", "cast", "expression", etc. Stringified from `rocky_sql::lineage::TransformKind` to avoid pulling schemars into rocky-sql.
    """


class ColumnLineageOutput(BaseModel):
    """
    JSON output for `rocky lineage <model> --column <col>`.
    """

    column: str
    command: str
    direction: str
    """
    Direction of the trace walk: `"upstream"` (producers) or `"downstream"` (consumers). Defaults to upstream when `--column` is set without direction flags, matching pre-Arc-1 behaviour.
    """
    model: str
    trace: list[LineageEdgeRecord]
    version: str
