# generated by datamodel-codegen:
#   filename:  compact_dedup.schema.json
#   timestamp: 2026-04-15T01:23:11+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, conint


class ByteCalibration(BaseModel):
    """
    Byte-level calibration block populated by `--calibrate-bytes`.

    Samples a handful of tables (default: 3), pulls their rows via `SELECT *`, hashes each row group with blake3 in-process, and computes byte-level dedup on the sample. The `lower_bound_multiplier` is the ratio `byte_dedup_pct / partition_dedup_pct` — it tells you how much of a floor the cheap partition-level measurement actually is.
    """

    byte_dedup_pct: float
    """
    Byte-level blake3 dedup on the same sample.
    """
    lower_bound_multiplier: float
    """
    `byte_dedup_pct / partition_dedup_pct`. A value >1.0 means the cheap partition-level measurement is genuinely underestimating.
    """
    partition_dedup_pct: float
    """
    Partition-level `SUM(HASH())` dedup recomputed on the sample (so it's directly comparable to `byte_dedup_pct`).
    """
    tables_sampled: list[str]
    """
    Which tables were hashed at byte level.
    """


class DedupPair(BaseModel):
    """
    A pair of tables that share duplicate partitions.
    """

    shared_partitions: conint(ge=0)
    shared_rows: conint(ge=0)
    table_a: str
    table_b: str


class DedupSummary(BaseModel):
    """
    Summary of a single dedup measurement (raw or semantic).

    `dedup_ratio` is a **lower bound** on true byte-level dedup — see the docstring on [`CompactDedupOutput`].
    """

    dedup_ratio: float
    """
    0.0..=1.0. Partition-level lower bound on byte-level dedup.
    """
    duplicate_partitions: conint(ge=0)
    estimated_savings_pct: float
    """
    0.0..=100.0. Estimated storage savings if duplicate partitions were collapsed to a single copy.
    """
    total_rows: conint(ge=0)
    unique_partitions: conint(ge=0)


class TableDedupContribution(BaseModel):
    """
    Per-table contribution to the overall duplicate set.
    """

    contribution_pct: float
    """
    0.0..=100.0. Share of this table's partitions that are duplicates of some other table's partitions.
    """
    partitions: conint(ge=0)
    partitions_shared_with_others: conint(ge=0)
    table: str


class CompactDedupOutput(BaseModel):
    """
    JSON output for `rocky compact --measure-dedup` (Layer 0 storage experiment).

    Measures cross-table partition dedup across all Rocky-managed tables in a project. The `raw` and `semantic` numbers are both **partition-level lower bounds** on byte-level dedup — two partitions that share 99% of their row groups but differ on a single row will appear fully distinct here. The optional `calibration` block (populated by `--calibrate-bytes`) hashes actual row-group bytes on a sampled subset of tables to give a sharper, more expensive second number.

    The measurement is **engine-scoped**: warehouse-native `HASH()` is not portable across engines (Databricks ≠ Snowflake ≠ DuckDB), so the `engine` field must be carried with any published result.
    """

    calibration: ByteCalibration | None = None
    """
    Byte-level calibration on a sampled subset of tables. Present only when `--calibrate-bytes` was passed. Produces a sharper estimate at the cost of pulling raw rows and hashing them locally.
    """
    command: str
    duration_ms: conint(ge=0)
    engine: str
    """
    Warehouse engine identifier (`"databricks"`, `"snowflake"`, `"duckdb"`). Measurements are not comparable across engines because `HASH()` is not portable.
    """
    excluded_columns: list[str]
    """
    Columns excluded from the `semantic` hash.
    """
    measured_at: AwareDatetime
    partitions_scanned: conint(ge=0)
    per_table: list[TableDedupContribution]
    """
    Per-table breakdown showing which tables contribute most to the duplicate set.
    """
    project: str
    """
    Project name from `rocky.toml`.
    """
    raw: DedupSummary
    """
    Dedup computed over all columns (what a byte-level chunk store would actually deduplicate).
    """
    scope: str
    """
    Whether the measurement was scoped to Rocky-managed tables (`"managed"`) or included all warehouse tables (`"all"`).
    """
    semantic: DedupSummary
    """
    Dedup computed after excluding Rocky-owned metadata columns. The gap between `raw` and `semantic` is "dedup we'd unlock if we ignored Rocky's own per-row metadata."
    """
    tables_scanned: conint(ge=0)
    top_dedup_pairs: list[DedupPair]
    """
    Top-N table pairs by shared partition count (from the `semantic` measurement).
    """
    version: str
