# generated by datamodel-codegen:
#   filename:  dag.schema.json
#   timestamp: 2026-04-16T10:46:55+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field, conint


class DagEdgeOutput(BaseModel):
    """
    One directed edge in the DAG output.
    """

    edge_type: str
    """
    Semantic classification: `"data"`, `"check"`, `"governance"`.
    """
    from_: str = Field(..., alias="from")
    """
    Upstream node ID.
    """
    to: str
    """
    Downstream node ID.
    """


class DagSummaryOutput(BaseModel):
    """
    Summary counts for the DAG.
    """

    counts_by_kind: dict[str, conint(ge=0)]
    execution_layers: conint(ge=0)
    total_edges: conint(ge=0)
    total_nodes: conint(ge=0)


class LineageQualifiedColumn(BaseModel):
    column: str
    model: str


class ModelFreshnessConfig(BaseModel):
    """
    Per-model freshness configuration.

    Declares the maximum allowed lag between successive materializations of the model. The compiler does not validate this — it's a metadata field consumed by downstream observability tools.
    """

    max_lag_seconds: conint(ge=0)
    """
    Maximum lag in seconds before the model is considered stale.
    """


class PartitionShapeOutput(BaseModel):
    """
    Partition shape metadata for time-interval nodes.
    """

    first_partition: str | None = None
    """
    First partition key, if declared in the model sidecar.
    """
    granularity: str
    """
    Time granularity: `"daily"`, `"hourly"`, `"monthly"`, `"yearly"`.
    """


class Type(StrEnum):
    full_refresh = "full_refresh"


class StrategyConfig8(BaseModel):
    """
    Materialization strategy for a model, defaulting to full refresh.
    """

    type: Type


class Type8(StrEnum):
    incremental = "incremental"


class StrategyConfig9(BaseModel):
    """
    Materialization strategy for a model, defaulting to full refresh.
    """

    timestamp_column: str
    type: Type8


class Type9(StrEnum):
    merge = "merge"


class StrategyConfig10(BaseModel):
    """
    Materialization strategy for a model, defaulting to full refresh.
    """

    type: Type9
    unique_key: list[str]
    update_columns: list[str] | None = None


class Type10(StrEnum):
    time_interval = "time_interval"


class Type11(StrEnum):
    ephemeral = "ephemeral"


class StrategyConfig12(BaseModel):
    """
    Ephemeral model — inlined as CTE in downstream queries, no table created.
    """

    type: Type11


class Type12(StrEnum):
    delete_insert = "delete_insert"


class StrategyConfig13(BaseModel):
    """
    Delete+Insert: delete matching rows by partition key, then insert.
    """

    partition_by: list[str]
    """
    Column(s) used to identify the partition to delete.
    """
    type: Type12


class Type13(StrEnum):
    microbatch = "microbatch"


class TargetConfig(BaseModel):
    """
    Target table coordinates for a model.
    """

    catalog: str
    schema_: str = Field(..., alias="schema")
    table: str


class TimeGrain(StrEnum):
    """
    Partition granularity for `time_interval` materialization.

    The granularity determines: - The canonical partition key format (see [`TimeGrain::format_str`]). - How `@start_date` / `@end_date` placeholders are computed per partition. - What column types are valid (`hour` requires TIMESTAMP; others accept DATE).
    """

    hour = "hour"
    day = "day"
    month = "month"
    year = "year"


class LineageEdgeRecord(BaseModel):
    source: LineageQualifiedColumn
    target: LineageQualifiedColumn
    transform: str
    """
    Transform kind: "direct", "cast", "expression", etc. Stringified from `rocky_sql::lineage::TransformKind` to avoid pulling schemars into rocky-sql.
    """


class StrategyConfig11(BaseModel):
    """
    Partition-keyed materialization. Each run targets specific partitions rather than appending past a watermark. Idempotent and backfill-friendly.

    The model SQL must reference `@start_date` and `@end_date` placeholders, which the runtime substitutes per partition with quoted timestamp literals.
    """

    batch_size: conint(ge=1) | None = 1
    """
    Combine N consecutive partitions into one SQL statement when backfilling. Defaults to 1 (atomic per-partition replacement).
    """
    first_partition: str | None = None
    """
    Lower bound for `--missing` discovery, in canonical key format (e.g., `"2024-01-01"` for daily). Required when `--missing` is used.
    """
    granularity: TimeGrain
    """
    Partition granularity (`hour`, `day`, `month`, `year`).
    """
    lookback: conint(ge=0) | None = 0
    """
    Recompute the previous N partitions on each run, in addition to whatever the CLI selected. Standard handling for late-arriving data.
    """
    time_column: str
    """
    Column on the model output that holds the partition value. Must be a non-nullable date or timestamp column. Validated by the compiler against the typed output schema.
    """
    type: Type10


class StrategyConfig14(BaseModel):
    """
    Microbatch: alias for time_interval with hourly defaults. dbt-compatible naming for partition-based incremental processing.
    """

    granularity: TimeGrain | None = "hour"
    """
    Batch granularity (default: Hour).
    """
    timestamp_column: str
    """
    Timestamp column for micro-batch boundaries.
    """
    type: Type13


class DagNodeOutput(BaseModel):
    """
    One node in the enriched DAG, projected for orchestrators.

    Cross-references the engine's internal `UnifiedNode` with model configs, seeds, and pipeline configs to attach the metadata that orchestrators need (target, strategy, freshness, partition shape).
    """

    depends_on: list[str] | None = None
    """
    Upstream node IDs (derived from DAG edges).
    """
    freshness: ModelFreshnessConfig | None = None
    """
    Per-model freshness expectation from the model sidecar.
    """
    id: str
    """
    Unique identifier: `{kind}:{name}` (e.g. `transformation:stg_orders`).
    """
    kind: str
    """
    Node kind: `source`, `load`, `transformation`, `quality`, `snapshot`, `seed`, `test`, `replication`.
    """
    label: str
    """
    Human-readable label (usually the pipeline or model name).
    """
    partition_shape: PartitionShapeOutput | None = None
    """
    Partition shape for time-interval models. `None` for unpartitioned strategies.
    """
    pipeline: str | None = None
    """
    Pipeline name from `rocky.toml`, if applicable.
    """
    strategy: (
        StrategyConfig8
        | StrategyConfig9
        | StrategyConfig10
        | StrategyConfig11
        | StrategyConfig12
        | StrategyConfig13
        | StrategyConfig14
        | None
    ) = None
    """
    Materialization strategy. Present for transformation nodes.
    """
    target: TargetConfig | None = None
    """
    Target table coordinates. Present for transformation, seed, load, and snapshot nodes.
    """


class DagOutput(BaseModel):
    """
    JSON output for `rocky dag`.

    Projects the engine's internal [`UnifiedDag`] into an enriched, orchestrator-friendly shape: every pipeline stage becomes a node with its target table coordinates, materialization strategy, freshness SLA, partition shape, and direct upstream dependencies.

    Consumers (dagster-rocky) can build a complete, connected asset graph from a single `rocky dag --output json` call.

    [`UnifiedDag`]: rocky_core::unified_dag::UnifiedDag
    """

    column_lineage: list[LineageEdgeRecord] | None = None
    """
    Column-level lineage edges across all models. Only populated when `--column-lineage` is passed; empty otherwise.
    """
    command: str
    edges: list[DagEdgeOutput]
    """
    Directed edges between nodes (from → to).
    """
    execution_layers: list[list[str]]
    """
    Topologically-sorted execution layers. Nodes within the same layer have no mutual dependencies and can execute in parallel.
    """
    nodes: list[DagNodeOutput]
    """
    Every stage in the pipeline as an enriched DAG node.
    """
    summary: DagSummaryOutput
    """
    Summary counts for the DAG.
    """
    version: str
