# generated by datamodel-codegen:
#   filename:  dag.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field, conint


class DagEdgeOutput(BaseModel):
    """
    One directed edge in the DAG output.
    """

    edge_type: str
    """
    Semantic classification: `"data"`, `"check"`, `"governance"`.
    """
    from_: str = Field(..., alias="from")
    """
    Upstream node ID.
    """
    to: str
    """
    Downstream node ID.
    """


class DagSummaryOutput(BaseModel):
    """
    Summary counts for the DAG.
    """

    counts_by_kind: dict[str, conint(ge=0)]
    execution_layers: conint(ge=0)
    total_edges: conint(ge=0)
    total_nodes: conint(ge=0)


class LineageQualifiedColumn(BaseModel):
    column: str
    model: str


class PartitionShapeOutput(BaseModel):
    """
    Partition shape metadata for time-interval nodes.
    """

    first_partition: str | None = None
    """
    First partition key, if declared in the model sidecar.
    """
    granularity: str
    """
    Time granularity: `"daily"`, `"hourly"`, `"monthly"`, `"yearly"`.
    """


class Type(StrEnum):
    full_refresh = "full_refresh"


class StrategyConfig12(BaseModel):
    """
    Materialization strategy for a model, defaulting to full refresh.
    """

    type: Type


class Type12(StrEnum):
    incremental = "incremental"


class StrategyConfig13(BaseModel):
    """
    Materialization strategy for a model, defaulting to full refresh.
    """

    timestamp_column: str
    type: Type12


class Type13(StrEnum):
    merge = "merge"


class StrategyConfig14(BaseModel):
    """
    Materialization strategy for a model, defaulting to full refresh.
    """

    type: Type13
    unique_key: list[str]
    update_columns: list[str] | None = None


class Type14(StrEnum):
    time_interval = "time_interval"


class Type15(StrEnum):
    ephemeral = "ephemeral"


class StrategyConfig16(BaseModel):
    """
    Ephemeral model — inlined as CTE in downstream queries, no table created.
    """

    type: Type15


class Type16(StrEnum):
    delete_insert = "delete_insert"


class StrategyConfig17(BaseModel):
    """
    Delete+Insert: delete matching rows by partition key, then insert.
    """

    partition_by: list[str]
    """
    Column(s) used to identify the partition to delete.
    """
    type: Type16


class Type17(StrEnum):
    microbatch = "microbatch"


class Type18(StrEnum):
    view = "view"


class StrategyConfig19(BaseModel):
    """
    SQL view — no physical storage. Every read against the target re-runs the model SELECT. Supported on every Rocky-targeted warehouse.
    """

    type: Type18


class Type19(StrEnum):
    materialized_view = "materialized_view"


class StrategyConfig20(BaseModel):
    """
    Materialized view — warehouse manages refresh. Supported on Databricks, Snowflake, and BigQuery. DuckDB / Trino surface a "not supported" error at SQL-gen time.
    """

    type: Type19


class Type20(StrEnum):
    dynamic_table = "dynamic_table"


class StrategyConfig21(BaseModel):
    """
    Snowflake dynamic table — warehouse manages lag-based refresh. `target_lag` is a Snowflake lag specifier (e.g. `"1 minute"`, `"5 hours"`, `"downstream"`). Non-Snowflake adapters surface a "not supported" error at SQL-gen time.
    """

    target_lag: str
    """
    Snowflake lag specifier — alphanumeric + space only. Examples: `"1 minute"`, `"5 hours"`, `"downstream"`.
    """
    type: Type20


class Type21(StrEnum):
    content_addressed = "content_addressed"


class StrategyConfig22(BaseModel):
    """
    Content-addressed write to a Delta UniForm table via the `rocky-iceberg` writer. The runtime executes the model SQL, converts the result to Arrow, blake3-hashes the Parquet bytes, uploads to `storage_prefix`, and emits a Delta log commit. Cross-engine reads (DuckDB iceberg_scan, etc.) require MSCK REPAIR after each commit; the runtime issues this automatically.
    """

    partition_columns: list[str] | None = []
    """
    Logical partition column names. Empty for unpartitioned tables. The runtime asserts this matches the table's declared partition columns at materialization time.
    """
    storage_prefix: str
    """
    Object-store key prefix that holds `_delta_log/` + Parquet files for the target table. Typically `s3://<bucket>/<path>/<table>` for AWS-backed deployments.
    """
    type: Type21


class TargetConfig(BaseModel):
    """
    Target table coordinates for a model.
    """

    catalog: str
    schema_: str = Field(..., alias="schema")
    table: str


class TestSeverity3(StrEnum):
    """
    Test failure is a hard error — pipeline fails.
    """

    error = "error"


class TestSeverity4(StrEnum):
    """
    Test failure is a warning — pipeline continues.
    """

    warning = "warning"


class TimeGrain(StrEnum):
    """
    Partition granularity for `time_interval` materialization.

    The granularity determines: - The canonical partition key format (see [`TimeGrain::format_str`]). - How `@start_date` / `@end_date` placeholders are computed per partition. - What column types are valid (`hour` requires TIMESTAMP; others accept DATE).
    """

    hour = "hour"
    day = "day"
    month = "month"
    year = "year"


class LineageEdgeRecord(BaseModel):
    source: LineageQualifiedColumn
    target: LineageQualifiedColumn
    transform: str
    """
    Transform kind: "direct", "cast", "expression", etc. Stringified from `rocky_sql::lineage::TransformKind` to avoid pulling schemars into rocky-sql.
    """


class ModelFreshnessConfig(BaseModel):
    """
    Per-model freshness configuration.

    Declares the maximum allowed lag between successive materializations of the model plus the optional timestamp column used by the runtime freshness check.

    The compiler does not enforce the TTL — it's metadata consumed by downstream observability tooling (`dagster-rocky` `FreshnessPolicy`, `rocky doctor --freshness`, etc.). The compiler does however soft-warn (W005) when a model has at least one temporal output column but no `freshness` declaration anywhere in scope (per-model or project-level default).
    """

    max_lag_seconds: conint(ge=0)
    """
    Maximum lag in seconds before the model is considered stale.

    Accepts both `max_lag_seconds` (legacy field name, preserved for existing sidecar fixtures + dagster Pydantic + VS Code bindings) and `expected_lag_seconds` (the documented public-facing name matching dbt freshness + SQLMesh defaults). Both deserialize to the same field; the serialized name stays `max_lag_seconds` so existing JSON/codegen consumers keep working unchanged.
    """
    severity: TestSeverity3 | TestSeverity4 | None = None
    """
    Severity reported when the freshness check trips. Default `warning` keeps the runtime check non-blocking — switch to `error` to fail the pipeline on stale data.
    """
    time_column: str | None = None
    """
    Optional timestamp column used to evaluate freshness at runtime (`MAX(time_column) < NOW() - INTERVAL max_lag_seconds`). When unset the runtime falls back to the model's last-materialization timestamp from the state store.
    """


class StrategyConfig15(BaseModel):
    """
    Partition-keyed materialization. Each run targets specific partitions rather than appending past a watermark. Idempotent and backfill-friendly.

    The model SQL must reference `@start_date` and `@end_date` placeholders, which the runtime substitutes per partition with quoted timestamp literals.
    """

    batch_size: conint(ge=1) | None = 1
    """
    Combine N consecutive partitions into one SQL statement when backfilling. Defaults to 1 (atomic per-partition replacement).
    """
    first_partition: str | None = None
    """
    Lower bound for `--missing` discovery, in canonical key format (e.g., `"2024-01-01"` for daily). Required when `--missing` is used.
    """
    granularity: TimeGrain
    """
    Partition granularity (`hour`, `day`, `month`, `year`).
    """
    lookback: conint(ge=0) | None = 0
    """
    Recompute the previous N partitions on each run, in addition to whatever the CLI selected. Standard handling for late-arriving data.
    """
    time_column: str
    """
    Column on the model output that holds the partition value. Must be a non-nullable date or timestamp column. Validated by the compiler against the typed output schema.
    """
    type: Type14


class StrategyConfig18(BaseModel):
    """
    Microbatch: alias for time_interval with hourly defaults. dbt-compatible naming for partition-based incremental processing.
    """

    granularity: TimeGrain | None = "hour"
    """
    Batch granularity (default: Hour).
    """
    timestamp_column: str
    """
    Timestamp column for micro-batch boundaries.
    """
    type: Type17


class DagNodeOutput(BaseModel):
    """
    One node in the enriched DAG, projected for orchestrators.

    Cross-references the engine's internal `UnifiedNode` with model configs, seeds, and pipeline configs to attach the metadata that orchestrators need (target, strategy, freshness, partition shape).
    """

    depends_on: list[str] | None = None
    """
    Upstream node IDs (derived from DAG edges).
    """
    freshness: ModelFreshnessConfig | None = None
    """
    Per-model freshness expectation from the model sidecar.
    """
    id: str
    """
    Unique identifier: `{kind}:{name}` (e.g. `transformation:stg_orders`).
    """
    kind: str
    """
    Node kind: `source`, `load`, `transformation`, `quality`, `snapshot`, `seed`, `test`, `replication`.
    """
    label: str
    """
    Human-readable label (usually the pipeline or model name).
    """
    partition_shape: PartitionShapeOutput | None = None
    """
    Partition shape for time-interval models. `None` for unpartitioned strategies.
    """
    pipeline: str | None = None
    """
    Pipeline name from `rocky.toml`, if applicable.
    """
    strategy: (
        StrategyConfig12
        | StrategyConfig13
        | StrategyConfig14
        | StrategyConfig15
        | StrategyConfig16
        | StrategyConfig17
        | StrategyConfig18
        | StrategyConfig19
        | StrategyConfig20
        | StrategyConfig21
        | StrategyConfig22
        | None
    ) = None
    """
    Materialization strategy. Present for transformation nodes.
    """
    target: TargetConfig | None = None
    """
    Target table coordinates. Present for transformation, seed, load, and snapshot nodes.
    """


class DagOutput(BaseModel):
    """
    JSON output for `rocky dag`.

    Projects the engine's internal [`UnifiedDag`] into an enriched, orchestrator-friendly shape: every pipeline stage becomes a node with its target table coordinates, materialization strategy, freshness SLA, partition shape, and direct upstream dependencies.

    Consumers (dagster-rocky) can build a complete, connected asset graph from a single `rocky dag --output json` call.

    [`UnifiedDag`]: rocky_core::unified_dag::UnifiedDag
    """

    column_lineage: list[LineageEdgeRecord] | None = None
    """
    Column-level lineage edges across all models. Only populated when `--column-lineage` is passed; empty otherwise.
    """
    command: str
    edges: list[DagEdgeOutput]
    """
    Directed edges between nodes (from → to).
    """
    execution_layers: list[list[str]]
    """
    Topologically-sorted execution layers. Nodes within the same layer have no mutual dependencies and can execute in parallel.
    """
    nodes: list[DagNodeOutput]
    """
    Every stage in the pipeline as an enriched DAG node.
    """
    schema_version: str | None = "1"
    """
    Version of the graph-export contract this payload conforms to.

    Distinct from `version` (the engine release, which churns every release): `schema_version` identifies the *shape* of the graph export — the node/edge/lineage fields orchestrators build an asset graph from. It is bumped only on a backward-incompatible change to that shape, so an orchestrator can pin against it across engine releases. Additive, backward-compatible field additions do not bump it (and surface through codegen-drift CI instead). Always emitted; older payloads that predate the field are treated as `"1"`.
    """
    summary: DagSummaryOutput
    """
    Summary counts for the DAG.
    """
    version: str
