# generated by datamodel-codegen:
#   filename:  doctor.schema.json
#   timestamp: 2026-04-13T18:41:57+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, conint


class HealthStatus(StrEnum):
    """
    Health check status.
    """

    healthy = "healthy"
    warning = "warning"
    critical = "critical"


class HealthCheck(BaseModel):
    """
    A single health check result.
    """

    duration_ms: conint(ge=0)
    message: str
    name: str
    status: HealthStatus


class DoctorOutput(BaseModel):
    """
    Doctor output structure.
    """

    checks: list[HealthCheck]
    command: str
    overall: str
    suggestions: list[str]
