# generated by datamodel-codegen:
#   filename:  hooks_test.schema.json

from __future__ import annotations

from pydantic import BaseModel


class HooksTestOutput(BaseModel):
    """
    JSON output for `rocky hooks test <event>`.
    """

    event: str
    message: str | None = None
    result: str | None = None
    """
    Free-form Debug rendering of the hook result, when applicable.
    """
    status: str
    """
    One of "no_hooks", "continue", "abort".
    """
