# generated by datamodel-codegen:
#   filename:  hooks_list.schema.json
#   timestamp: 2026-04-15T23:42:16+00:00

from __future__ import annotations

from pydantic import BaseModel, conint


class HookEntry(BaseModel):
    command: str
    env_keys: list[str]
    event: str
    on_failure: str
    timeout_ms: conint(ge=0)


class HooksListOutput(BaseModel):
    """
    JSON output for `rocky hooks list`.
    """

    hooks: list[HookEntry]
    total: conint(ge=0)
