# generated by datamodel-codegen:
#   filename:  import_dbt.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field, conint


class ImportDbtEmission(BaseModel):
    """
    Files-on-disk metadata for the runnable Rocky repo emitted by `rocky import-dbt --output-dir <out>`.

    Consumers (Dagster, vscode) treat this block as the contract for "where the importer wrote things." Absence of the block on `ImportDbtOutput` means no repo was emitted (e.g. dry-run mode in a follow-up).
    """

    adapter_type: str
    """
    Rocky adapter type written into `[adapter]` (`duckdb` / `databricks` / …).
    """
    migration_notes_path: str
    """
    Path to the generated `MIGRATION-NOTES.md`.
    """
    models_skipped_count: conint(ge=0)
    """
    Number of dbt model files seen but not translated (failed entries).
    """
    models_translated_count: conint(ge=0)
    """
    Number of dbt models successfully translated and written under `models/`.
    """
    original_dbt_adapter_type: str
    """
    dbt profile `type` value the importer mapped from. Useful when the caller passed `--target-adapter` and we want to surface the original.
    """
    out_dir: str
    """
    Resolved output directory.
    """
    required_env_vars: list[str]
    """
    Env vars referenced by the emitted `[adapter]` block. Surfaced in `MIGRATION-NOTES.md` under "Required env vars".
    """
    rocky_toml_path: str
    """
    Path to the generated `rocky.toml`.
    """
    seeds_copied_count: conint(ge=0)
    """
    Number of files copied from `<dbt_project>/seeds/` into `<out>/seeds/`.
    """


class ImportDbtFailure(BaseModel):
    name: str
    reason: str


class ImportDbtHookKind(StrEnum):
    """
    Lifecycle hook kind for [`ImportDbtStructuredWarning::DroppedHook`].
    """

    pre = "pre"
    post = "post"


class Kind(StrEnum):
    unsupported_materialization = "unsupported_materialization"


class ImportDbtStructuredWarning1(BaseModel):
    """
    A dbt materialization with no direct Rocky equivalent. The importer fell back to the closest match (typically `full_refresh`).
    """

    action: str
    dbt_materialization: str
    kind: Kind
    model: str


class Kind33(StrEnum):
    dropped_databricks_tags = "dropped_databricks_tags"


class ImportDbtStructuredWarning2(BaseModel):
    """
    `databricks_tags` block dropped — Rocky's `[classification]` block + `rocky-databricks` governance surface covers the same use case but requires manual config.
    """

    kind: Kind33
    model: str
    tags: dict[str, str]


class Kind34(StrEnum):
    dropped_hook = "dropped_hook"


class ImportDbtStructuredWarning3(BaseModel):
    """
    `pre_hook` or `post_hook` dropped — Rocky supports lifecycle hooks via the `[[hook]]` block in `rocky.toml`.
    """

    hook_kind: ImportDbtHookKind
    kind: Kind34
    model: str
    sql: str


class Kind35(StrEnum):
    dropped_on_schema_change = "dropped_on_schema_change"


class ImportDbtStructuredWarning4(BaseModel):
    """
    `on_schema_change` dropped — Rocky exposes the equivalent via per-pipeline `[drift]` policy.
    """

    dbt_value: str
    kind: Kind35
    model: str
    rocky_equivalent: str


class Kind36(StrEnum):
    unresolvable_macro = "unresolvable_macro"


class ImportDbtStructuredWarning5(BaseModel):
    """
    A custom Jinja macro call survived `dbt compile` — defined out-of-tree. The user needs to hand-port the macro.
    """

    first_call_site_line: conint(ge=0)
    kind: Kind36
    macro_name: str
    model: str


class Kind37(StrEnum):
    microbatch_missing_event_time = "microbatch_missing_event_time"


class ImportDbtStructuredWarning6(BaseModel):
    """
    A microbatch model is missing the required `event_time` field — the importer fell back to `full_refresh`.
    """

    kind: Kind37
    model: str


class ImportDbtWarning(BaseModel):
    category: str
    message: str
    model: str
    suggestion: str | None = None


class ImportDbtOutput(BaseModel):
    """
    JSON output for `rocky import-dbt`.

    The `report` field is the per-model migration report from `rocky_compiler::import::report::generate_report`. We hold it as `serde_json::Value` (typed as `any` in JSON Schema) to avoid pulling `JsonSchema` derives all the way through `rocky-compiler::import`. The downstream Pydantic/TS bindings will see it as a free-form object.
    """

    command: str
    dbt_version: str | None = None
    emission: ImportDbtEmission | None = None
    """
    Metadata about the emitted Rocky repo. Present when `--output-dir` triggered repo emission (the default for `rocky import-dbt`). Absent when emission was skipped or failed before disk writes.
    """
    failed: conint(ge=0)
    failed_details: list[ImportDbtFailure]
    import_method: str
    imported: conint(ge=0)
    imported_models: list[str]
    macros_detected: conint(ge=0)
    project_name: str | None = None
    report: Any
    """
    Free-form per-model migration report payload.
    """
    sources_found: conint(ge=0)
    sources_mapped: conint(ge=0)
    structured_warnings: (
        list[
            ImportDbtStructuredWarning1
            | ImportDbtStructuredWarning2
            | ImportDbtStructuredWarning3
            | ImportDbtStructuredWarning4
            | ImportDbtStructuredWarning5
            | ImportDbtStructuredWarning6
        ]
        | None
    ) = Field([], validate_default=True)
    """
    Typed structured warnings — payload-carrying variants for dbt config Rocky can't auto-translate (dropped tags, dropped hooks, unresolvable macros, etc.). Coexists with `warning_details` — orchestrators that don't know about this field still see the flat string warnings under `warning_details`.
    """
    tests_converted: conint(ge=0)
    tests_converted_custom: conint(ge=0)
    tests_found: conint(ge=0)
    tests_skipped: conint(ge=0)
    version: str
    warning_details: list[ImportDbtWarning]
    warnings: conint(ge=0)
