# generated by datamodel-codegen:
#   filename:  import_dbt.schema.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, conint


class ImportDbtEmission(BaseModel):
    """
    Files-on-disk metadata for the runnable Rocky repo emitted by `rocky import-dbt --output-dir <out>`.

    Consumers (Dagster, vscode) treat this block as the contract for "where the importer wrote things." Absence of the block on `ImportDbtOutput` means no repo was emitted (e.g. dry-run mode in a follow-up).
    """

    adapter_type: str
    """
    Rocky adapter type written into `[adapter]` (`duckdb` / `databricks` / …).
    """
    migration_notes_path: str
    """
    Path to the generated `MIGRATION-NOTES.md`.
    """
    models_skipped_count: conint(ge=0)
    """
    Number of dbt model files seen but not translated (failed entries).
    """
    models_translated_count: conint(ge=0)
    """
    Number of dbt models successfully translated and written under `models/`.
    """
    original_dbt_adapter_type: str
    """
    dbt profile `type` value the importer mapped from. Useful when the caller passed `--target-adapter` and we want to surface the original.
    """
    out_dir: str
    """
    Resolved output directory.
    """
    required_env_vars: list[str]
    """
    Env vars referenced by the emitted `[adapter]` block. Surfaced in `MIGRATION-NOTES.md` under "Required env vars".
    """
    rocky_toml_path: str
    """
    Path to the generated `rocky.toml`.
    """
    seeds_copied_count: conint(ge=0)
    """
    Number of files copied from `<dbt_project>/seeds/` into `<out>/seeds/`.
    """


class ImportDbtFailure(BaseModel):
    name: str
    reason: str


class ImportDbtWarning(BaseModel):
    category: str
    message: str
    model: str
    suggestion: str | None = None


class ImportDbtOutput(BaseModel):
    """
    JSON output for `rocky import-dbt`.

    The `report` field is the per-model migration report from `rocky_compiler::import::report::generate_report`. We hold it as `serde_json::Value` (typed as `any` in JSON Schema) to avoid pulling `JsonSchema` derives all the way through `rocky-compiler::import`. The downstream Pydantic/TS bindings will see it as a free-form object.
    """

    command: str
    dbt_version: str | None = None
    emission: ImportDbtEmission | None = None
    """
    Metadata about the emitted Rocky repo. Present when `--output-dir` triggered repo emission (the default for `rocky import-dbt`). Absent when emission was skipped or failed before disk writes.
    """
    failed: conint(ge=0)
    failed_details: list[ImportDbtFailure]
    import_method: str
    imported: conint(ge=0)
    imported_models: list[str]
    macros_detected: conint(ge=0)
    project_name: str | None = None
    report: Any
    """
    Free-form per-model migration report payload.
    """
    sources_found: conint(ge=0)
    sources_mapped: conint(ge=0)
    tests_converted: conint(ge=0)
    tests_converted_custom: conint(ge=0)
    tests_found: conint(ge=0)
    tests_skipped: conint(ge=0)
    version: str
    warning_details: list[ImportDbtWarning]
    warnings: conint(ge=0)
