# generated by datamodel-codegen:
#   filename:  import_dbt.schema.json
#   timestamp: 2026-04-15T12:34:08+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, conint


class ImportDbtFailure(BaseModel):
    name: str
    reason: str


class ImportDbtWarning(BaseModel):
    category: str
    message: str
    model: str
    suggestion: str | None = None


class ImportDbtOutput(BaseModel):
    """
    JSON output for `rocky import-dbt`.

    The `report` field is the per-model migration report from `rocky_compiler::import::report::generate_report`. We hold it as `serde_json::Value` (typed as `any` in JSON Schema) to avoid pulling `JsonSchema` derives all the way through `rocky-compiler::import`. The downstream Pydantic/TS bindings will see it as a free-form object.
    """

    command: str
    dbt_version: str | None = None
    failed: conint(ge=0)
    failed_details: list[ImportDbtFailure]
    import_method: str
    imported: conint(ge=0)
    imported_models: list[str]
    macros_detected: conint(ge=0)
    project_name: str | None = None
    report: Any
    """
    Free-form per-model migration report payload.
    """
    sources_found: conint(ge=0)
    sources_mapped: conint(ge=0)
    tests_converted: conint(ge=0)
    tests_converted_custom: conint(ge=0)
    tests_found: conint(ge=0)
    tests_skipped: conint(ge=0)
    version: str
    warning_details: list[ImportDbtWarning]
    warnings: conint(ge=0)
