# generated by datamodel-codegen:
#   filename:  lineage.schema.json
#   timestamp: 2026-04-15T23:28:11+00:00

from __future__ import annotations

from pydantic import BaseModel


class LineageColumnDef(BaseModel):
    name: str


class LineageQualifiedColumn(BaseModel):
    column: str
    model: str


class LineageEdgeRecord(BaseModel):
    source: LineageQualifiedColumn
    target: LineageQualifiedColumn
    transform: str
    """
    Transform kind: "direct", "cast", "expression", etc. Stringified from `rocky_sql::lineage::TransformKind` to avoid pulling schemars into rocky-sql.
    """


class LineageOutput(BaseModel):
    """
    JSON output for `rocky lineage <model>` (model lineage shape).

    When invoked with `--column <col>` (or `model.column` syntax), the dispatch returns `ColumnLineageOutput` instead — the two shapes share version/command/model headers but otherwise differ enough to keep separate.
    """

    columns: list[LineageColumnDef]
    command: str
    downstream: list[str]
    edges: list[LineageEdgeRecord]
    model: str
    upstream: list[str]
    version: str
