# generated by datamodel-codegen:
#   filename:  metrics.schema.json
#   timestamp: 2026-04-15T01:23:11+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, conint


class ColumnTrendPoint(BaseModel):
    null_rate: float | None = None
    row_count: conint(ge=0)
    run_id: str
    timestamp: AwareDatetime


class MetricsAlert(BaseModel):
    column: str | None = None
    message: str
    run_id: str
    severity: str
    type: str


class MetricsSnapshotEntry(BaseModel):
    freshness_lag_seconds: conint(ge=0) | None = None
    null_rates: dict[str, float]
    row_count: conint(ge=0)
    run_id: str
    timestamp: AwareDatetime


class MetricsOutput(BaseModel):
    """
    JSON output for `rocky metrics`.

    All optional fields are present-or-absent depending on the flags (`--trend`, `--alerts`, `--column`). The empty case (no snapshots available) sets `message` and leaves the collections empty.
    """

    alerts: list[MetricsAlert]
    column: str | None = None
    column_trend: list[ColumnTrendPoint]
    command: str
    count: conint(ge=0)
    message: str | None = None
    model: str
    snapshots: list[MetricsSnapshotEntry]
    version: str
