# generated by datamodel-codegen:
#   filename:  model_history.schema.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, conint


class ModelExecutionRecord(BaseModel):
    """
    One model execution from the state store, mirroring `rocky_core::state::ModelExecution`.
    """

    duration_ms: conint(ge=0)
    rows_affected: conint(ge=0) | None = None
    sql_hash: str
    started_at: AwareDatetime
    status: str


class ModelHistoryOutput(BaseModel):
    """
    JSON output for `rocky history --model <name>`.
    """

    command: str
    count: conint(ge=0)
    executions: list[ModelExecutionRecord]
    model: str
    version: str
