# generated by datamodel-codegen:
#   filename:  plan.schema.json
#   timestamp: 2026-04-15T12:34:08+00:00

from __future__ import annotations

from pydantic import BaseModel


class PlannedStatement(BaseModel):
    purpose: str
    sql: str
    target: str


class PlanOutput(BaseModel):
    """
    JSON output for `rocky plan`.
    """

    command: str
    filter: str
    statements: list[PlannedStatement]
    version: str
