# generated by datamodel-codegen:
#   filename:  preview_cost.schema.json

from __future__ import annotations

from pydantic import BaseModel, conint


class PreviewCostSummary(BaseModel):
    """
    Aggregate cost rollup for [`PreviewCostOutput`].
    """

    delta_usd: float | None = None
    """
    `total_branch_cost_usd - total_base_cost_usd`. Positive = the PR costs more to run than `main`.
    """
    models_skipped_via_copy: conint(ge=0)
    """
    Number of models that did not run on the branch because they were copied from base. Their savings show up below.
    """
    savings_from_copy_usd: float | None = None
    """
    Sum of `base_cost_usd` for every copied model — the cost the PR avoided by copying instead of re-running. `None` when no base costs are available for the copied models.
    """
    total_base_cost_usd: float | None = None
    """
    Sum of every per-model `base_cost_usd` (limited to models in the prune set — copied models contribute 0 here, accounted for in `savings_from_copy_usd`).
    """
    total_branch_cost_usd: float | None = None
    """
    Sum of every per-model `branch_cost_usd` that produced a number.
    """


class PreviewModelCostDelta(BaseModel):
    """
    Per-model cost delta.
    """

    base_bytes_scanned: conint(ge=0) | None = None
    base_cost_usd: float | None = None
    base_duration_ms: conint(ge=0)
    branch_bytes_scanned: conint(ge=0) | None = None
    branch_cost_usd: float | None = None
    branch_duration_ms: conint(ge=0)
    delta_usd: float | None = None
    model_name: str
    skipped_via_copy: bool
    """
    `true` if this model was copied from base instead of re-run. When true, `branch_*` fields are `None` / `0` and the savings for this row roll into [`PreviewCostSummary::savings_from_copy_usd`].
    """


class PreviewCostOutput(BaseModel):
    """
    JSON output for `rocky preview cost`.

    Diff layer over `rocky cost latest`'s machinery. Per-model deltas are computed by looking up the latest base-schema `RunRecord` and the branch run's `RunRecord` and subtracting field-by-field.

    `models_skipped_via_copy` is the prune-set complement: copied models did not run on the branch, so their delta is `None` and their savings accrue to `savings_from_copy_usd`.
    """

    base_run_id: str | None = None
    """
    `RunRecord` id for the latest base-schema run that the branch is being compared against. `None` when no base run exists.
    """
    branch_name: str
    branch_run_id: str
    """
    `RunRecord` id for the branch execution. Empty when the branch run was a no-op (every changed model pruned to zero downstream).
    """
    command: str
    markdown: str
    per_model: list[PreviewModelCostDelta]
    summary: PreviewCostSummary
    version: str
