# generated by datamodel-codegen:
#   filename:  preview_diff.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field, conint


class PreviewColumnTypeChange(BaseModel):
    """
    One column-type change entry.
    """

    from_: str = Field(..., alias="from")
    name: str
    to: str


class PreviewDiffSummary(BaseModel):
    """
    Aggregate diff counts for [`PreviewDiffOutput`].
    """

    any_coverage_warning: bool
    """
    `true` if **any** per-model diff carries `sampling_window.coverage_warning = true`.
    """
    models_unchanged: conint(ge=0)
    models_with_changes: conint(ge=0)
    total_rows_added: conint(ge=0)
    total_rows_changed: conint(ge=0)
    total_rows_removed: conint(ge=0)


class PreviewRowSampleChange(BaseModel):
    """
    One `(column, base, branch)` triple in [`PreviewRowSample::changes`].
    """

    base_value: str
    branch_value: str
    column: str


class PreviewSamplingWindow(BaseModel):
    """
    Sampling-window metadata surfaced verbatim in the PR comment.

    `coverage_warning = true` flags that the row count outside the sampling window is non-trivial; reviewers should not infer "no change" from a clean sample if this flag is set.
    """

    coverage: str
    """
    One of `"first_n_by_order"` (Phase 2) or `"checksum_bisection"` (Phase 2.5 lift, not yet shipped).
    """
    coverage_warning: bool
    limit: conint(ge=0)
    ordered_by: str


class PreviewStructuralDiff(BaseModel):
    """
    Column-level structural diff. Mirrors the shape produced by `rocky ci-diff` at the column granularity.
    """

    added_columns: list[str]
    removed_columns: list[str]
    type_changes: list[PreviewColumnTypeChange]
    """
    One entry per column whose type changed. Each carries `name`, `from`, `to`.
    """


class PreviewRowSample(BaseModel):
    """
    One representative changed row in [`PreviewSampledRowDiff::samples`].
    """

    changes: list[PreviewRowSampleChange]
    """
    Pairs of `(column_name, base_value, branch_value)` for every column that differs on this row.
    """
    primary_key: str


class PreviewSampledRowDiff(BaseModel):
    """
    Sampled row-level diff. All counts are over the sampling window.
    """

    rows_added: conint(ge=0)
    rows_changed: conint(ge=0)
    rows_removed: conint(ge=0)
    samples: list[PreviewRowSample]
    """
    Up to `--max-samples` (default 5) representative changed rows for human review. Pure noise when sampling found no change.
    """


class PreviewModelDiff(BaseModel):
    """
    Per-model diff. Combines structural (column-level) and sampled (row-level) findings.
    """

    model_name: str
    sampled: PreviewSampledRowDiff
    sampling_window: PreviewSamplingWindow
    structural: PreviewStructuralDiff


class PreviewDiffOutput(BaseModel):
    """
    JSON output for `rocky preview diff`.

    Combines the structural diff (column added/removed/type-changed) from the existing `rocky_core::ci_diff` machinery with a sampled row-level diff that extends the `rocky_core::compare`/`shadow` kernel.

    **Sampling correctness ceiling.** Phase 2 sampling reads `LIMIT N` rows ordered by primary key (or first column). Changes outside that window appear as no-change unless the row count itself differs. `sampling_window.coverage_warning = true` flags this risk on the per-model level so reviewers don't infer false coverage. A checksum-bisection exhaustive diff is the Phase 2.5 lift.
    """

    base_ref: str
    branch_name: str
    command: str
    markdown: str
    """
    Pre-rendered Markdown suitable for posting as a GitHub PR comment.
    """
    models: list[PreviewModelDiff]
    summary: PreviewDiffSummary
    version: str
