# generated by datamodel-codegen:
#   filename:  profile_storage.schema.json

from __future__ import annotations

from pydantic import BaseModel


class EncodingRecommendationOutput(BaseModel):
    column: str
    data_type: str
    estimated_cardinality: str
    reasoning: str
    recommended_encoding: str


class ProfileStorageOutput(BaseModel):
    """
    JSON output for `rocky profile-storage`.
    """

    command: str
    model: str
    profile_sql: str
    recommendations: list[EncodingRecommendationOutput]
    version: str
