# generated by datamodel-codegen:
#   filename:  replay.schema.json

from __future__ import annotations

from pydantic import BaseModel, conint


class ReplayModelOutput(BaseModel):
    """
    A single model execution inside a replayed run.
    """

    bytes_scanned: conint(ge=0) | None = None
    bytes_written: conint(ge=0) | None = None
    duration_ms: conint(ge=0)
    finished_at: str
    model_name: str
    rows_affected: conint(ge=0) | None = None
    sql_hash: str
    started_at: str
    status: str


class ReplayOutput(BaseModel):
    """
    JSON output for `rocky replay <run_id|latest>`.

    Inspection-only surface over the state store's [`RunRecord`]: shows every model that ran, with the SQL hash, row counts, bytes, and timings captured at the time. Re-execution (with pinned inputs + content-addressed writes) is deferred to a follow-up when the Arc-1 storage path arrives.
    """

    command: str
    config_hash: str
    finished_at: str
    models: list[ReplayModelOutput]
    run_id: str
    started_at: str
    status: str
    trigger: str
    version: str
