# generated by datamodel-codegen:
#   filename:  rocky_project.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class AdapterKind3(StrEnum):
    """
    Warehouse data movement (reads / writes table bytes).
    """

    data = "data"


class AdapterKind4(StrEnum):
    """
    Metadata-only discovery (enumerates source schemas / connectors).
    """

    discovery = "discovery"


class AggregateCmp(StrEnum):
    """
    Comparison operator for `Aggregate` assertions. Each comparison has a long form (`lt`, `lte`, `gt`, `gte`, `eq`, `ne`) and an equivalent symbolic alias (`<`, `<=`, `>`, `>=`, `==`, `!=`).
    """

    lt = "lt"
    field_ = "<"
    lte = "lte"
    field__ = "<="
    gt = "gt"
    field__1 = ">"
    gte = "gte"
    field___1 = ">="
    eq = "eq"
    field___2 = "=="
    ne = "ne"
    field___3 = "!="


class AggregateOp1(StrEnum):
    """
    `SUM(column)` — column required.
    """

    sum = "sum"


class AggregateOp2(StrEnum):
    """
    `COUNT(*)` — column ignored.
    """

    count = "count"


class AggregateOp3(StrEnum):
    """
    `AVG(column)` — column required.
    """

    avg = "avg"


class AggregateOp4(StrEnum):
    """
    `MIN(column)` — column required.
    """

    min = "min"


class AggregateOp5(StrEnum):
    """
    `MAX(column)` — column required.
    """

    max = "max"


class BindingType(StrEnum):
    """
    Workspace binding access level.
    """

    READ_WRITE = "READ_WRITE"
    READ_ONLY = "READ_ONLY"


class BudgetBreachAction(StrEnum):
    """
    What to do when a [`BudgetConfig`] limit is exceeded by an actual run.

    `Warn` always fires the `budget_breach` event; `Error` additionally causes `rocky run` to exit with a non-zero status so orchestrators can gate downstream work on the breach.
    """

    warn = "warn"
    error = "error"


class BudgetConfig(BaseModel):
    """
    Declarative run-level budget for cost, duration, and (future) data volume. All limits are optional; when unset the dimension is not enforced.

    A breach is detected at end of run by comparing [`BudgetConfig`] against the observed [`crate::cost::compute_observed_cost_usd`] total and the run wall clock. Per-model budgets are deferred to a later wave — the first iteration enforces run-level totals only.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    max_duration_ms: conint(ge=0) | None = None
    """
    Maximum allowed run wall-clock duration in milliseconds.
    """
    max_usd: float | None = None
    """
    Maximum allowed run cost in USD. When set and exceeded, emits `budget_breach` on the event bus; when paired with `on_breach = "error"`, also fails the run.
    """
    on_breach: BudgetBreachAction | None = "warn"
    """
    What to do when a limit is breached. Defaults to `warn` — fire the event, keep the run successful. Set to `error` to fail the run.
    """


class CompositeKind1(StrEnum):
    """
    `(col1, col2, ...)` is unique across all rows.
    """

    unique = "unique"


class CompositeKind(RootModel[CompositeKind1]):
    root: CompositeKind1
    """
    Kind of composite (multi-column) assertion.
    """


class ConcurrencyMode1(StrEnum):
    """
    Concurrency strategy: the literal `"adaptive"` for AIMD-based throttling, or a positive integer for fixed concurrency.
    """

    adaptive = "adaptive"


class CostSection(BaseModel):
    """
    Cost estimation configuration.

    Controls pricing assumptions used by [`crate::optimize::recommend_strategy`] when analyzing materialization costs and generating recommendations.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    compute_cost_per_dbu: float | None = 0.4
    """
    Cost per DBU (default: $0.40).
    """
    min_history_runs: conint(ge=0) | None = 5
    """
    Minimum runs before making cost recommendations.
    """
    storage_cost_per_gb_month: float | None = 0.023
    """
    Cost per GB of storage per month (default: $0.023).
    """
    warehouse_size: str | None = "Medium"
    """
    Warehouse size for cost estimation (e.g., "Small", "Medium", "Large").
    """


class Dialect(StrEnum):
    """
    Target dialect for transpilation.

    Serializes lowercase (`databricks`, `snowflake`, `bigquery`, `duckdb`) so the long-form names can sit in `rocky.toml` under the `[portability]` block without translation. The CLI's short-form flag values (`dbx`/`sf`/`bq`/`duckdb`) are kept as ergonomics in the `TargetDialect` clap enum and convert to this type at the boundary.
    """

    databricks = "databricks"
    snowflake = "snowflake"
    bigquery = "bigquery"
    duckdb = "duckdb"


class DiscoveryConfig(BaseModel):
    """
    Discovery configuration within a pipeline source.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    adapter: str | None = "default"
    """
    Name of the adapter to use for discovery (references a key in `[adapter.*]`). Defaults to `"default"`.
    """


class ExecutionConfig(BaseModel):
    """
    Controls parallelism and error handling for table processing.

    Rocky processes tables within a run concurrently using async tasks. Tune `concurrency` based on your warehouse capacity.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    concurrency: ConcurrencyMode1 | conint(ge=1) | None = "adaptive"
    """
    Concurrency strategy (default: `"adaptive"`).

    - `"adaptive"` — AIMD throttle that starts at 32 and adjusts based on rate-limit signals. Best for remote warehouses (Databricks, Snowflake). - An integer (e.g. `8`) — fixed concurrency, always this many in-flight tables. Use for local adapters (DuckDB) or when you know the limit. - `1` — serial execution.
    """
    error_rate_abort_pct: conint(ge=0) | None = 50
    """
    Abort remaining tables if error rate exceeds this percentage (0-100). Prevents wasting compute when the warehouse is unhealthy. Default: 50 (abort if more than half of completed tables failed). Set to 0 to disable.
    """
    fail_fast: bool | None = False
    """
    If true, abort all remaining tables on first error. If false, process all tables and report errors at the end (partial success).
    """
    table_retries: conint(ge=0) | None = 1
    """
    Number of times to retry failed tables after the initial parallel phase. Default: 1. Set to 0 to disable auto-retry.
    """


class FailureAction1(StrEnum):
    """
    Stop pipeline immediately.
    """

    abort = "abort"


class FailureAction2(StrEnum):
    """
    Log warning, continue execution.
    """

    warn = "warn"


class FailureAction3(StrEnum):
    """
    Silent continue.
    """

    ignore = "ignore"


class GrantConfig(BaseModel):
    """
    A permission grant to apply to catalogs or schemas.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    permissions: list[str]
    principal: str


class HookConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    command: str
    """
    Shell command to execute (passed to `sh -c`).
    """
    env: dict[str, str] | None = {}
    """
    Extra environment variables passed to the hook process.
    """
    on_failure: FailureAction1 | FailureAction2 | FailureAction3 | None = "warn"
    """
    What to do if the hook command exits non-zero or times out.
    """
    timeout_ms: conint(ge=0) | None = 30000
    """
    Maximum time to wait for the hook to complete.
    """


class HookConfigOrList(RootModel[HookConfig | list[HookConfig]]):
    root: HookConfig | list[HookConfig]
    """
    Supports both single-hook and multi-hook syntax per event.

    Single: `[hook.on_pipeline_start]` Multiple: `[[hook.on_after_checks]]`
    """


class LoadFileFormat(StrEnum):
    """
    File format for load pipelines, parsed from TOML.

    Mirrors `rocky_adapter_sdk::FileFormat` but lives in rocky-core to avoid a hard dependency from config parsing to the adapter SDK.
    """

    csv = "csv"
    parquet = "parquet"
    json_lines = "json_lines"


class LoadOptionsConfig(BaseModel):
    """
    Load-specific options parsed from TOML.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    batch_size: conint(ge=0) | None = 10000
    """
    Number of rows per INSERT batch. Default: 10,000.
    """
    create_table: bool | None = True
    """
    Create the target table if it does not exist. Default: true.
    """
    csv_delimiter: str | None = ","
    """
    CSV-specific: field delimiter character. Default: `,`.
    """
    csv_has_header: bool | None = True
    """
    CSV-specific: whether the first row is a header. Default: true.
    """
    truncate_first: bool | None = False
    """
    Truncate the target table before loading. Default: false.
    """


class MetadataColumnConfig(BaseModel):
    """
    A metadata column added during replication (e.g., `_loaded_by`).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    type: str
    value: str


class Type(StrEnum):
    replication = "replication"


class Type15(StrEnum):
    transformation = "transformation"


class Type16(StrEnum):
    quality = "quality"


class Type17(StrEnum):
    snapshot = "snapshot"


class Type18(StrEnum):
    load = "load"


class PortabilityConfig(BaseModel):
    """
    Project-wide dialect portability configuration.

    Lives at the top level because a Rocky project targets one warehouse; per-pipeline overrides aren't supported yet (no demand signal). The `allow` list applies to every model — a per-model override is the `-- rocky-allow: <constructs>` pragma in the model SQL itself, parsed by [`rocky_sql::pragma`].
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    allow: list[str] | None = []
    """
    Project-wide allow-list of construct labels (case-insensitive, matched against `PortabilityIssue::construct`). Useful for blanket exemptions like `allow = ["QUALIFY"]` when a project standardizes on a specific extension. For per-model exemptions prefer the `-- rocky-allow: <construct>` pragma over expanding this list.
    """
    target_dialect: Dialect | None = None
    """
    Target dialect for the portability lint. When unset, no lint runs (matches the wave-1 "flag opt-in" behavior). The CLI flag overrides this if both are present.
    """


class Type19(StrEnum):
    not_null = "not_null"


class Type20(StrEnum):
    unique = "unique"


class Type21(StrEnum):
    accepted_values = "accepted_values"


class Type22(StrEnum):
    relationships = "relationships"


class Type23(StrEnum):
    expression = "expression"


class Type24(StrEnum):
    row_count_range = "row_count_range"


class Type25(StrEnum):
    in_range = "in_range"


class Type26(StrEnum):
    regex_match = "regex_match"


class Type27(StrEnum):
    aggregate = "aggregate"


class Type28(StrEnum):
    composite = "composite"


class Type29(StrEnum):
    not_in_future = "not_in_future"


class Type30(StrEnum):
    older_than_n_days = "older_than_n_days"


class QualityTargetConfig(BaseModel):
    """
    Target configuration for quality pipelines (adapter reference only).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    adapter: str | None = "default"
    """
    Name of the adapter to use (references a key in `[adapter.*]`).
    """


class QuarantineMode1(StrEnum):
    """
    Write a `<table>__valid` table with passing rows and a `<table>__quarantine` table with failing rows (plus per-assertion `_error_<name>` label columns). Original table untouched. Default.
    """

    split = "split"


class QuarantineMode2(StrEnum):
    """
    Replace `<table>` in place with a copy that has per-assertion `_error_<name>` label columns set for failing rows. Rewrites the source — use with care; not recommended when the source is a raw replication target.
    """

    tag = "tag"


class QuarantineMode3(StrEnum):
    """
    Write only the `<table>__valid` half. Failing rows are discarded. Irreversible at run-time.
    """

    drop = "drop"


class RetryConfig(BaseModel):
    """
    Retry policy for transient warehouse errors (HTTP 429/503, rate limits, timeouts).

    Rocky retries transient errors with exponential backoff and optional jitter to prevent thundering herd across concurrent runs.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    backoff_multiplier: float | None = 2.0
    """
    Backoff multiplier applied after each retry (e.g. 2.0 = double each time).
    """
    circuit_breaker_recovery_timeout_secs: conint(ge=0) | None = None
    """
    Seconds the breaker will stay `Open` before a single trial request is allowed through (half-open state). On trial success the breaker closes and resumes normal traffic; on trial failure it re-opens immediately. `None` preserves the pre-Arc-3 "manual-reset-only" behaviour — a tripped breaker stays tripped for the rest of the run.
    """
    circuit_breaker_threshold: conint(ge=0) | None = 5
    """
    Circuit breaker: trip after this many consecutive transient failures across statements. Once tripped, all subsequent statements fail immediately without attempting execution. Default: 5. Set to 0 to disable.
    """
    initial_backoff_ms: conint(ge=0) | None = 1000
    """
    Initial backoff duration in milliseconds before the first retry.
    """
    jitter: bool | None = True
    """
    Add random jitter to prevent concurrent runs from retrying in lockstep.
    """
    max_backoff_ms: conint(ge=0) | None = 30000
    """
    Maximum backoff duration in milliseconds (caps exponential growth).
    """
    max_retries: conint(ge=0) | None = 3
    """
    Maximum number of retry attempts. Set to 0 to disable retries (e.g. for CI).
    """
    max_retries_per_run: conint(ge=0) | None = None
    """
    Cross-statement retry budget for a single run (§P2.7). When set, adapters construct a [`crate::retry_budget::RetryBudget`] from this value and decrement it on every retry; once exhausted, remaining statements fail fast with adapter-specific `RetryBudgetExhausted` errors instead of burning the warehouse's rate-limit quota.

    `None` (default) keeps legacy behaviour — per-statement [`RetryConfig::max_retries`] is the only bound. `Some(0)` means no retries are allowed for the whole run.
    """


class RunRetryConfig(BaseModel):
    """
    Top-level retry configuration applied across every adapter for this run. See [`RockyConfig::retry`] for the cross-adapter semantics this unlocks.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    max_retries_per_run: conint(ge=0) | None = None
    """
    Total number of retries allowed across every adapter for this run. `None` means no cross-adapter cap (each adapter's own `retry.max_retries_per_run` still applies in isolation).
    """


class SchemaEvolutionConfig(BaseModel):
    """
    Schema evolution configuration.

    Controls how Rocky handles columns that disappear from the source but still exist in the target table. Instead of immediately dropping them, Rocky can keep them for a grace period (filling with NULL) so downstream consumers have time to adapt.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    grace_period_days: conint(ge=0) | None = 7
    """
    Number of days to keep a dropped column before removing it from the target table. During this window the column is filled with NULL for new rows and a warning is emitted on every run. Default: 7.
    """


class SchemaPatternConfig(BaseModel):
    """
    Schema pattern configuration from TOML, converted to [`SchemaPattern`] at runtime.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    components: list[str]
    prefix: str
    separator: str


class SnapshotSourceConfig(BaseModel):
    """
    Source table for a snapshot pipeline (explicit single-table reference).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    adapter: str | None = "default"
    """
    Name of the adapter to use (references a key in `[adapter.*]`).
    """
    catalog: str
    schema_: str = Field(..., alias="schema")
    table: str


class StateBackend1(StrEnum):
    """
    State stored on local disk (default). No sync needed.
    """

    local = "local"


class StateBackend2(StrEnum):
    """
    State synced to/from an S3 bucket via the `object_store` crate.
    """

    s3 = "s3"


class StateBackend3(StrEnum):
    """
    State synced to/from a Google Cloud Storage bucket.
    """

    gcs = "gcs"


class StateBackend4(StrEnum):
    """
    State synced to/from a Valkey/Redis instance.
    """

    valkey = "valkey"


class StateBackend5(StrEnum):
    """
    Tiered: Valkey (fast) with S3 fallback (durable).
    """

    tiered = "tiered"


class StateConfig(BaseModel):
    """
    State persistence configuration.

    Controls where Rocky stores watermarks and anomaly history between runs. On ephemeral environments (EKS pods), use S3, GCS, or Valkey for persistence.

    When both S3 and Valkey are configured (`backend = "tiered"`): - Download: Valkey first (fast), S3 fallback (durable) - Upload: write to both Valkey + S3
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    backend: (
        StateBackend1
        | StateBackend2
        | StateBackend3
        | StateBackend4
        | StateBackend5
        | None
    ) = "local"
    """
    Storage backend: local (default), s3, gcs, valkey, or tiered (valkey + s3 fallback)
    """
    gcs_bucket: str | None = None
    """
    GCS bucket for state persistence
    """
    gcs_prefix: str | None = None
    """
    GCS key prefix (default: "rocky/state/")
    """
    s3_bucket: str | None = None
    """
    S3 bucket for state persistence
    """
    s3_prefix: str | None = None
    """
    S3 key prefix (default: "rocky/state/")
    """
    transfer_timeout_seconds: conint(ge=0) | None = 300
    """
    Wall-clock budget (seconds) for each state transfer operation (download or upload). Catches stuck SDK retry loops, DNS, TLS, and hung endpoints that the per-request HTTP timeout does not see. Defaults to 300s; raise for large state or slow networks.
    """
    valkey_prefix: str | None = None
    """
    Valkey key prefix (default: "rocky:state:")
    """
    valkey_url: str | None = None
    """
    Valkey/Redis URL for state persistence
    """


class TableRef(BaseModel):
    """
    A reference to a specific catalog/schema/table for quality checks and snapshot pipelines.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    catalog: str
    schema_: str = Field(..., alias="schema")
    table: str | None = None
    """
    Specific table name. When `None`, all tables in the schema are checked.
    """


class TestSeverity1(StrEnum):
    """
    Test failure is a hard error — pipeline fails.
    """

    error = "error"


class TestSeverity2(StrEnum):
    """
    Test failure is a warning — pipeline continues.
    """

    warning = "warning"


class WebhookConfig(BaseModel):
    """
    Configuration for a single webhook endpoint.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    async_: bool | None = Field(False, alias="async")
    """
    If true, fire-and-forget (spawn task, don't await). Default: false.
    """
    body_template: str | None = None
    """
    Mustache-style body template. If None, the full HookContext is serialized as JSON.
    """
    headers: dict[str, str] | None = {}
    """
    Additional HTTP headers.
    """
    method: str | None = "POST"
    """
    HTTP method (default: POST).
    """
    on_failure: FailureAction1 | FailureAction2 | FailureAction3 | None = "warn"
    """
    What to do when the webhook fails.
    """
    preset: str | None = None
    """
    Optional preset name (e.g., "slack", "pagerduty"). When set, preset defaults are merged before execution.
    """
    retry_count: conint(ge=0) | None = 0
    """
    Number of retry attempts on failure (default: 0).
    """
    retry_delay_ms: conint(ge=0) | None = 1000
    """
    Delay between retries in milliseconds (default: 1000).
    """
    secret: str | None = None
    """
    HMAC-SHA256 signing secret. When set, adds `X-Rocky-Signature: sha256=<hex>` header.
    """
    timeout_ms: conint(ge=0) | None = 10000
    """
    Request timeout in milliseconds (default: 10000).
    """
    url: str
    """
    Target URL for the webhook request.
    """


class WorkspaceBindingConfig(BaseModel):
    """
    A workspace binding with ID and access level.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    binding_type: BindingType | None = "READ_WRITE"
    id: conint(ge=0)


class AdapterConfig(BaseModel):
    """
    Configuration for a named adapter instance.

    The `type` field determines which adapter crate handles this config. Adapter-specific fields are captured via `serde(flatten)`.

    Credential fields (`token`, `client_secret`, `api_key`, `api_secret`, `password`, `oauth_token`) are wrapped in [`RedactedString`] so that `Debug` output never leaks secrets.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    account: str | None = None
    """
    Snowflake account identifier (e.g., "xy12345.us-east-1").
    """
    api_key: str | None = None
    api_secret: str | None = None
    client_id: str | None = None
    client_secret: str | None = None
    database: str | None = None
    """
    Default database for the session.
    """
    destination_id: str | None = None
    host: str | None = None
    http_path: str | None = None
    kind: AdapterKind3 | AdapterKind4 | None = None
    """
    Role this adapter block plays. See [`AdapterKind`] for the required-vs-optional rules per adapter type.
    """
    location: str | None = None
    """
    BigQuery processing location (e.g., "US", "EU", "us-central1").
    """
    oauth_token: str | None = None
    """
    OAuth access token (pre-obtained from an IdP).
    """
    password: str | None = None
    """
    Snowflake password (for password auth).
    """
    path: str | None = None
    """
    Optional file path for a persistent DuckDB database. When unset, the adapter uses an in-memory database. A persistent path is required when the same DuckDB adapter is also used as a discovery source — discovery and warehouse share the same database.
    """
    private_key_path: str | None = None
    """
    Path to RSA private key file (PEM) for key-pair auth.
    """
    project_id: str | None = None
    """
    Google Cloud project ID.
    """
    retry: RetryConfig | None = Field(
        {
            "backoff_multiplier": 2.0,
            "circuit_breaker_recovery_timeout_secs": None,
            "circuit_breaker_threshold": 5,
            "initial_backoff_ms": 1000,
            "jitter": True,
            "max_backoff_ms": 30000,
            "max_retries": 3,
            "max_retries_per_run": None,
        },
        validate_default=True,
    )
    """
    Retry policy for this adapter.
    """
    role: str | None = None
    """
    Snowflake role to use for the session.
    """
    timeout_secs: conint(ge=0) | None = None
    token: str | None = None
    type: str
    """
    Adapter type: "databricks", "fivetran", "duckdb", etc.
    """
    username: str | None = None
    """
    Snowflake username (for password or key-pair auth).
    """
    warehouse: str | None = None
    """
    Snowflake warehouse to use for query execution.
    """


class AggregateCheckToggle1(BaseModel):
    """
    Explicit struct form with per-check severity.
    """

    enabled: bool | None = False
    severity: TestSeverity1 | TestSeverity2 | None = "error"
    """
    Severity of a test failure.
    """


class CustomCheckConfig(BaseModel):
    """
    A user-defined SQL check with a name, query template, and pass/fail threshold.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    severity: TestSeverity1 | TestSeverity2 | None = "error"
    """
    Severity reported when this check fails.
    """
    sql: str
    threshold: conint(ge=0) | None = 0


class FreshnessConfig(BaseModel):
    """
    Freshness check configuration with optional per-schema overrides.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    overrides: dict[str, conint(ge=0)] | None = {}
    """
    Per-schema freshness overrides. Key is a schema pattern (e.g., "raw__us_west__shopify"), value overrides threshold_seconds for matching schemas.
    """
    severity: TestSeverity1 | TestSeverity2 | None = "error"
    """
    Severity reported when freshness lag exceeds the threshold.
    """
    threshold_seconds: conint(ge=0)


class HooksConfig(BaseModel):
    """
    The `[hook]` section from rocky.toml.

    Each key is an event name like `on_pipeline_start`. The value can be either a single hook config (TOML table) or an array of hook configs (TOML array of tables).

    Webhook entries live under `[hook.webhooks.on_<event>]` or `[[hook.webhooks.on_<event>]]`.
    """

    webhooks: dict[str, WebhookConfig | list[WebhookConfig]] | None = Field(
        {}, validate_default=True
    )
    """
    Webhook configurations keyed by event name.
    """


class IsolationConfig(BaseModel):
    """
    Workspace isolation configuration (Databricks-specific).

    ```toml [governance.isolation] enabled = true

    [[governance.isolation.workspace_ids]] id = 7474656540609532 binding_type = "READ_WRITE"

    [[governance.isolation.workspace_ids]] id = 7474647537929812 binding_type = "READ_ONLY" ```
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    enabled: bool | None = False
    workspace_ids: list[WorkspaceBindingConfig] | None = Field(
        [], validate_default=True
    )


class NullRateConfig(BaseModel):
    """
    Null rate check configuration: columns to check, threshold, and sample size.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    columns: list[str]
    sample_percent: conint(ge=0) | None = 10
    severity: TestSeverity1 | TestSeverity2 | None = "error"
    """
    Severity reported when a column's null rate exceeds the threshold.
    """
    threshold: float


class PipelineSourceConfig(BaseModel):
    """
    Pipeline source configuration.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    adapter: str | None = "default"
    """
    Name of the adapter to use (references a key in `[adapter.*]`). Defaults to `"default"` — resolved against the adapter map in [`normalize_rocky_config`].
    """
    catalog: str | None = None
    """
    Source catalog name.
    """
    discovery: DiscoveryConfig | None = None
    """
    Optional discovery configuration.
    """
    schema_pattern: SchemaPatternConfig
    """
    Schema pattern for parsing source schema names.
    """


class QualityAssertion1(BaseModel):
    """
    Assert that a column contains no NULL values.
    """

    column: str | None = None
    """
    Column under test. Required for `not_null`, `unique`, `accepted_values`, `relationships`, `in_range`, `regex_match`. Ignored for `expression` and `row_count_range`.
    """
    filter: str | None = None
    """
    Optional SQL boolean predicate that scopes the assertion to a subset of rows. When set, only rows where `(filter)` evaluates to `TRUE` are subject to the assertion — rows where the filter is `FALSE` or `NULL` pass unconditionally.

    Filter is user-supplied SQL; the caller is responsible for sandboxing execution (same contract as `expression`).

    Example: `filter = "created_at > current_date - interval 30 day"` restricts a `not_null` check to rows created in the last 30 days.
    """
    name: str | None = None
    """
    Optional identifier used as the `CheckResult.name` in the JSON output. When unset, a synthesized `"{kind}:{column}"` name is used — which can collide if multiple assertions share the same table, kind, and column. Set `name` explicitly to disambiguate.
    """
    severity: TestSeverity1 | TestSeverity2 | None = "error"
    """
    Severity of failure. Defaults to `error`.
    """
    table: str
    """
    Table name this assertion applies to. Must match a table discovered from one of the pipeline's `[[tables]]` entries (by unqualified table name).
    """
    type: Type19


class QualityAssertion2(BaseModel):
    """
    Assert that a column contains only unique values.
    """

    column: str | None = None
    """
    Column under test. Required for `not_null`, `unique`, `accepted_values`, `relationships`, `in_range`, `regex_match`. Ignored for `expression` and `row_count_range`.
    """
    filter: str | None = None
    """
    Optional SQL boolean predicate that scopes the assertion to a subset of rows. When set, only rows where `(filter)` evaluates to `TRUE` are subject to the assertion — rows where the filter is `FALSE` or `NULL` pass unconditionally.

    Filter is user-supplied SQL; the caller is responsible for sandboxing execution (same contract as `expression`).

    Example: `filter = "created_at > current_date - interval 30 day"` restricts a `not_null` check to rows created in the last 30 days.
    """
    name: str | None = None
    """
    Optional identifier used as the `CheckResult.name` in the JSON output. When unset, a synthesized `"{kind}:{column}"` name is used — which can collide if multiple assertions share the same table, kind, and column. Set `name` explicitly to disambiguate.
    """
    severity: TestSeverity1 | TestSeverity2 | None = "error"
    """
    Severity of failure. Defaults to `error`.
    """
    table: str
    """
    Table name this assertion applies to. Must match a table discovered from one of the pipeline's `[[tables]]` entries (by unqualified table name).
    """
    type: Type20


class QualityAssertion3(BaseModel):
    """
    Assert that a column contains only values from a fixed set.
    """

    column: str | None = None
    """
    Column under test. Required for `not_null`, `unique`, `accepted_values`, `relationships`, `in_range`, `regex_match`. Ignored for `expression` and `row_count_range`.
    """
    filter: str | None = None
    """
    Optional SQL boolean predicate that scopes the assertion to a subset of rows. When set, only rows where `(filter)` evaluates to `TRUE` are subject to the assertion — rows where the filter is `FALSE` or `NULL` pass unconditionally.

    Filter is user-supplied SQL; the caller is responsible for sandboxing execution (same contract as `expression`).

    Example: `filter = "created_at > current_date - interval 30 day"` restricts a `not_null` check to rows created in the last 30 days.
    """
    name: str | None = None
    """
    Optional identifier used as the `CheckResult.name` in the JSON output. When unset, a synthesized `"{kind}:{column}"` name is used — which can collide if multiple assertions share the same table, kind, and column. Set `name` explicitly to disambiguate.
    """
    severity: TestSeverity1 | TestSeverity2 | None = "error"
    """
    Severity of failure. Defaults to `error`.
    """
    table: str
    """
    Table name this assertion applies to. Must match a table discovered from one of the pipeline's `[[tables]]` entries (by unqualified table name).
    """
    type: Type21
    values: list[str]
    """
    The allowed values. Compared as string literals.
    """


class QualityAssertion4(BaseModel):
    """
    Assert that every non-NULL value in a column exists in a referenced table's column (referential integrity).
    """

    column: str | None = None
    """
    Column under test. Required for `not_null`, `unique`, `accepted_values`, `relationships`, `in_range`, `regex_match`. Ignored for `expression` and `row_count_range`.
    """
    filter: str | None = None
    """
    Optional SQL boolean predicate that scopes the assertion to a subset of rows. When set, only rows where `(filter)` evaluates to `TRUE` are subject to the assertion — rows where the filter is `FALSE` or `NULL` pass unconditionally.

    Filter is user-supplied SQL; the caller is responsible for sandboxing execution (same contract as `expression`).

    Example: `filter = "created_at > current_date - interval 30 day"` restricts a `not_null` check to rows created in the last 30 days.
    """
    name: str | None = None
    """
    Optional identifier used as the `CheckResult.name` in the JSON output. When unset, a synthesized `"{kind}:{column}"` name is used — which can collide if multiple assertions share the same table, kind, and column. Set `name` explicitly to disambiguate.
    """
    severity: TestSeverity1 | TestSeverity2 | None = "error"
    """
    Severity of failure. Defaults to `error`.
    """
    table: str
    """
    Table name this assertion applies to. Must match a table discovered from one of the pipeline's `[[tables]]` entries (by unqualified table name).
    """
    to_column: str
    """
    Column in the target table to join against.
    """
    to_table: str
    """
    Fully-qualified target table (`catalog.schema.table`).
    """
    type: Type22


class QualityAssertion5(BaseModel):
    """
    Assert that a custom SQL expression holds for every row.
    """

    column: str | None = None
    """
    Column under test. Required for `not_null`, `unique`, `accepted_values`, `relationships`, `in_range`, `regex_match`. Ignored for `expression` and `row_count_range`.
    """
    filter: str | None = None
    """
    Optional SQL boolean predicate that scopes the assertion to a subset of rows. When set, only rows where `(filter)` evaluates to `TRUE` are subject to the assertion — rows where the filter is `FALSE` or `NULL` pass unconditionally.

    Filter is user-supplied SQL; the caller is responsible for sandboxing execution (same contract as `expression`).

    Example: `filter = "created_at > current_date - interval 30 day"` restricts a `not_null` check to rows created in the last 30 days.
    """
    name: str | None = None
    """
    Optional identifier used as the `CheckResult.name` in the JSON output. When unset, a synthesized `"{kind}:{column}"` name is used — which can collide if multiple assertions share the same table, kind, and column. Set `name` explicitly to disambiguate.
    """
    severity: TestSeverity1 | TestSeverity2 | None = "error"
    """
    Severity of failure. Defaults to `error`.
    """
    table: str
    """
    Table name this assertion applies to. Must match a table discovered from one of the pipeline's `[[tables]]` entries (by unqualified table name).
    """
    expression: str
    """
    A SQL boolean expression. Rows where `NOT (expression)` are failures.
    """
    type: Type23


class QualityAssertion6(BaseModel):
    """
    Assert that the table's row count falls within an inclusive range.
    """

    column: str | None = None
    """
    Column under test. Required for `not_null`, `unique`, `accepted_values`, `relationships`, `in_range`, `regex_match`. Ignored for `expression` and `row_count_range`.
    """
    filter: str | None = None
    """
    Optional SQL boolean predicate that scopes the assertion to a subset of rows. When set, only rows where `(filter)` evaluates to `TRUE` are subject to the assertion — rows where the filter is `FALSE` or `NULL` pass unconditionally.

    Filter is user-supplied SQL; the caller is responsible for sandboxing execution (same contract as `expression`).

    Example: `filter = "created_at > current_date - interval 30 day"` restricts a `not_null` check to rows created in the last 30 days.
    """
    name: str | None = None
    """
    Optional identifier used as the `CheckResult.name` in the JSON output. When unset, a synthesized `"{kind}:{column}"` name is used — which can collide if multiple assertions share the same table, kind, and column. Set `name` explicitly to disambiguate.
    """
    severity: TestSeverity1 | TestSeverity2 | None = "error"
    """
    Severity of failure. Defaults to `error`.
    """
    table: str
    """
    Table name this assertion applies to. Must match a table discovered from one of the pipeline's `[[tables]]` entries (by unqualified table name).
    """
    max: conint(ge=0) | None = None
    """
    Maximum row count (inclusive). `None` means no upper bound.
    """
    min: conint(ge=0) | None = None
    """
    Minimum row count (inclusive). `None` means no lower bound.
    """
    type: Type24


class QualityAssertion7(BaseModel):
    """
    Assert that a column's values fall within a numeric range (inclusive, half-open either side). Phase 4a supports numeric bounds only — use `time_window` (Phase 4b) or `expression` for temporal comparisons.

    NULL column values pass (consistent with existing `NOT IN` / `NOT (expr)` semantics).
    """

    column: str | None = None
    """
    Column under test. Required for `not_null`, `unique`, `accepted_values`, `relationships`, `in_range`, `regex_match`. Ignored for `expression` and `row_count_range`.
    """
    filter: str | None = None
    """
    Optional SQL boolean predicate that scopes the assertion to a subset of rows. When set, only rows where `(filter)` evaluates to `TRUE` are subject to the assertion — rows where the filter is `FALSE` or `NULL` pass unconditionally.

    Filter is user-supplied SQL; the caller is responsible for sandboxing execution (same contract as `expression`).

    Example: `filter = "created_at > current_date - interval 30 day"` restricts a `not_null` check to rows created in the last 30 days.
    """
    name: str | None = None
    """
    Optional identifier used as the `CheckResult.name` in the JSON output. When unset, a synthesized `"{kind}:{column}"` name is used — which can collide if multiple assertions share the same table, kind, and column. Set `name` explicitly to disambiguate.
    """
    severity: TestSeverity1 | TestSeverity2 | None = "error"
    """
    Severity of failure. Defaults to `error`.
    """
    table: str
    """
    Table name this assertion applies to. Must match a table discovered from one of the pipeline's `[[tables]]` entries (by unqualified table name).
    """
    max: str | None = None
    """
    Maximum value (inclusive). `None` means no upper bound.
    """
    min: str | None = None
    """
    Minimum value (inclusive). `None` means no lower bound.
    """
    type: Type25


class QualityAssertion8(BaseModel):
    """
    Assert that a column's values match a regular expression.

    Dialect-specific operator (`REGEXP` / `RLIKE` / `REGEXP_LIKE` / `REGEXP_CONTAINS`) is produced by [`SqlDialect::regex_match_predicate`]. Patterns are validated against a strict allowlist that rejects single quotes, backticks, and semicolons.

    NULL column values pass.
    """

    column: str | None = None
    """
    Column under test. Required for `not_null`, `unique`, `accepted_values`, `relationships`, `in_range`, `regex_match`. Ignored for `expression` and `row_count_range`.
    """
    filter: str | None = None
    """
    Optional SQL boolean predicate that scopes the assertion to a subset of rows. When set, only rows where `(filter)` evaluates to `TRUE` are subject to the assertion — rows where the filter is `FALSE` or `NULL` pass unconditionally.

    Filter is user-supplied SQL; the caller is responsible for sandboxing execution (same contract as `expression`).

    Example: `filter = "created_at > current_date - interval 30 day"` restricts a `not_null` check to rows created in the last 30 days.
    """
    name: str | None = None
    """
    Optional identifier used as the `CheckResult.name` in the JSON output. When unset, a synthesized `"{kind}:{column}"` name is used — which can collide if multiple assertions share the same table, kind, and column. Set `name` explicitly to disambiguate.
    """
    severity: TestSeverity1 | TestSeverity2 | None = "error"
    """
    Severity of failure. Defaults to `error`.
    """
    table: str
    """
    Table name this assertion applies to. Must match a table discovered from one of the pipeline's `[[tables]]` entries (by unqualified table name).
    """
    pattern: str
    """
    The regex pattern. Dialect-specific syntax — stick to the portable subset (character classes, anchors, quantifiers).
    """
    type: Type26


class QualityAssertion9(BaseModel):
    """
    Assert that an aggregate (`sum`, `count`, `avg`, `min`, `max`) of a column satisfies a comparison against a numeric threshold. The comparison is what **passes** — e.g. `op = "sum", cmp = "gt", value = "0"` means "sum(col) > 0 passes; otherwise fails".

    Table-level; not quarantinable. Use `count` (no column) for the row-count-based variants that `row_count_range` can't express (equality, strict inequalities).
    """

    column: str | None = None
    """
    Column under test. Required for `not_null`, `unique`, `accepted_values`, `relationships`, `in_range`, `regex_match`. Ignored for `expression` and `row_count_range`.
    """
    filter: str | None = None
    """
    Optional SQL boolean predicate that scopes the assertion to a subset of rows. When set, only rows where `(filter)` evaluates to `TRUE` are subject to the assertion — rows where the filter is `FALSE` or `NULL` pass unconditionally.

    Filter is user-supplied SQL; the caller is responsible for sandboxing execution (same contract as `expression`).

    Example: `filter = "created_at > current_date - interval 30 day"` restricts a `not_null` check to rows created in the last 30 days.
    """
    name: str | None = None
    """
    Optional identifier used as the `CheckResult.name` in the JSON output. When unset, a synthesized `"{kind}:{column}"` name is used — which can collide if multiple assertions share the same table, kind, and column. Set `name` explicitly to disambiguate.
    """
    severity: TestSeverity1 | TestSeverity2 | None = "error"
    """
    Severity of failure. Defaults to `error`.
    """
    table: str
    """
    Table name this assertion applies to. Must match a table discovered from one of the pipeline's `[[tables]]` entries (by unqualified table name).
    """
    cmp: AggregateCmp
    """
    Comparison between `op(column)` and `value`. The check passes when the comparison is true.
    """
    op: AggregateOp1 | AggregateOp2 | AggregateOp3 | AggregateOp4 | AggregateOp5
    """
    Aggregate operator.
    """
    type: Type27
    value: str
    """
    Threshold to compare against. Parsed as `f64`.
    """


class QualityAssertion10(BaseModel):
    """
    Assert that a combination of columns is unique across all rows. Extends [`TestType::Unique`] to composite keys.

    Set-based; not quarantinable.
    """

    column: str | None = None
    """
    Column under test. Required for `not_null`, `unique`, `accepted_values`, `relationships`, `in_range`, `regex_match`. Ignored for `expression` and `row_count_range`.
    """
    filter: str | None = None
    """
    Optional SQL boolean predicate that scopes the assertion to a subset of rows. When set, only rows where `(filter)` evaluates to `TRUE` are subject to the assertion — rows where the filter is `FALSE` or `NULL` pass unconditionally.

    Filter is user-supplied SQL; the caller is responsible for sandboxing execution (same contract as `expression`).

    Example: `filter = "created_at > current_date - interval 30 day"` restricts a `not_null` check to rows created in the last 30 days.
    """
    name: str | None = None
    """
    Optional identifier used as the `CheckResult.name` in the JSON output. When unset, a synthesized `"{kind}:{column}"` name is used — which can collide if multiple assertions share the same table, kind, and column. Set `name` explicitly to disambiguate.
    """
    severity: TestSeverity1 | TestSeverity2 | None = "error"
    """
    Severity of failure. Defaults to `error`.
    """
    table: str
    """
    Table name this assertion applies to. Must match a table discovered from one of the pipeline's `[[tables]]` entries (by unqualified table name).
    """
    columns: list[str]
    """
    Columns that together form the key. Must have at least two entries (single-column uniqueness is covered by `Unique`).
    """
    kind: CompositeKind
    """
    The kind of composite assertion. Currently `unique` only — kept as an enum to leave room for `not_null_any` / `not_null_all` in a later phase without another TestType.
    """
    type: Type28


class QualityAssertion11(BaseModel):
    """
    First-class sugar for `col <= CURRENT_TIMESTAMP()` — no timestamp in the future. Row-level; quarantinable (NULL column values pass).
    """

    column: str | None = None
    """
    Column under test. Required for `not_null`, `unique`, `accepted_values`, `relationships`, `in_range`, `regex_match`. Ignored for `expression` and `row_count_range`.
    """
    filter: str | None = None
    """
    Optional SQL boolean predicate that scopes the assertion to a subset of rows. When set, only rows where `(filter)` evaluates to `TRUE` are subject to the assertion — rows where the filter is `FALSE` or `NULL` pass unconditionally.

    Filter is user-supplied SQL; the caller is responsible for sandboxing execution (same contract as `expression`).

    Example: `filter = "created_at > current_date - interval 30 day"` restricts a `not_null` check to rows created in the last 30 days.
    """
    name: str | None = None
    """
    Optional identifier used as the `CheckResult.name` in the JSON output. When unset, a synthesized `"{kind}:{column}"` name is used — which can collide if multiple assertions share the same table, kind, and column. Set `name` explicitly to disambiguate.
    """
    severity: TestSeverity1 | TestSeverity2 | None = "error"
    """
    Severity of failure. Defaults to `error`.
    """
    table: str
    """
    Table name this assertion applies to. Must match a table discovered from one of the pipeline's `[[tables]]` entries (by unqualified table name).
    """
    type: Type29


class QualityAssertion12(BaseModel):
    """
    First-class sugar for `col <= CURRENT_DATE - N days` — every row's timestamp must be at least `days` days old. Row-level; quarantinable (NULL column values pass). Dialect-specific: uses [`SqlDialect::date_minus_days_expr`].
    """

    column: str | None = None
    """
    Column under test. Required for `not_null`, `unique`, `accepted_values`, `relationships`, `in_range`, `regex_match`. Ignored for `expression` and `row_count_range`.
    """
    filter: str | None = None
    """
    Optional SQL boolean predicate that scopes the assertion to a subset of rows. When set, only rows where `(filter)` evaluates to `TRUE` are subject to the assertion — rows where the filter is `FALSE` or `NULL` pass unconditionally.

    Filter is user-supplied SQL; the caller is responsible for sandboxing execution (same contract as `expression`).

    Example: `filter = "created_at > current_date - interval 30 day"` restricts a `not_null` check to rows created in the last 30 days.
    """
    name: str | None = None
    """
    Optional identifier used as the `CheckResult.name` in the JSON output. When unset, a synthesized `"{kind}:{column}"` name is used — which can collide if multiple assertions share the same table, kind, and column. Set `name` explicitly to disambiguate.
    """
    severity: TestSeverity1 | TestSeverity2 | None = "error"
    """
    Severity of failure. Defaults to `error`.
    """
    table: str
    """
    Table name this assertion applies to. Must match a table discovered from one of the pipeline's `[[tables]]` entries (by unqualified table name).
    """
    days: conint(ge=0)
    """
    N — days in the past. Must be > 0.
    """
    type: Type30


class QuarantineConfig(BaseModel):
    """
    Row quarantine configuration. When enabled, error-severity row-level assertions (`not_null`, `accepted_values`, `expression`) on a given table are compiled into a single boolean row predicate. Rows matching the predicate go to the `__valid` table; rows that don't go to the `__quarantine` table (or are dropped / tagged, per `mode`).

    Aggregate / set-based assertions (`unique`, `relationships`, `row_count_range`) are **not** lowered — they stay observational and produce `CheckResult` entries as before.

    ```toml [pipeline.nightly_dq.checks.quarantine] enabled = true mode    = "split"          # "split" (default) | "tag" | "drop" # suffix_valid       = "__valid" # suffix_quarantine  = "__quarantine" ```
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    enabled: bool | None = False
    """
    Enable quarantine. Default: `false`.
    """
    mode: QuarantineMode1 | QuarantineMode2 | QuarantineMode3 | None = "split"
    """
    How to split rows — see [`QuarantineMode`].
    """
    suffix_quarantine: str | None = "__quarantine"
    """
    Table-name suffix for the failing-rows table. Default `"__quarantine"`.
    """
    suffix_valid: str | None = "__valid"
    """
    Table-name suffix for the passing-rows table. Default `"__valid"`.
    """


class ChecksConfig(BaseModel):
    """
    Data quality checks configuration (row count, column match, freshness, null rate, custom).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    anomaly_threshold_pct: float | None = 50.0
    """
    Row count anomaly detection threshold (percentage deviation from baseline). Default: 50.0 (50% deviation triggers anomaly). Set to 0 to disable.
    """
    assertions: (
        list[
            QualityAssertion1
            | QualityAssertion2
            | QualityAssertion3
            | QualityAssertion4
            | QualityAssertion5
            | QualityAssertion6
            | QualityAssertion7
            | QualityAssertion8
            | QualityAssertion9
            | QualityAssertion10
            | QualityAssertion11
            | QualityAssertion12
        ]
        | None
    ) = Field([], validate_default=True)
    """
    Row-level assertions (`not_null`, `unique`, `accepted_values`, `relationships`, `expression`, `row_count_range`) executed against specific tables in the quality pipeline. Each entry targets a single table by name and reuses the `TestDecl` surface from declarative model tests.
    """
    column_match: bool | AggregateCheckToggle1 | None = Field(
        False, validate_default=True
    )
    """
    Per-check-kind toggle that accepts either a plain boolean (legacy form) or a struct with `enabled` + `severity`.

    ```toml # Legacy — still supported row_count = true

    # New — per-check severity [pipeline.x.checks.row_count] enabled  = true severity = "warning" ```
    """
    custom: list[CustomCheckConfig] | None = Field([], validate_default=True)
    enabled: bool | None = False
    fail_on_error: bool | None = True
    """
    When `true` (default), the quality run exits non-zero if any error-severity check fails. Set `false` to force the pipeline to always succeed and leave failure handling to downstream consumers of the JSON output.
    """
    freshness: FreshnessConfig | None = None
    null_rate: NullRateConfig | None = None
    quarantine: QuarantineConfig | None = None
    """
    Row quarantine — split/tag/drop rows that violate error-severity row-level assertions. Disabled when unset. See [`QuarantineConfig`].
    """
    row_count: bool | AggregateCheckToggle1 | None = Field(False, validate_default=True)
    """
    Per-check-kind toggle that accepts either a plain boolean (legacy form) or a struct with `enabled` + `severity`.

    ```toml # Legacy — still supported row_count = true

    # New — per-check severity [pipeline.x.checks.row_count] enabled  = true severity = "warning" ```
    """


class GovernanceConfig(BaseModel):
    """
    Governance settings: auto-creation of catalogs/schemas, tags, isolation, and grants.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    auto_create_catalogs: bool | None = False
    auto_create_schemas: bool | None = False
    grants: list[GrantConfig] | None = Field([], validate_default=True)
    """
    Permissions granted on every managed catalog.
    """
    isolation: IsolationConfig | None = None
    """
    Workspace isolation settings.
    """
    schema_grants: list[GrantConfig] | None = Field([], validate_default=True)
    """
    Permissions granted on every managed schema.
    """
    tag_prefix: str | None = None
    """
    Optional prefix prepended to auto-generated component tag keys (e.g., `"ge_"` turns `client` → `ge_client`). Does not affect keys in `[governance.tags]` — those are used verbatim.
    """
    tags: dict[str, str] | None = {}
    """
    Tags applied to every managed catalog and schema.
    """


class LoadTargetConfig(BaseModel):
    """
    Target configuration for load pipelines.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    adapter: str | None = "default"
    """
    Name of the adapter to use (references a key in `[adapter.*]`).
    """
    catalog: str
    """
    Target catalog name.
    """
    governance: GovernanceConfig | None = Field(
        {
            "auto_create_catalogs": False,
            "auto_create_schemas": False,
            "grants": [],
            "isolation": None,
            "schema_grants": [],
            "tag_prefix": None,
            "tags": {},
        },
        validate_default=True,
    )
    """
    Governance settings for the target.
    """
    schema_: str = Field(..., alias="schema")
    """
    Target schema name.
    """
    table: str | None = None
    """
    Optional explicit table name. When omitted, derives from the file name (e.g., `orders.csv` -> table `orders`).
    """


class PipelineTargetConfig(BaseModel):
    """
    Pipeline target configuration.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    adapter: str | None = "default"
    """
    Name of the adapter to use (references a key in `[adapter.*]`). Defaults to `"default"`.
    """
    catalog_template: str
    """
    Template for the target catalog name.
    """
    governance: GovernanceConfig | None = Field(
        {
            "auto_create_catalogs": False,
            "auto_create_schemas": False,
            "grants": [],
            "isolation": None,
            "schema_grants": [],
            "tag_prefix": None,
            "tags": {},
        },
        validate_default=True,
    )
    """
    Governance settings for the target.
    """
    schema_template: str
    """
    Template for the target schema name.
    """
    separator: str | None = None
    """
    Separator for joining variadic components in target templates.

    When a source pattern uses `"__"` as its separator but the target templates use `"_"` between placeholders, set this to `"_"` so that multi-valued components (e.g., `{hierarchies}`) are joined correctly.

    Defaults to the source pattern separator when not set.
    """


class QualityPipelineConfig(BaseModel):
    """
    Quality pipeline configuration — standalone data quality checks.

    Runs checks against existing tables without any data movement.

    ```toml [pipeline.nightly_dq] type = "quality"

    [pipeline.nightly_dq.target] adapter = "databricks_prod"

    [[pipeline.nightly_dq.tables]] catalog = "acme_warehouse" schema = "raw__us_west__shopify"

    [pipeline.nightly_dq.checks] enabled = true freshness = { threshold_seconds = 86400 } ```
    """

    checks: ChecksConfig
    """
    Data quality checks to run.
    """
    depends_on: list[str] | None = []
    """
    Pipeline dependencies for chaining.
    """
    execution: ExecutionConfig | None = Field(
        {
            "concurrency": "adaptive",
            "error_rate_abort_pct": 50,
            "fail_fast": False,
            "table_retries": 1,
        },
        validate_default=True,
    )
    """
    Execution settings (concurrency, retries, etc.).
    """
    tables: list[TableRef] | None = Field([], validate_default=True)
    """
    Tables to check. Each entry specifies catalog + schema, and optionally a specific table (omit for all tables in the schema).
    """
    target: QualityTargetConfig
    """
    Target adapter for running check queries.
    """


class ReplicationPipelineConfig(BaseModel):
    """
    Replication pipeline configuration.

    Copies tables from a source to a target using schema pattern discovery, with optional incremental strategy, metadata columns, governance, and data quality checks.
    """

    checks: ChecksConfig | None = Field(
        {
            "anomaly_threshold_pct": 0.0,
            "assertions": [],
            "column_match": False,
            "custom": [],
            "enabled": False,
            "fail_on_error": False,
            "freshness": None,
            "null_rate": None,
            "quarantine": None,
            "row_count": False,
        },
        validate_default=True,
    )
    """
    Data quality checks.
    """
    depends_on: list[str] | None = []
    """
    Pipeline dependencies for chaining (Phase 4).
    """
    execution: ExecutionConfig | None = Field(
        {
            "concurrency": "adaptive",
            "error_rate_abort_pct": 50,
            "fail_fast": False,
            "table_retries": 1,
        },
        validate_default=True,
    )
    """
    Execution settings (concurrency, retries, etc.).
    """
    metadata_columns: list[MetadataColumnConfig] | None = Field(
        [], validate_default=True
    )
    """
    Metadata columns added during replication.
    """
    source: PipelineSourceConfig
    """
    Source configuration.
    """
    strategy: str | None = "incremental"
    """
    Replication strategy: "incremental" or "full_refresh".
    """
    target: PipelineTargetConfig
    """
    Target configuration.
    """
    timestamp_column: str | None = "_fivetran_synced"
    """
    Timestamp column for incremental strategy.
    """


class SnapshotTargetConfig(BaseModel):
    """
    Target table for a snapshot pipeline (explicit single-table reference + governance).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    adapter: str | None = "default"
    """
    Name of the adapter to use (references a key in `[adapter.*]`).
    """
    catalog: str
    governance: GovernanceConfig | None = Field(
        {
            "auto_create_catalogs": False,
            "auto_create_schemas": False,
            "grants": [],
            "isolation": None,
            "schema_grants": [],
            "tag_prefix": None,
            "tags": {},
        },
        validate_default=True,
    )
    schema_: str = Field(..., alias="schema")
    table: str


class TransformationTargetConfig(BaseModel):
    """
    Target configuration for transformation pipelines.

    Unlike replication targets (which use `catalog_template` / `schema_template` for dynamic routing), transformation targets only need an adapter reference and optional governance — the actual catalog/schema/table is defined per-model in sidecar TOML files.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    adapter: str | None = "default"
    """
    Name of the adapter to use (references a key in `[adapter.*]`). Defaults to `"default"`.
    """
    governance: GovernanceConfig | None = Field(
        {
            "auto_create_catalogs": False,
            "auto_create_schemas": False,
            "grants": [],
            "isolation": None,
            "schema_grants": [],
            "tag_prefix": None,
            "tags": {},
        },
        validate_default=True,
    )
    """
    Governance settings for the target.
    """


class LoadPipelineConfig(BaseModel):
    """
    Load pipeline configuration -- ingest files (CSV, Parquet, JSONL) into a warehouse.

    Loads data from a local directory into a target catalog/schema. The format can be auto-detected from file extensions or set explicitly.

    ```toml [pipeline.load_data] type = "load" source_dir = "data/" format = "csv"

    [pipeline.load_data.target] adapter = "prod" catalog = "warehouse" schema = "raw"

    [pipeline.load_data.options] batch_size = 5000 create_table = true truncate_first = false csv_delimiter = "," csv_has_header = true ```
    """

    checks: ChecksConfig | None = Field(
        {
            "anomaly_threshold_pct": 0.0,
            "assertions": [],
            "column_match": False,
            "custom": [],
            "enabled": False,
            "fail_on_error": False,
            "freshness": None,
            "null_rate": None,
            "quarantine": None,
            "row_count": False,
        },
        validate_default=True,
    )
    """
    Data quality checks run after loading.
    """
    depends_on: list[str] | None = []
    """
    Pipeline dependencies for chaining.
    """
    execution: ExecutionConfig | None = Field(
        {
            "concurrency": "adaptive",
            "error_rate_abort_pct": 50,
            "fail_fast": False,
            "table_retries": 1,
        },
        validate_default=True,
    )
    """
    Execution settings (concurrency, retries, etc.).
    """
    format: LoadFileFormat | None = None
    """
    Explicit file format. When omitted, auto-detected from file extensions.
    """
    options: LoadOptionsConfig | None = Field(
        {
            "batch_size": 10000,
            "create_table": True,
            "csv_delimiter": ",",
            "csv_has_header": True,
            "truncate_first": False,
        },
        validate_default=True,
    )
    """
    Load options (batch size, create/truncate behavior, CSV settings).
    """
    source_dir: str
    """
    Directory or glob pattern for source files, relative to the config file.
    """
    target: LoadTargetConfig
    """
    Target table location.
    """


class PipelineConfig1(ReplicationPipelineConfig):
    """
    Pipeline configuration. The `type` field selects one of five variants — `replication` (default when omitted), `transformation`, `quality`, `snapshot`, or `load`. Each variant has its own field set; see the per-variant subschemas in `definitions`.
    """

    type: Type | None = None


class PipelineConfig3(QualityPipelineConfig):
    """
    Pipeline configuration. The `type` field selects one of five variants — `replication` (default when omitted), `transformation`, `quality`, `snapshot`, or `load`. Each variant has its own field set; see the per-variant subschemas in `definitions`.
    """

    type: Type16


class PipelineConfig5(LoadPipelineConfig):
    """
    Pipeline configuration. The `type` field selects one of five variants — `replication` (default when omitted), `transformation`, `quality`, `snapshot`, or `load`. Each variant has its own field set; see the per-variant subschemas in `definitions`.
    """

    type: Type18


class SnapshotPipelineConfig(BaseModel):
    """
    Snapshot pipeline configuration — SCD Type 2 slowly-changing dimension capture.

    Tracks historical changes to a source table by maintaining `valid_from` / `valid_to` columns in the target history table.

    ```toml [pipeline.customer_history] type = "snapshot" unique_key = ["customer_id"] updated_at = "updated_at"

    [pipeline.customer_history.source] adapter = "databricks_prod" catalog = "raw_catalog" schema = "raw__us_west__shopify" table = "customers"

    [pipeline.customer_history.target] adapter = "databricks_prod" catalog = "acme_warehouse" schema = "silver__scd" table = "customers_history" ```
    """

    checks: ChecksConfig | None = Field(
        {
            "anomaly_threshold_pct": 0.0,
            "assertions": [],
            "column_match": False,
            "custom": [],
            "enabled": False,
            "fail_on_error": False,
            "freshness": None,
            "null_rate": None,
            "quarantine": None,
            "row_count": False,
        },
        validate_default=True,
    )
    """
    Data quality checks run after snapshot.
    """
    depends_on: list[str] | None = []
    """
    Pipeline dependencies for chaining.
    """
    execution: ExecutionConfig | None = Field(
        {
            "concurrency": "adaptive",
            "error_rate_abort_pct": 50,
            "fail_fast": False,
            "table_retries": 1,
        },
        validate_default=True,
    )
    """
    Execution settings.
    """
    invalidate_hard_deletes: bool | None = False
    """
    When true, rows deleted from the source get their `valid_to` set to the current timestamp in the target. Default: false.
    """
    source: SnapshotSourceConfig
    """
    Source table reference (single table, not pattern-based discovery).
    """
    target: SnapshotTargetConfig
    """
    Target history table.
    """
    unique_key: list[str]
    """
    Column(s) that uniquely identify a row in the source table.
    """
    updated_at: str
    """
    Column used to detect changes (compared between runs).
    """


class TransformationPipelineConfig(BaseModel):
    """
    Transformation pipeline configuration.

    Orchestrates `.sql` / `.rocky` model compilation and execution as a first-class pipeline, with its own execution, checks, and governance settings. Model-level strategy (incremental, merge, time_interval, etc.) is defined in each model's sidecar TOML, not at the pipeline level.

    ```toml [pipeline.silver] type = "transformation" models = "models/**"

    [pipeline.silver.target] adapter = "databricks_prod" [pipeline.silver.target.governance] auto_create_schemas = true

    [pipeline.silver.execution] concurrency = 8 ```
    """

    checks: ChecksConfig | None = Field(
        {
            "anomaly_threshold_pct": 0.0,
            "assertions": [],
            "column_match": False,
            "custom": [],
            "enabled": False,
            "fail_on_error": False,
            "freshness": None,
            "null_rate": None,
            "quarantine": None,
            "row_count": False,
        },
        validate_default=True,
    )
    """
    Data quality checks run after model execution.
    """
    depends_on: list[str] | None = []
    """
    Pipeline dependencies for chaining.
    """
    execution: ExecutionConfig | None = Field(
        {
            "concurrency": "adaptive",
            "error_rate_abort_pct": 50,
            "fail_fast": False,
            "table_retries": 1,
        },
        validate_default=True,
    )
    """
    Execution settings (concurrency, retries, etc.).
    """
    models: str | None = "models/**"
    """
    Glob pattern for model files, relative to the config file directory. Default: `"models/**"`.
    """
    target: TransformationTargetConfig
    """
    Target configuration (adapter + governance).
    """


class PipelineConfig2(TransformationPipelineConfig):
    """
    Pipeline configuration. The `type` field selects one of five variants — `replication` (default when omitted), `transformation`, `quality`, `snapshot`, or `load`. Each variant has its own field set; see the per-variant subschemas in `definitions`.
    """

    type: Type15


class PipelineConfig4(SnapshotPipelineConfig):
    """
    Pipeline configuration. The `type` field selects one of five variants — `replication` (default when omitted), `transformation`, `quality`, `snapshot`, or `load`. Each variant has its own field set; see the per-variant subschemas in `definitions`.
    """

    type: Type17


class RockyConfig(BaseModel):
    """
    Top-level Rocky configuration (v2 format).

    Uses named adapters and named pipelines: ```toml [adapter.databricks_prod] type = "databricks" ...

    [pipeline.raw_replication] type = "replication" ... ```
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    adapter: AdapterConfig | dict[str, AdapterConfig] | None = Field(
        {}, validate_default=True
    )
    """
    Named adapter configurations (keyed by adapter name).
    """
    budget: BudgetConfig | None = Field(
        {"max_duration_ms": None, "max_usd": None, "on_breach": "warn"},
        validate_default=True,
    )
    """
    Declarative run-level budget. See [`BudgetConfig`] for the semantics of each limit and the breach action.
    """
    cost: CostSection | None = Field(
        {
            "compute_cost_per_dbu": 0.4,
            "min_history_runs": 5,
            "storage_cost_per_gb_month": 0.023,
            "warehouse_size": "Medium",
        },
        validate_default=True,
    )
    """
    Cost estimation configuration.
    """
    hook: HooksConfig | None = Field({"webhooks": {}}, validate_default=True)
    """
    Shell hooks configuration.
    """
    pipeline: (
        dict[
            str,
            PipelineConfig1
            | PipelineConfig2
            | PipelineConfig3
            | PipelineConfig4
            | PipelineConfig5,
        ]
        | PipelineConfig1
        | PipelineConfig2
        | PipelineConfig3
        | PipelineConfig4
        | PipelineConfig5
        | None
    ) = Field({}, validate_default=True)
    """
    Named pipeline configurations (keyed by pipeline name).
    """
    portability: PortabilityConfig | None = Field(
        {"allow": [], "target_dialect": None}, validate_default=True
    )
    """
    Dialect-portability lint configuration. Consumed by `rocky compile` to drive P001 (and, when wired, future) diagnostics. The CLI's `--target-dialect` flag, when set, takes precedence over [`PortabilityConfig::target_dialect`].
    """
    retry: RunRetryConfig | None = None
    """
    Run-level retry budget shared across every adapter for this run.

    When set, `rocky run` builds a single [`crate::retry_budget::RetryBudget`] from [`RunRetryConfig::max_retries_per_run`] and passes it to every connector via `with_retry_budget(...)`. One bad table that burns through retries on adapter A then has less budget available for adapter B's retries — the protection §P2.7 added within a single adapter now extends across the whole run.

    Unset (the default) preserves per-adapter semantics: each adapter still honours its own `retry.max_retries_per_run` independently. That's the backward-compatible path and stays the right choice when adapters have wildly different rate limits.
    """
    schema_evolution: SchemaEvolutionConfig | None = Field(
        {"grace_period_days": 7}, validate_default=True
    )
    """
    Schema evolution configuration (grace-period column drops).
    """
    state: StateConfig | None = Field(
        {
            "backend": "local",
            "gcs_bucket": None,
            "gcs_prefix": None,
            "s3_bucket": None,
            "s3_prefix": None,
            "transfer_timeout_seconds": 300,
            "valkey_prefix": None,
            "valkey_url": None,
        },
        validate_default=True,
    )
    """
    Global state persistence configuration.
    """
