# generated by datamodel-codegen:
#   filename:  run.schema.json
#   timestamp: 2026-04-15T23:28:11+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, conint


class AnomalyOutput(BaseModel):
    """
    Row count anomaly detected by historical baseline comparison.
    """

    baseline_avg: float
    current_count: conint(ge=0)
    deviation_pct: float
    reason: str
    table: str


class CheckResult1(BaseModel):
    """
    Row count comparison between source and target tables.
    """

    name: str
    passed: bool
    source_count: conint(ge=0)
    target_count: conint(ge=0)


class CheckResult2(BaseModel):
    """
    Column presence comparison between source and target schemas.
    """

    name: str
    passed: bool
    extra: list[str]
    missing: list[str]


class CheckResult3(BaseModel):
    """
    Data freshness measured as lag from the max timestamp to now.
    """

    name: str
    passed: bool
    lag_seconds: conint(ge=0)
    threshold_seconds: conint(ge=0)


class CheckResult4(BaseModel):
    """
    Null rate for a specific column, sampled via TABLESAMPLE.
    """

    name: str
    passed: bool
    column: str
    null_rate: float
    threshold: float


class CheckResult5(BaseModel):
    """
    User-defined SQL check evaluated against a threshold.
    """

    name: str
    passed: bool
    query: str
    result_value: conint(ge=0)
    threshold: conint(ge=0)


class DriftActionOutput(BaseModel):
    action: str
    reason: str
    table: str


class DriftSummary(BaseModel):
    actions_taken: list[DriftActionOutput]
    tables_checked: conint(ge=0)
    tables_drifted: conint(ge=0)


class ExcludedTableOutput(BaseModel):
    """
    A table that the discovery adapter reported but that is missing from the source warehouse, so the run skipped it. Tracked separately from `errors` because it is not a runtime failure — the row never made it past the pre-flight existence check.
    """

    asset_key: list[str]
    """
    Dagster-style asset key path (`[source_type, ...components, table]`).
    """
    reason: str
    """
    Why the table was excluded. Currently always `"missing_from_source"` but kept as a free-form field so future causes (disabled, sync_paused, ...) can be added without a schema break.
    """
    source_schema: str
    """
    Source schema the table was expected to live in.
    """
    table_name: str
    """
    Bare table name as reported by the discovery adapter.
    """


class ExecutionSummary(BaseModel):
    """
    Summary of execution parallelism and throughput.
    """

    adaptive_concurrency: bool
    """
    Whether adaptive concurrency (AIMD throttle) was enabled for this run.
    """
    concurrency: conint(ge=0)
    final_concurrency: conint(ge=0) | None = None
    """
    Final concurrency level at end of run (may differ from initial if adaptive concurrency adjusted it). Only present when adaptive concurrency is enabled.
    """
    rate_limits_detected: conint(ge=0) | None = None
    """
    Number of rate-limit signals (HTTP 429 / UC_REQUEST_LIMIT_EXCEEDED) that triggered concurrency reduction. Only present when adaptive concurrency is enabled.
    """
    tables_failed: conint(ge=0)
    tables_processed: conint(ge=0)


class MaterializationMetadata(BaseModel):
    column_count: conint(ge=0) | None = None
    """
    Number of columns in the materialized table's typed schema. Populated for derived models (where the compiler resolved a typed schema); `None` for source-replication tables that inherit their schema from upstream.
    """
    compile_time_ms: conint(ge=0) | None = None
    """
    Compile time in milliseconds for the model that produced this materialization. Populated only for derived models. Mirrors the relevant slice of `PhaseTimings.total_ms`.
    """
    sql_hash: str | None = None
    """
    Short hash (16 hex chars) of the generated SQL string. Lets orchestrators detect "what changed?" between runs without diffing full SQL bodies. Computed via `xxh3_64` of the canonical SQL the engine sent to the warehouse.
    """
    strategy: str
    target_table_full_name: str | None = None
    """
    Fully-qualified target table identifier in `catalog.schema.table` format. Useful for click-through links to the warehouse UI from the Dagster asset detail page. Always set when the materialization targets a known table.
    """
    watermark: AwareDatetime | None = None


class MetricsSnapshot(BaseModel):
    """
    Serializable metrics summary for JSON output.
    """

    anomalies_detected: conint(ge=0)
    error_rate_pct: float
    query_duration_max_ms: conint(ge=0)
    query_duration_p50_ms: conint(ge=0)
    query_duration_p95_ms: conint(ge=0)
    retries_attempted: conint(ge=0)
    retries_succeeded: conint(ge=0)
    statements_executed: conint(ge=0)
    table_duration_max_ms: conint(ge=0)
    table_duration_p50_ms: conint(ge=0)
    table_duration_p95_ms: conint(ge=0)
    tables_failed: conint(ge=0)
    tables_processed: conint(ge=0)


class PartitionInfo(BaseModel):
    """
    Partition window information for a single `time_interval` materialization.

    `key` is the canonical Rocky partition key (e.g. `"2026-04-07"` for daily; `"2026-04-07T13"` for hourly). `start` / `end` are the half-open `[start, end)` window the SQL substituted for `@start_date` / `@end_date`. `batched_with` lists any additional partition keys that were merged into this batch when `batch_size > 1` — empty for the default one-partition-per-statement case.
    """

    batched_with: list[str]
    end: AwareDatetime
    key: str
    start: AwareDatetime


class PartitionSummary(BaseModel):
    """
    Per-model summary of `time_interval` partition execution.

    One entry per partitioned model touched by the run. Lets dagster-rocky (and other orchestrators) display per-model partition stats without re-counting the per-partition `MaterializationOutput.partition` entries.
    """

    model: str
    partitions_failed: conint(ge=0)
    partitions_planned: conint(ge=0)
    partitions_skipped: conint(ge=0)
    """
    Partitions that were already `Computed` in the state store and skipped by the runtime (currently always 0; reserved for the `--missing` change-detection optimization).
    """
    partitions_succeeded: conint(ge=0)


class PermissionSummary(BaseModel):
    catalogs_created: conint(ge=0)
    grants_added: conint(ge=0)
    grants_revoked: conint(ge=0)
    schemas_created: conint(ge=0)


class TableCheckOutput(BaseModel):
    asset_key: list[str]
    checks: list[
        CheckResult1 | CheckResult2 | CheckResult3 | CheckResult4 | CheckResult5
    ]


class TableErrorOutput(BaseModel):
    """
    Error from a table that failed during parallel processing.
    """

    asset_key: list[str]
    error: str


class MaterializationOutput(BaseModel):
    asset_key: list[str]
    duration_ms: conint(ge=0)
    metadata: MaterializationMetadata
    partition: PartitionInfo | None = None
    """
    Partition window this materialization targeted, present only when the model's strategy is `time_interval`. `None` for unpartitioned strategies (full_refresh, incremental, merge).
    """
    rows_copied: conint(ge=0) | None = None


class RunOutput(BaseModel):
    """
    JSON output for `rocky run`.
    """

    anomalies: list[AnomalyOutput]
    check_results: list[TableCheckOutput]
    command: str
    drift: DriftSummary
    duration_ms: conint(ge=0)
    errors: list[TableErrorOutput]
    excluded_tables: list[ExcludedTableOutput]
    """
    Tables that the discovery adapter reported as enabled but that do not exist in the source warehouse (e.g. Fivetran has them configured but hasn't synced them, or they carry the `do_not_alter__` broken-table marker). Surfaced so orchestrators can flag the gap in their UIs instead of silently dropping the assets.
    """
    execution: ExecutionSummary
    filter: str
    materializations: list[MaterializationOutput]
    metrics: MetricsSnapshot | None = None
    partition_summaries: list[PartitionSummary]
    """
    Per-model partition execution summaries, present only when the run touched one or more `time_interval` models. Empty for runs that didn't execute any partitioned models.
    """
    permissions: PermissionSummary
    pipeline_type: str | None = None
    """
    Pipeline type that was executed (e.g., "replication").
    """
    resumed_from: str | None = None
    shadow: bool
    """
    True when running in shadow mode (targets rewritten).
    """
    tables_copied: conint(ge=0)
    tables_failed: conint(ge=0)
    tables_skipped: conint(ge=0)
    version: str
