# generated by datamodel-codegen:
#   filename:  state.schema.json
#   timestamp: 2026-04-13T18:41:57+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel


class WatermarkEntry(BaseModel):
    last_value: AwareDatetime
    table: str
    updated_at: AwareDatetime


class StateOutput(BaseModel):
    """
    JSON output for `rocky state show`.
    """

    command: str
    version: str
    watermarks: list[WatermarkEntry]
