# generated by datamodel-codegen:
#   filename:  state_retention_sweep.schema.json

from __future__ import annotations

from pydantic import BaseModel, conint


class RetentionSweepOutput(BaseModel):
    """
    JSON output for `rocky state retention sweep`.

    Mirrors [`rocky_core::retention::SweepReport`] with the version/command envelope every CLI JSON output carries. `dry_run = true` reports counts that *would* result without touching the state store.
    """

    audit_deleted: conint(ge=0)
    """
    Quality snapshots (`quality_history`) deleted, or that would be deleted.
    """
    audit_kept: conint(ge=0)
    """
    Quality snapshots remaining.
    """
    command: str
    domains: list[str]
    """
    Domains that were considered in this sweep, as the canonical lowercase strings (`"history"`, `"lineage"`, `"audit"`).
    """
    dry_run: bool
    """
    `true` when `--dry-run` was set; the state store was left untouched.
    """
    duration_ms: conint(ge=0)
    """
    Wall-clock duration of the sweep in milliseconds.
    """
    lineage_deleted: conint(ge=0)
    """
    DAG snapshots (`dag_snapshots`) deleted, or that would be deleted.
    """
    lineage_kept: conint(ge=0)
    """
    DAG snapshots remaining.
    """
    max_age_days: conint(ge=0)
    """
    Configured retention window in days at the time of the sweep.
    """
    min_runs_kept: conint(ge=0)
    """
    Configured per-domain floor at the time of the sweep.
    """
    runs_deleted: conint(ge=0)
    """
    Run records (`run_history`) deleted, or that would be deleted in dry-run mode.
    """
    runs_kept: conint(ge=0)
    """
    Run records remaining after the sweep.
    """
    version: str
