# generated by datamodel-codegen:
#   filename:  test.schema.json
#   timestamp: 2026-04-15T09:43:31+00:00

from __future__ import annotations

from pydantic import BaseModel, conint


class DeclarativeTestResult(BaseModel):
    """
    Result of a single declarative test assertion.
    """

    column: str | None = None
    """
    Column under test, if applicable.
    """
    detail: str | None = None
    """
    Human-readable detail (e.g., "3 NULL rows found" or execution error).
    """
    model: str
    """
    Model name the test belongs to.
    """
    severity: str
    """
    Severity declared in the sidecar ("error" or "warning").
    """
    sql: str
    """
    The SQL that was executed.
    """
    status: str
    """
    "pass", "fail", or "error".
    """
    table: str
    """
    Fully-qualified target table (catalog.schema.table).
    """
    test_type: str
    """
    Test type (e.g., "not_null", "unique", "row_count_range").
    """


class DeclarativeTestSummary(BaseModel):
    """
    Summary of declarative test execution (from `[[tests]]` in model sidecars).
    """

    errored: conint(ge=0)
    failed: conint(ge=0)
    passed: conint(ge=0)
    results: list[DeclarativeTestResult]
    total: conint(ge=0)
    warned: conint(ge=0)


class TestFailure(BaseModel):
    """
    One failed test, mirroring the (name, error) tuple in `rocky_engine::test_runner::TestResult::failures` but with named fields because schemars/JSON Schema can't represent positional tuples cleanly.
    """

    error: str
    name: str


class TestOutput(BaseModel):
    """
    JSON output for `rocky test`.
    """

    command: str
    declarative: DeclarativeTestSummary | None = None
    """
    Results from declarative `[[tests]]` in model sidecars. Present only when `--declarative` is used.
    """
    failed: conint(ge=0)
    failures: list[TestFailure]
    passed: conint(ge=0)
    total: conint(ge=0)
    version: str
