# generated by datamodel-codegen:
#   filename:  test_adapter.schema.json
#   timestamp: 2026-04-15T01:23:11+00:00

from __future__ import annotations

from pydantic import BaseModel, conint


class TestAdapterTestResult(BaseModel):
    category: str
    """
    Stringified `TestCategory`: "connection", "ddl", "dml", "query", "types", "dialect", "governance", "discovery", "batch_checks".
    """
    duration_ms: conint(ge=0)
    message: str | None = None
    name: str
    status: str
    """
    Stringified `TestStatus`: "passed", "failed", "skipped".
    """


class TestAdapterOutput(BaseModel):
    """
    JSON output for `rocky test-adapter`.

    Mirrors `rocky_adapter_sdk::conformance::ConformanceResult` with the status/category enums stringified, so we don't have to add `JsonSchema` to the SDK crate.
    """

    adapter: str
    results: list[TestAdapterTestResult]
    sdk_version: str
    tests_failed: conint(ge=0)
    tests_passed: conint(ge=0)
    tests_run: conint(ge=0)
    tests_skipped: conint(ge=0)
