# generated by datamodel-codegen:
#   filename:  validate_migration.schema.json
#   timestamp: 2026-04-15T01:23:11+00:00

from __future__ import annotations

from pydantic import BaseModel, conint


class ModelValidationOutput(BaseModel):
    compile_ok: bool
    contracts_generated: conint(ge=0)
    dbt_description: str | None = None
    model: str
    present_in_dbt: bool
    present_in_rocky: bool
    rocky_intent: str | None = None
    test_count: conint(ge=0)
    warnings: list[str]


class ValidateMigrationOutput(BaseModel):
    """
    JSON output for `rocky validate-migration`.
    """

    command: str
    dbt_version: str | None = None
    models_failed: conint(ge=0)
    models_imported: conint(ge=0)
    project_name: str | None = None
    total_contracts: conint(ge=0)
    total_tests: conint(ge=0)
    total_warnings: conint(ge=0)
    validations: list[ModelValidationOutput]
    version: str
