#!/usr/bin/env bash
# Recompute POC counts from the on-disk catalog and rewrite the hand-typed
# counts in examples/playground/README.md so they can't silently drift.
#
# Single source of truth: the directories under examples/playground/pocs/.
#
# This script writes three surfaces:
#   1. examples/playground/README.md — per-category "(N POCs · ...)" headers
#      and the "N of M POCs run with no external credentials." line.
#      (git-tracked; the codegen-style drift check diffs this file.)
#   2. examples/playground/pocs/README.md — the "N small POCs across 8
#      categories" headline, the per-category "(N POCs · ...)" bullets, and
#      the "N of M | None" credentials-table row. (git-tracked; kept in sync
#      here so the catalog READMEs can't disagree — this is the surface that
#      previously drifted because nothing rewrote it.)
#   3. docs/src/data/poc-counts.json + docs/public/llms.txt — regenerated by
#      delegating to docs/scripts/count-pocs.mjs (the existing build-time
#      authority). Both are gitignored and rendered fresh by the docs build,
#      so they are not part of the drift check; we refresh them here only so a
#      local run leaves a consistent tree.
#
# Credential-free count = total POCs minus the number of POCs whose run.sh
# carries a `${VAR:?...}` guard (the documented marker the parse-validate
# harness uses to detect credential-gated POCs — see playground CLAUDE.md).
#
# Idempotent: running twice produces no diff.
#
# Usage: bash scripts/update-poc-counts.sh
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
pocs_root="$repo_root/examples/playground/pocs"
readme="$repo_root/examples/playground/README.md"
pocs_readme="$pocs_root/README.md"

if [ ! -d "$pocs_root" ]; then
    echo "error: $pocs_root not found" >&2
    exit 1
fi
if [ ! -f "$readme" ]; then
    echo "error: $readme not found" >&2
    exit 1
fi
if [ ! -f "$pocs_readme" ]; then
    echo "error: $pocs_readme not found" >&2
    exit 1
fi

# --- Count POCs per category and in total ------------------------------------
# Count every immediate subdirectory of each category, matching the semantics
# of docs/scripts/count-pocs.mjs so the README and the generated JSON can never
# disagree. (Plain shell vars, no associative arrays, so this runs on the
# bash 3.2 shipped on macOS as well as CI's bash 4+.)
total=0
credential_gated=0

for category_dir in "$pocs_root"/*/; do
    [ -d "$category_dir" ] || continue
    category="$(basename "$category_dir")"
    count=0
    for poc_dir in "$category_dir"*/; do
        [ -d "$poc_dir" ] || continue
        count=$((count + 1))
        run_sh="$poc_dir/run.sh"
        # A `${VAR:?...}` guard in run.sh marks a credential-gated POC.
        if [ -f "$run_sh" ] && grep -qE '\$\{[A-Za-z_][A-Za-z0-9_]*:\?' "$run_sh"; then
            credential_gated=$((credential_gated + 1))
        fi
    done
    total=$((total + count))

    # The category dir is e.g. "00-foundations"; the README header uses the
    # two-digit prefix. Rewrite only the numeric token before " POCs" on the
    # matching "### NN — ... (N POCs" line — targeted and idempotent.
    prefix="${category%%-*}"
    perl -i -pe "s/^(### ${prefix} .*\\()\\d+( POCs)/\${1}${count}\${2}/" "$readme"

    # pocs/README.md bullet: "- [NN-name](NN-name/): ... (N POCs · ...)".
    # Rewrite only the count in the trailing "(N POCs ·" token on the bullet
    # line for this category — the "·" anchor keeps it off any other paren.
    perl -i -pe "s/^(- \\[${category}\\].*\\()\\d+( POCs ·)/\${1}${count}\${2}/" "$pocs_readme"

    echo "  $category: $count"
done

credential_free=$((total - credential_gated))

echo "poc-counts: total=$total credential_free=$credential_free (gated=$credential_gated)"

# --- Rewrite the credential-free line ----------------------------------------
# "**62 of 75 POCs run with no external credentials.**"
perl -i -pe "s/^\\*\\*\\d+ of \\d+ POCs run with no external credentials\\.\\*\\*/**${credential_free} of ${total} POCs run with no external credentials.**/" "$readme"

# --- Rewrite pocs/README.md headline + credentials-table row -----------------
# Headline: "99 small POCs across 8 categories."
perl -i -pe "s/^\\d+( small POCs across )/${total}\${1}/" "$pocs_readme"
# Credentials table: "| 87 of 99 | None ...".
perl -i -pe "s/^(\\| )\\d+ of \\d+( \\| None)/\${1}${credential_free} of ${total}\${2}/" "$pocs_readme"

# --- Regenerate the (gitignored) docs JSON + llms.txt ------------------------
# Delegate to the existing build-time authority so there is one JSON writer.
if command -v node >/dev/null 2>&1; then
    node "$repo_root/docs/scripts/count-pocs.mjs"
else
    echo "note: node not found; skipped docs/src/data/poc-counts.json refresh" >&2
fi

echo "poc-counts: README updated."
