import * as vscode from "vscode";
import {
  runRockyJsonWithProgress,
  runRockyWithProgress,
  showRockyError,
} from "../rockyCli";
import type {
  ArchiveResult,
  CompactResult,
  ProfileStorageResult,
} from "../types/rockyJson";
import {
  confirmAction,
  ensureWorkspace,
  promptForInput,
  showJsonInEditor,
  showSqlInEditor,
} from "./ui";

/**
 * Generates and previews compaction SQL for a model. Always runs `--dry-run`
 * first; an "Apply" follow-up re-invokes the CLI without the flag, after
 * confirming with the user.
 */
export async function compact(): Promise<void> {
  if (!ensureWorkspace()) return;

  const table = await promptForInput("Table to compact (catalog.schema.table)", {
    placeHolder: "e.g., main.analytics.fct_daily_revenue",
    required: true,
  });
  if (!table) return;

  let dryRunResult: CompactResult;
  try {
    dryRunResult = await runRockyJsonWithProgress<CompactResult>(
      `Planning compaction for ${table}...`,
      ["compact", table, "--dry-run", "--output", "json"],
      { timeoutMs: 30000 },
    );
  } catch (err) {
    showRockyError("Compact (dry-run) failed", err);
    return;
  }

  if (dryRunResult.sql) {
    await showSqlInEditor(`-- DRY RUN — generated by rocky compact\n${dryRunResult.sql}`);
  } else {
    vscode.window.showInformationMessage("Rocky compact: nothing to do.");
    return;
  }

  const apply = await confirmAction(
    `Apply compaction to ${table}?`,
    "Apply",
    "This executes the SQL above against your warehouse.",
  );
  if (!apply) return;

  try {
    await runRockyWithProgress(
      `Applying compaction to ${table}...`,
      ["compact", table, "--output", "json"],
      { timeoutMs: 0 },
    );
    vscode.window.showInformationMessage(`Compaction applied to ${table}.`);
  } catch (err) {
    showRockyError("Compact apply failed", err);
  }
}

export async function archive(): Promise<void> {
  if (!ensureWorkspace()) return;

  const olderThan = await promptForInput("Archive partitions older than", {
    placeHolder: "e.g., 90d, 6m, 1y",
    value: "90d",
    required: true,
  });
  if (!olderThan) return;

  const model = await promptForInput(
    "Filter to a specific model (leave empty for all)",
    { placeHolder: "e.g., events" },
  );

  const baseArgs = ["archive", "--older-than", olderThan, "--output", "json"];
  if (model) baseArgs.push("--model", model);

  let dryRunResult: ArchiveResult;
  try {
    dryRunResult = await runRockyJsonWithProgress<ArchiveResult>(
      "Planning archive...",
      [...baseArgs, "--dry-run"],
      { timeoutMs: 30000 },
    );
  } catch (err) {
    showRockyError("Archive (dry-run) failed", err);
    return;
  }

  const partitions = dryRunResult.partitions_to_archive ?? 0;
  const tables = dryRunResult.tables_affected ?? 0;
  if (partitions === 0) {
    vscode.window.showInformationMessage("Rocky archive: nothing to archive.");
    return;
  }

  await showJsonInEditor(JSON.stringify(dryRunResult));

  const apply = await confirmAction(
    `Archive ${partitions} partition${partitions === 1 ? "" : "s"} across ${tables} table${tables === 1 ? "" : "s"}?`,
    "Archive",
    "This permanently removes data from the affected tables.",
  );
  if (!apply) return;

  try {
    await runRockyWithProgress("Applying archive...", baseArgs, {
      timeoutMs: 0,
    });
    vscode.window.showInformationMessage(
      `Archived ${partitions} partition${partitions === 1 ? "" : "s"}.`,
    );
  } catch (err) {
    showRockyError("Archive apply failed", err);
  }
}

export async function profileStorage(): Promise<void> {
  if (!ensureWorkspace()) return;

  const table = await promptForInput("Table to profile", {
    placeHolder: "e.g., main.analytics.fct_daily_revenue",
    required: true,
  });
  if (!table) return;

  try {
    const result = await runRockyJsonWithProgress<ProfileStorageResult>(
      `Profiling ${table}...`,
      ["profile-storage", table, "--output", "json"],
      { timeoutMs: 60000 },
    );

    const recs = result.recommendations?.length ?? 0;
    vscode.window.showInformationMessage(
      `Rocky profile-storage: ${recs} recommendation${recs === 1 ? "" : "s"}.`,
    );
    await showJsonInEditor(JSON.stringify(result));
  } catch (err) {
    showRockyError("Profile storage failed", err);
  }
}
