//! `rocky export-schemas <dir>` — emit JSON Schema files for every CLI
//! `--output json` payload type. Used by the dagster + vscode codegen
//! pipelines (Phase 2 of the monorepo consolidation).
//!
//! The schema files are the canonical source of truth for the Pydantic
//! models in `integrations/dagster` and the TypeScript interfaces in
//! `editors/vscode`. They are committed to the `schemas/` directory at the
//! monorepo root and regenerated by this command on every change to the
//! Rust output structs.

use std::path::Path;

use anyhow::{Context, Result};
use rocky_core::config::{AdapterConfig, RockyConfig};
use schemars::{JsonSchema, schema_for};
use serde::Serialize;

use crate::commands::doctor::DoctorOutput;
use crate::output::{
    AiExplainOutput, AiGenerateOutput, AiSyncOutput, AiTestOutput, ArchiveOutput,
    BranchDeleteOutput, BranchListOutput, BranchOutput, CatalogOutput, CiDiffOutput, CiOutput,
    ClearSchemaCacheOutput, ColumnLineageOutput, CompactDedupOutput, CompactOutput, CompareOutput,
    CompileOutput, ComplianceOutput, CostOutput, DagOutput, DagRunOutput, DiscoverOutput,
    DriftOutput, EstimateOutput, HistoryOutput, HooksListOutput, HooksTestOutput, ImportDbtOutput,
    LineageDiffOutput, LineageOutput, LoadOutput, MetricsOutput, ModelHistoryOutput,
    OptimizeOutput, PlanOutput, PreviewCostOutput, PreviewCreateOutput, PreviewDiffOutput,
    ProfileStorageOutput, ReplayOutput, RetentionStatusOutput, RetentionSweepOutput, RunOutput,
    SeedOutput, StateOutput, TestAdapterOutput, TestOutput, TraceOutput, ValidateMigrationOutput,
    ValidateOutput,
};

/// Top-level command output types currently covered by schemars.
///
/// As of Phase 2 round 14, every Rocky CLI command that emits
/// `--output json` is registered here. Adding a new entry is the only
/// thing required to expose a new command's schema once its output
/// type derives `JsonSchema`. The `roundtrip` test below catches the
/// case where someone adds a new output struct but forgets to register
/// it (it asserts the count matches the committed `schemas/` directory).
fn schemas() -> Vec<(&'static str, serde_json::Value)> {
    fn entry<T: JsonSchema + Serialize>(name: &'static str) -> (&'static str, serde_json::Value) {
        let schema = schema_for!(T);
        (
            name,
            serde_json::to_value(schema).expect("schema serialization is infallible"),
        )
    }

    vec![
        entry::<DiscoverOutput>("discover"),
        entry::<RunOutput>("run"),
        entry::<PlanOutput>("plan"),
        entry::<DriftOutput>("drift"),
        entry::<StateOutput>("state"),
        entry::<ClearSchemaCacheOutput>("state_clear_schema_cache"),
        entry::<DoctorOutput>("doctor"),
        entry::<CompileOutput>("compile"),
        entry::<TestOutput>("test"),
        entry::<CiOutput>("ci"),
        entry::<CiDiffOutput>("ci_diff"),
        entry::<OptimizeOutput>("optimize"),
        entry::<EstimateOutput>("estimate"),
        entry::<HistoryOutput>("history"),
        entry::<ModelHistoryOutput>("model_history"),
        entry::<MetricsOutput>("metrics"),
        entry::<AiGenerateOutput>("ai"),
        entry::<AiSyncOutput>("ai_sync"),
        entry::<AiExplainOutput>("ai_explain"),
        entry::<AiTestOutput>("ai_test"),
        entry::<LineageOutput>("lineage"),
        entry::<ColumnLineageOutput>("column_lineage"),
        entry::<LineageDiffOutput>("lineage_diff"),
        entry::<CatalogOutput>("catalog"),
        entry::<CompareOutput>("compare"),
        entry::<CompactOutput>("compact"),
        entry::<CompactDedupOutput>("compact_dedup"),
        entry::<ArchiveOutput>("archive"),
        entry::<ProfileStorageOutput>("profile_storage"),
        entry::<ImportDbtOutput>("import_dbt"),
        entry::<HooksListOutput>("hooks_list"),
        entry::<HooksTestOutput>("hooks_test"),
        entry::<ValidateMigrationOutput>("validate_migration"),
        entry::<TestAdapterOutput>("test_adapter"),
        entry::<ValidateOutput>("validate"),
        entry::<SeedOutput>("seed"),
        entry::<LoadOutput>("load"),
        entry::<DagOutput>("dag"),
        entry::<DagRunOutput>("dag_run"),
        entry::<BranchOutput>("branch"),
        entry::<BranchListOutput>("branch_list"),
        entry::<BranchDeleteOutput>("branch_delete"),
        entry::<ReplayOutput>("replay"),
        entry::<TraceOutput>("trace"),
        entry::<CostOutput>("cost"),
        entry::<PreviewCreateOutput>("preview_create"),
        entry::<PreviewDiffOutput>("preview_diff"),
        entry::<PreviewCostOutput>("preview_cost"),
        entry::<ComplianceOutput>("compliance"),
        entry::<RetentionStatusOutput>("retention_status"),
        entry::<RetentionSweepOutput>("state_retention_sweep"),
        // Config types feeding the VS Code project schema. Not CLI command
        // outputs, but exported through the same pipeline so the IDE-facing
        // `editors/vscode/schemas/rocky-project.schema.json` is generated
        // from Rust types. The `just codegen` recipe copies `rocky_project`
        // into the editor directory after this command runs.
        entry::<AdapterConfig>("adapter_config"),
        entry::<RockyConfig>("rocky_project"),
    ]
}

pub fn export_schemas(output_dir: &Path) -> Result<()> {
    std::fs::create_dir_all(output_dir)
        .with_context(|| format!("creating {}", output_dir.display()))?;

    let entries = schemas();
    let count = entries.len();

    for (name, schema) in entries {
        let path = output_dir.join(format!("{name}.schema.json"));
        let pretty = serde_json::to_string_pretty(&schema).context("serializing schema to JSON")?;
        std::fs::write(&path, pretty + "\n")
            .with_context(|| format!("writing {}", path.display()))?;
        println!("wrote {}", path.display());
    }

    println!("\nExported {count} schemas to {}", output_dir.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    /// Every entry in `schemas()` must produce a valid Draft-07 JSON Schema
    /// with at least a top-level `type`, `$ref`, or `oneOf`. Catches the
    /// failure mode where a struct's `JsonSchema` derive misbehaves.
    #[test]
    fn every_entry_produces_a_valid_schema() {
        for (name, schema) in schemas() {
            let obj = schema
                .as_object()
                .unwrap_or_else(|| panic!("schema for `{name}` is not a JSON object"));
            assert!(
                obj.contains_key("$schema"),
                "schema for `{name}` is missing the $schema header"
            );
            assert!(
                obj.contains_key("type") || obj.contains_key("$ref") || obj.contains_key("oneOf"),
                "schema for `{name}` has neither `type`, `$ref`, nor `oneOf` at the top level"
            );
        }
    }

    /// Catch accidental duplicate registrations (e.g., copy-paste errors
    /// where two structs end up under the same command name). The codegen
    /// pipeline would silently overwrite the second one with the first, so
    /// guard against it at the source.
    #[test]
    fn schema_names_are_unique() {
        let names: Vec<&str> = schemas().into_iter().map(|(n, _)| n).collect();
        let unique: HashSet<&str> = names.iter().copied().collect();
        assert_eq!(
            names.len(),
            unique.len(),
            "duplicate schema names detected: {names:?}"
        );
    }

    /// The committed `schemas/` directory at the monorepo root must contain
    /// exactly one `.schema.json` file per entry in `schemas()`. If someone
    /// adds a new output struct, registers it here, and forgets to commit
    /// the regenerated file (or vice versa), this test fails.
    ///
    /// Skipped silently when the schemas/ directory isn't reachable from
    /// CARGO_MANIFEST_DIR (e.g., when the crate is checked out in isolation
    /// outside the monorepo, or when cargo's working directory has been
    /// remapped).
    #[test]
    fn registered_schemas_match_committed_files() {
        let manifest_dir = env!("CARGO_MANIFEST_DIR");
        // crates/rocky-cli → engine → workspace root → schemas/
        let schemas_dir = std::path::Path::new(manifest_dir)
            .join("..")
            .join("..")
            .join("..")
            .join("schemas");

        if !schemas_dir.is_dir() {
            eprintln!(
                "skipping registered_schemas_match_committed_files: \
                 {} not found (running outside the monorepo?)",
                schemas_dir.display()
            );
            return;
        }

        let registered: HashSet<String> = schemas()
            .into_iter()
            .map(|(name, _)| format!("{name}.schema.json"))
            .collect();

        let committed: HashSet<String> = std::fs::read_dir(&schemas_dir)
            .expect("reading schemas/ directory")
            .filter_map(Result::ok)
            .filter_map(|e| e.file_name().into_string().ok())
            .filter(|n| n.ends_with(".schema.json"))
            .collect();

        let only_registered: Vec<&String> = registered.difference(&committed).collect();
        let only_committed: Vec<&String> = committed.difference(&registered).collect();
        assert!(
            only_registered.is_empty() && only_committed.is_empty(),
            "schemas drift detected:\n  registered but not committed: {only_registered:?}\n  committed but not registered: {only_committed:?}\n  Run `just codegen` to refresh the committed bindings."
        );
    }
}
