/**
 * The one way the SPA talks to the engine: same-origin `fetch` against
 * `/api/v1`, the bearer token on every call, and every failure surfaced as
 * the server's error envelope (never a bare status).
 *
 * The payloads are the typed `*Output` shapes the CLI prints; their
 * TypeScript interfaces are generated by `just codegen` and imported from
 * the one generated tree (see `tsconfig.json`'s `@rocky-types` alias).
 */

import type { ErrorEnvelope } from "@rocky-types/error_envelope";
import { TOKEN_STORAGE_KEY } from "./token";

/** A refused request: the server's envelope plus the HTTP status. */
export class ApiError extends Error {
  readonly status: number;
  readonly envelope: ErrorEnvelope;

  constructor(status: number, envelope: ErrorEnvelope) {
    super(`${envelope.code}: ${envelope.message}`);
    this.name = "ApiError";
    this.status = status;
    this.envelope = envelope;
  }
}

export interface ApiClientOptions {
  fetch?: typeof fetch;
  storage?: { getItem: (k: string) => string | null };
  /** Defaults to `""` (same origin). Tests pass an absolute base. */
  base?: string;
}

/**
 * `GET /api/v1/<path>` with the tab's token. Resolves to the parsed payload,
 * rejects with `ApiError` on a non-2xx answer. A body that is not JSON is
 * reported as an envelope too, so a caller always gets one shape.
 */
export async function apiGet<T>(path: string, options: ApiClientOptions = {}): Promise<T> {
  const doFetch = options.fetch ?? fetch;
  const storage = options.storage ?? sessionStorage;
  const base = options.base ?? "";
  const headers: Record<string, string> = { Accept: "application/json" };
  const token = storage.getItem(TOKEN_STORAGE_KEY);
  if (token) headers.Authorization = `Bearer ${token}`;

  const response = await doFetch(`${base}/api/v1/${path.replace(/^\/+/, "")}`, { headers });
  const text = await response.text();
  const body = parseJson(text);
  if (!response.ok) {
    throw new ApiError(response.status, asEnvelope(body, response.status));
  }
  return body as T;
}

/** A body that is not JSON is `null`, never a thrown error. */
function parseJson(text: string): unknown {
  if (text === "") return null;
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

/** Coerce whatever the server answered into the envelope shape. */
function asEnvelope(body: unknown, status: number): ErrorEnvelope {
  if (
    typeof body === "object" &&
    body !== null &&
    typeof (body as { code?: unknown }).code === "string" &&
    typeof (body as { message?: unknown }).message === "string"
  ) {
    return body as ErrorEnvelope;
  }
  return {
    code: `http_${status}`,
    message: `the server answered ${status} without an error envelope`,
  };
}
