/**
 * The one way the SPA talks to the engine: same-origin `fetch` against
 * `/api/v1`, the session cookie on every call, and every failure surfaced as
 * the server's error envelope (never a bare status).
 *
 * The page never holds the token. `rocky serve --ui` prints a `/login?t=…`
 * link; opening it sets an `HttpOnly` session cookie and lands here. Every
 * call sends that cookie (`credentials: "same-origin"`) and `X-Rocky-UI: 1`,
 * which the server requires on a cookie-authenticated write. A `401` means
 * the session is gone (the server restarted, or the link was never opened):
 * the shell then asks for the newest link.
 *
 * The payloads are the typed `*Output` shapes the CLI prints; their
 * TypeScript interfaces are generated by `just codegen` and imported from
 * the one generated tree (see `tsconfig.json`'s `@rocky-types` alias).
 */

import type { ErrorEnvelope } from "@rocky-types/error_envelope";

/** A refused request: the server's envelope plus the HTTP status. */
export class ApiError extends Error {
  readonly status: number;
  readonly envelope: ErrorEnvelope;

  constructor(status: number, envelope: ErrorEnvelope) {
    super(`${envelope.code}: ${envelope.message}`);
    this.name = "ApiError";
    this.status = status;
    this.envelope = envelope;
  }
}

/** What a `401` tells the person. The server's own envelope is kept too. */
export const SESSION_EXPIRED_HINT =
  "Session expired — open the newest Rocky UI: link from the console.";

/** The event the shell listens for to swap the page for the sign-in note. */
export const SESSION_EXPIRED_EVENT = "rocky:session-expired";

export interface ApiClientOptions {
  fetch?: typeof fetch;
  /** Defaults to `""` (same origin). Tests pass an absolute base. */
  base?: string;
  /**
   * Extra request headers. The one caller today is the samples panel, which
   * must send `X-Rocky-Allow-Warehouse: true` — and only when the viewer has
   * asked for rows, never on a page load. Kept out of the default so a header
   * that spends money is always written at its call site.
   */
  headers?: Record<string, string>;
  /** Where a `401` is announced. Defaults to `window`; tests pass a target. */
  events?: Pick<EventTarget, "dispatchEvent">;
}

/**
 * Headers the page never sends, whatever a caller passes. `X-Rocky-Principal`
 * is an advisory audit label anyone can set; the browser must not claim a
 * principal it cannot prove. `Authorization` would mix a bearer secret into
 * a cookie session.
 */
const NEVER_SENT = ["x-rocky-principal", "authorization"];

function requestHeaders(extra: Record<string, string> | undefined): Record<string, string> {
  const headers: Record<string, string> = { Accept: "application/json", "X-Rocky-UI": "1" };
  for (const [name, value] of Object.entries(extra ?? {})) {
    if (!NEVER_SENT.includes(name.toLowerCase())) headers[name] = value;
  }
  return headers;
}

async function request<T>(
  path: string,
  init: { method: "GET" | "POST"; body?: string },
  options: ApiClientOptions,
): Promise<T> {
  const doFetch = options.fetch ?? fetch;
  const base = options.base ?? "";
  const headers = requestHeaders(options.headers);
  if (init.body !== undefined) headers["Content-Type"] = "application/json";

  const response = await doFetch(`${base}/api/v1/${path.replace(/^\/+/, "")}`, {
    method: init.method,
    headers,
    body: init.body,
    credentials: "same-origin",
  });
  const text = await response.text();
  const body = parseJson(text);
  if (!response.ok) {
    const envelope = asEnvelope(body, response.status);
    if (response.status === 401) {
      announceSessionExpired(options.events);
      throw new ApiError(401, { ...envelope, remediation_hint: SESSION_EXPIRED_HINT });
    }
    throw new ApiError(response.status, envelope);
  }
  return body as T;
}

function announceSessionExpired(events: ApiClientOptions["events"]): void {
  const target = events ?? (typeof window === "undefined" ? undefined : window);
  target?.dispatchEvent(new Event(SESSION_EXPIRED_EVENT));
}

/**
 * `GET /api/v1/<path>` with the session cookie. Resolves to the parsed
 * payload, rejects with `ApiError` on a non-2xx answer. A body that is not
 * JSON is reported as an envelope too, so a caller always gets one shape.
 */
export function apiGet<T>(path: string, options: ApiClientOptions = {}): Promise<T> {
  return request<T>(path, { method: "GET" }, options);
}

/**
 * `POST /api/v1/<path>` with a JSON body, the session cookie and
 * `X-Rocky-UI: 1`. The browser adds the `Origin` header itself, and the
 * server requires both on a cookie write.
 */
export function apiPost<T>(path: string, body: unknown, options: ApiClientOptions = {}): Promise<T> {
  return request<T>(path, { method: "POST", body: JSON.stringify(body ?? {}) }, options);
}

/** A body that is not JSON is `null`, never a thrown error. */
function parseJson(text: string): unknown {
  if (text === "") return null;
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

/** Coerce whatever the server answered into the envelope shape. */
function asEnvelope(body: unknown, status: number): ErrorEnvelope {
  if (
    typeof body === "object" &&
    body !== null &&
    typeof (body as { code?: unknown }).code === "string" &&
    typeof (body as { message?: unknown }).message === "string"
  ) {
    return body as ErrorEnvelope;
  }
  return {
    code: `http_${status}`,
    message: `the server answered ${status} without an error envelope`,
  };
}
