name: dagster-ci

on:
  push:
    branches: [main]
    paths:
      - 'integrations/dagster/**'
      - 'sdk/python/**'
      - 'schemas/**'
      - '.github/workflows/dagster-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'integrations/dagster/**'
      - 'sdk/python/**'
      - 'schemas/**'
      - '.github/workflows/dagster-ci.yml'

defaults:
  run:
    working-directory: integrations/dagster

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - run: uv sync --dev
      - run: uv run python -m pytest -v
      - run: uv run python -m ruff check src/ tests/
      - run: uv run python -m ruff format --check src/ tests/
