name: dagster-ci

on:
  push:
    branches: [main]
    paths:
      - 'integrations/dagster/**'
      - 'sdk/python/**'
      - 'schemas/**'
      - '.github/workflows/dagster-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'integrations/dagster/**'
      - 'sdk/python/**'
      - 'schemas/**'
      - '.github/workflows/dagster-ci.yml'

defaults:
  run:
    working-directory: integrations/dagster

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - run: uv sync --dev
      - run: uv run python -m pytest -v
      - run: uv run python -m ruff check src/ tests/
      - run: uv run python -m ruff format --check src/ tests/
