name: vscode-ci

on:
  push:
    branches: [main]
    paths:
      - 'editors/vscode/**'
      - 'schemas/**'
      - '.github/workflows/vscode-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'editors/vscode/**'
      - 'schemas/**'
      - '.github/workflows/vscode-ci.yml'

defaults:
  run:
    working-directory: editors/vscode

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: editors/vscode/package-lock.json
      - run: npm ci
      - run: npm run compile
      - name: Run tests
        uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3 # v1
        with:
          working-directory: editors/vscode
          run: npm test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: editors/vscode/package-lock.json
      - run: npm ci
      - run: npm run lint
